;(function(){
var g,aa=this;function ba(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a){var b=n(a);return"array"==b||"object"==b&&"number"==typeof a.length}function da(a){return"string"==typeof a}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var fa="closure_uid_"+(1E9*Math.random()>>>0),ha=0;var ia;function ja(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ka(a,b){return a<b?-1:a>b?1:0};var la=Array.prototype,ma=la.forEach?function(a,b,c){la.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=da(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function na(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var oa,pa,qa,ra;function ta(){return aa.navigator?aa.navigator.userAgent:null}ra=qa=pa=oa=!1;var ua;if(ua=ta()){var va=aa.navigator;oa=0==ua.lastIndexOf("Opera",0);pa=!oa&&(-1!=ua.indexOf("MSIE")||-1!=ua.indexOf("Trident"));qa=!oa&&-1!=ua.indexOf("WebKit");ra=!oa&&!qa&&!pa&&"Gecko"==va.product}var wa=oa,r=pa,xa=ra,ya=qa;function za(){var a=aa.document;return a?a.documentMode:void 0}var Aa;
a:{var Ba="",Ca;if(wa&&aa.opera)var Da=aa.opera.version,Ba="function"==typeof Da?Da():Da;else if(xa?Ca=/rv\:([^\);]+)(\)|;)/:r?Ca=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:ya&&(Ca=/WebKit\/(\S+)/),Ca)var Ea=Ca.exec(ta()),Ba=Ea?Ea[1]:"";if(r){var Fa=za();if(Fa>parseFloat(Ba)){Aa=String(Fa);break a}}Aa=Ba}var Ga={};
function Ia(a){var b;if(!(b=Ga[a])){b=0;for(var c=ja(String(Aa)).split("."),d=ja(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(h)||["","",""],q=m.exec(k)||["","",""];if(0==p[0].length&&0==q[0].length)break;b=ka(0==p[1].length?0:parseInt(p[1],10),0==q[1].length?0:parseInt(q[1],10))||ka(0==p[2].length,0==q[2].length)||ka(p[2],q[2])}while(0==b)}b=Ga[a]=0<=b}return b}
var Ja=aa.document,La=Ja&&r?za()||("CSS1Compat"==Ja.compatMode?parseInt(Aa,10):5):void 0;!xa&&!r||r&&r&&9<=La||xa&&Ia("1.9.1");r&&Ia("9");function Ma(){return!0};function Na(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function Oa(){var a=document;return a.querySelectorAll&&a.querySelector?a.querySelectorAll("HTML"):a.getElementsByTagName("HTML")}function Pa(a,b,c){function d(d){d&&b.appendChild(da(d)?a.createTextNode(d):d)}for(var e=1;e<c.length;e++){var f=c[e];!ca(f)||ea(f)&&0<f.nodeType?d(f):ma(Qa(f)?na(f):f,d)}}function Qa(a){if(a&&"number"==typeof a.length){if(ea(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==n(a))return"function"==typeof a.item}return!1}
function Ra(a){this.bb=a||aa.document||document}Ra.prototype.createElement=function(a){return this.bb.createElement(a)};Ra.prototype.createTextNode=function(a){return this.bb.createTextNode(String(a))};Ra.prototype.appendChild=function(a,b){a.appendChild(b)};Ra.prototype.append=function(a,b){Pa(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments)};function Sa(a,b){null!=a&&this.append.apply(this,arguments)}Sa.prototype.ra="";Sa.prototype.append=function(a,b,c){this.ra+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.ra+=arguments[d];return this};Sa.prototype.toString=function(){return this.ra};var Ta=null;function Ua(){return new Va(null,5,[Wa,!0,Xa,!0,Ya,!1,Za,!1,$a,null],null)}function t(a){return null!=a&&!1!==a}function ab(a){return t(a)?!1:!0}function v(a,b){return a[n(null==b?null:b)]?!0:a._?!0:w?!1:null}function bb(a){return null==a?null:a.constructor}function x(a,b){var c=bb(b),c=t(t(c)?c.ob:c)?c.nb:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function cb(a){var b=a.nb;return t(b)?b:""+z.c(a)}
function B(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}var db={},eb={};function fb(a){if(a?a.B:a)return a.B(a);var b;b=fb[n(null==a?null:a)];if(!b&&(b=fb._,!b))throw x("ICounted.-count",a);return b.call(null,a)}function gb(a,b){if(a?a.F:a)return a.F(a,b);var c;c=gb[n(null==a?null:a)];if(!c&&(c=gb._,!c))throw x("ICollection.-conj",a);return c.call(null,a,b)}
var hb={},C=function(){function a(a,b,c){if(a?a.N:a)return a.N(a,b,c);var h;h=C[n(null==a?null:a)];if(!h&&(h=C._,!h))throw x("IIndexed.-nth",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.w:a)return a.w(a,b);var c;c=C[n(null==a?null:a)];if(!c&&(c=C._,!c))throw x("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,f){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}(),
ib={};function D(a){if(a?a.O:a)return a.O(a);var b;b=D[n(null==a?null:a)];if(!b&&(b=D._,!b))throw x("ISeq.-first",a);return b.call(null,a)}function E(a){if(a?a.R:a)return a.R(a);var b;b=E[n(null==a?null:a)];if(!b&&(b=E._,!b))throw x("ISeq.-rest",a);return b.call(null,a)}
var jb={},G=function(){function a(a,b,c){if(a?a.J:a)return a.J(a,b,c);var h;h=G[n(null==a?null:a)];if(!h&&(h=G._,!h))throw x("ILookup.-lookup",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.I:a)return a.I(a,b);var c;c=G[n(null==a?null:a)];if(!c&&(c=G._,!c))throw x("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}();
function kb(a,b,c){if(a?a.sa:a)return a.sa(a,b,c);var d;d=kb[n(null==a?null:a)];if(!d&&(d=kb._,!d))throw x("IAssociative.-assoc",a);return d.call(null,a,b,c)}var lb={},mb={};function nb(a){if(a?a.ib:a)return a.ib();var b;b=nb[n(null==a?null:a)];if(!b&&(b=nb._,!b))throw x("IMapEntry.-key",a);return b.call(null,a)}function ob(a){if(a?a.jb:a)return a.jb();var b;b=ob[n(null==a?null:a)];if(!b&&(b=ob._,!b))throw x("IMapEntry.-val",a);return b.call(null,a)}var pb={};
function qb(a,b,c){if(a?a.ab:a)return a.ab(a,b,c);var d;d=qb[n(null==a?null:a)];if(!d&&(d=qb._,!d))throw x("IVector.-assoc-n",a);return d.call(null,a,b,c)}function rb(a){if(a?a.tb:a)return a.state;var b;b=rb[n(null==a?null:a)];if(!b&&(b=rb._,!b))throw x("IDeref.-deref",a);return b.call(null,a)}var sb={};function tb(a){if(a?a.G:a)return a.G(a);var b;b=tb[n(null==a?null:a)];if(!b&&(b=tb._,!b))throw x("IMeta.-meta",a);return b.call(null,a)}
function ub(a,b){if(a?a.H:a)return a.H(a,b);var c;c=ub[n(null==a?null:a)];if(!c&&(c=ub._,!c))throw x("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var vb={},wb=function(){function a(a,b,c){if(a?a.M:a)return a.M(a,b,c);var h;h=wb[n(null==a?null:a)];if(!h&&(h=wb._,!h))throw x("IReduce.-reduce",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.L:a)return a.L(a,b);var c;c=wb[n(null==a?null:a)];if(!c&&(c=wb._,!c))throw x("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}();
function xb(a,b){if(a?a.t:a)return a.t(a,b);var c;c=xb[n(null==a?null:a)];if(!c&&(c=xb._,!c))throw x("IEquiv.-equiv",a);return c.call(null,a,b)}function yb(a){if(a?a.v:a)return a.v(a);var b;b=yb[n(null==a?null:a)];if(!b&&(b=yb._,!b))throw x("IHash.-hash",a);return b.call(null,a)}var zb={};function Ab(a){if(a?a.A:a)return a.A(a);var b;b=Ab[n(null==a?null:a)];if(!b&&(b=Ab._,!b))throw x("ISeqable.-seq",a);return b.call(null,a)}var Bb={};
function H(a,b){if(a?a.mb:a)return a.mb(0,b);var c;c=H[n(null==a?null:a)];if(!c&&(c=H._,!c))throw x("IWriter.-write",a);return c.call(null,a,b)}var Cb={};function Db(a,b,c){if(a?a.u:a)return a.u(a,b,c);var d;d=Db[n(null==a?null:a)];if(!d&&(d=Db._,!d))throw x("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}function Eb(a,b,c){if(a?a.lb:a)return a.lb(0,b,c);var d;d=Eb[n(null==a?null:a)];if(!d&&(d=Eb._,!d))throw x("IWatchable.-notify-watches",a);return d.call(null,a,b,c)}
function Fb(a){if(a?a.Ea:a)return a.Ea(a);var b;b=Fb[n(null==a?null:a)];if(!b&&(b=Fb._,!b))throw x("IEditableCollection.-as-transient",a);return b.call(null,a)}function Gb(a,b){if(a?a.Fa:a)return a.Fa(a,b);var c;c=Gb[n(null==a?null:a)];if(!c&&(c=Gb._,!c))throw x("ITransientCollection.-conj!",a);return c.call(null,a,b)}function Hb(a){if(a?a.Ga:a)return a.Ga(a);var b;b=Hb[n(null==a?null:a)];if(!b&&(b=Hb._,!b))throw x("ITransientCollection.-persistent!",a);return b.call(null,a)}
function Ib(a,b,c){if(a?a.xa:a)return a.xa(a,b,c);var d;d=Ib[n(null==a?null:a)];if(!d&&(d=Ib._,!d))throw x("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function Jb(a,b,c){if(a?a.kb:a)return a.kb(0,b,c);var d;d=Jb[n(null==a?null:a)];if(!d&&(d=Jb._,!d))throw x("ITransientVector.-assoc-n!",a);return d.call(null,a,b,c)}function Kb(a){if(a?a.hb:a)return a.hb();var b;b=Kb[n(null==a?null:a)];if(!b&&(b=Kb._,!b))throw x("IChunk.-drop-first",a);return b.call(null,a)}
function Lb(a){if(a?a.Ma:a)return a.Ma(a);var b;b=Lb[n(null==a?null:a)];if(!b&&(b=Lb._,!b))throw x("IChunkedSeq.-chunked-first",a);return b.call(null,a)}function Mb(a){if(a?a.Na:a)return a.Na(a);var b;b=Mb[n(null==a?null:a)];if(!b&&(b=Mb._,!b))throw x("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function Nb(a){if(a?a.La:a)return a.La(a);var b;b=Nb[n(null==a?null:a)];if(!b&&(b=Nb._,!b))throw x("IChunkedNext.-chunked-next",a);return b.call(null,a)}
function Ob(a){this.Ib=a;this.o=0;this.f=1073741824}Ob.prototype.mb=function(a,b){return this.Ib.append(b)};function Pb(a){var b=new Sa;a.u(null,new Ob(b),Ua());return""+z.c(b)}var Qb="undefined"!==typeof Math.imul?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function Rb(a){a=Qb(a,3432918353);return Qb(a<<15|a>>>-15,461845907)}function Ub(a,b){var c=a^b;return Qb(c<<13|c>>>-13,5)+3864292196}
function Vb(a,b){var c=a^b,c=Qb(c^c>>>16,2246822507),c=Qb(c^c>>>13,3266489909);return c^c>>>16}function Wb(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=Ub(c,Rb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}b=void 0}b=1===(a.length&1)?b^Rb(a.charCodeAt(a.length-1)):b;return Vb(b,Qb(2,a.length))}var Xb={},Yb=0;
function Zb(a){255<Yb&&(Xb={},Yb=0);var b=Xb[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b){for(var c=0,d=0;;)if(c<b)var e=c+1,d=Qb(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}b=void 0}else b=0;else b=0;Xb[a]=b;Yb+=1}return a=b}function $b(a){a&&(a.f&4194304||a.Ob)?a=a.v(null):"number"===typeof a?a=Math.floor(a)%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Zb(a),0!==a&&(a=Rb(a),a=Ub(0,a),a=Vb(a,4))):a=null==a?0:w?yb(a):null;return a}
function ac(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function bc(a,b){if(t(J.a?J.a(a,b):J.call(null,a,b)))return 0;var c=ab(a.Q);if(t(c?b.Q:c))return-1;if(t(a.Q)){if(ab(b.Q))return 1;c=cc.a?cc.a(a.Q,b.Q):cc.call(null,a.Q,b.Q);return 0===c?cc.a?cc.a(a.name,b.name):cc.call(null,a.name,b.name):c}return dc?cc.a?cc.a(a.name,b.name):cc.call(null,a.name,b.name):null}function ec(a,b,c,d,e){this.Q=a;this.name=b;this.ga=c;this.ka=d;this.qa=e;this.f=2154168321;this.o=4096}g=ec.prototype;
g.u=function(a,b){return H(b,this.ga)};g.v=function(){var a=this.ka;return null!=a?a:this.ka=a=ac(Wb(this.name),Zb(this.Q))};g.H=function(a,b){return new ec(this.Q,this.name,this.ga,this.ka,b)};g.G=function(){return this.qa};g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return G.d(c,this,null);case 3:return G.d(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};
g.c=function(a){return G.d(a,this,null)};g.a=function(a,b){return G.d(a,this,b)};g.t=function(a,b){return b instanceof ec?this.ga===b.ga:!1};g.toString=function(){return this.ga};function L(a){if(null==a)return null;if(a&&(a.f&8388608||a.wa))return a.A(null);if(a instanceof Array||"string"===typeof a)return 0===a.length?null:new fc(a,0);if(v(zb,a))return Ab(a);if(w)throw Error(""+z.c(a)+" is not ISeqable");return null}
function M(a){if(null==a)return null;if(a&&(a.f&64||a.va))return a.O(null);a=L(a);return null==a?null:D(a)}function N(a){return null!=a?a&&(a.f&64||a.va)?a.R(null):(a=L(a))?E(a):O:O}function P(a){return null==a?null:a&&(a.f&128||a.Qb)?a.ca(null):L(N(a))}
var J=function(){function a(a,b){return null==a?null==b:a===b||xb(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(b.a(a,d))if(P(e))a=d,d=M(e),e=P(e);else return b.a(d,M(e));else return!1}a.m=2;a.i=function(a){var b=M(a);a=P(a);var d=M(a);a=N(a);return c(b,d,a)};a.g=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,e);
default:return c.g(b,e,Q(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.i=c.i;b.c=function(){return!0};b.a=a;b.g=c.g;return b}();function gc(a,b){var c=Rb(a),c=Ub(0,c);return Vb(c,b)}function hc(a){var b=0,c=1;for(a=L(a);;)if(null!=a)b+=1,c=Qb(31,c)+$b(M(a))|0,a=P(a);else return gc(c,b)}function ic(a){var b=0,c=0;for(a=L(a);;)if(null!=a)b+=1,c=c+$b(M(a))|0,a=P(a);else return gc(c,b)}eb["null"]=!0;fb["null"]=function(){return 0};
Date.prototype.t=function(a,b){return b instanceof Date&&this.toString()===b.toString()};xb.number=function(a,b){return a===b};sb["function"]=!0;tb["function"]=function(){return null};db["function"]=!0;yb._=function(a){return a[fa]||(a[fa]=++ha)};
var jc=function(){function a(a,b,c,d){for(var l=fb(a);;)if(d<l)c=b.a?b.a(c,C.a(a,d)):b.call(null,c,C.a(a,d)),d+=1;else return c}function b(a,b,c){for(var d=fb(a),l=0;;)if(l<d)c=b.a?b.a(c,C.a(a,l)):b.call(null,c,C.a(a,l)),l+=1;else return c}function c(a,b){var c=fb(a);if(0===c)return b.ta?"":b.call(null);for(var d=C.a(a,0),l=1;;)if(l<c)d=b.a?b.a(d,C.a(a,l)):b.call(null,d,C.a(a,l)),l+=1;else return d}var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,
d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.d=b;d.h=a;return d}(),kc=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.a?b.a(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.ta?"":b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.a?b.a(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.d=b;d.h=a;return d}();function lc(a){return a?a.f&2||a.Da?!0:a.f?!1:v(eb,a):v(eb,a)}function mc(a){return a?a.f&16||a.ua?!0:a.f?!1:v(hb,a):v(hb,a)}function fc(a,b){this.b=a;this.j=b;this.f=166199550;this.o=8192}g=fc.prototype;g.toString=function(){return Pb(this)};
g.w=function(a,b){var c=b+this.j;return c<this.b.length?this.b[c]:null};g.N=function(a,b,c){a=b+this.j;return a<this.b.length?this.b[a]:c};g.ca=function(){return this.j+1<this.b.length?new fc(this.b,this.j+1):null};g.B=function(){return this.b.length-this.j};g.v=function(){return hc(this)};g.t=function(a,b){return nc.a?nc.a(this,b):nc.call(null,this,b)};g.L=function(a,b){return kc.h(this.b,b,this.b[this.j],this.j+1)};g.M=function(a,b,c){return kc.h(this.b,b,c,this.j)};g.O=function(){return this.b[this.j]};
g.R=function(){return this.j+1<this.b.length?new fc(this.b,this.j+1):O};g.A=function(){return this};g.F=function(a,b){return T.a?T.a(b,this):T.call(null,b,this)};
var oc=function(){function a(a,b){return b<a.length?new fc(a,b):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}(),Q=function(){function a(a,b){return oc.a(a,b)}function b(a){return oc.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.c=b;c.a=a;return c}();function pc(a){return M(P(a))}xb._=function(a,b){return a===b};
var qc=function(){function a(a,b){return null!=a?gb(a,b):gb(O,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(t(e))a=b.a(a,d),d=M(e),e=P(e);else return b.a(a,d)}a.m=2;a.i=function(a){var b=M(a);a=P(a);var d=M(a);a=N(a);return c(b,d,a)};a.g=c;return a}(),b=function(b,e,f){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.g(b,e,Q(arguments,2))}throw Error("Invalid arity: "+
arguments.length);};b.m=2;b.i=c.i;b.a=a;b.g=c.g;return b}();function U(a){if(null!=a)if(a&&(a.f&2||a.Da))a=a.B(null);else if(a instanceof Array)a=a.length;else if("string"===typeof a)a=a.length;else if(v(eb,a))a=fb(a);else if(w)a:{a=L(a);for(var b=0;;){if(lc(a)){a=b+fb(a);break a}a=P(a);b+=1}a=void 0}else a=null;else a=0;return a}
var rc=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return L(a)?M(a):c;if(mc(a))return C.d(a,b,c);if(L(a))a=P(a),b-=1;else return w?c:null}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(L(a))return M(a);throw Error("Index out of bounds");}if(mc(a))return C.a(a,b);if(L(a)){var c=P(a),h=b-1;a=c;b=h}else{if(w)throw Error("Index out of bounds");return null}}}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}(),sc=function(){function a(a,b,c){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return c;if(a&&(a.f&16||a.ua))return a.N(null,b,c);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:c;if(v(hb,a))return C.a(a,b);if(a?a.f&64||a.va||(a.f?0:v(ib,a)):v(ib,a))return rc.d(a,b,c);if(w)throw Error("nth not supported on this type "+z.c(cb(bb(a))));return null}function b(a,
b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(a&&(a.f&16||a.ua))return a.w(null,b);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:null;if(v(hb,a))return C.a(a,b);if(a?a.f&64||a.va||(a.f?0:v(ib,a)):v(ib,a))return rc.a(a,b);if(w)throw Error("nth not supported on this type "+z.c(cb(bb(a))));return null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+
arguments.length);};c.a=b;c.d=a;return c}(),tc=function(){function a(a,b,c){return null!=a?a&&(a.f&256||a.ub)?a.J(null,b,c):a instanceof Array?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:v(jb,a)?G.d(a,b,c):w?c:null:c}function b(a,b){return null==a?null:a&&(a.f&256||a.ub)?a.I(null,b):a instanceof Array?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:v(jb,a)?G.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}(),vc=function(){function a(a,b,c){return null!=a?kb(a,b,c):uc.a?uc.a([b],[c]):uc.call(null,[b],[c])}var b=null,c=function(){function a(b,d,k,l){var m=null;3<arguments.length&&(m=Q(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,m)}function c(a,d,e,l){for(;;)if(a=b.d(a,d,e),t(l))d=M(l),e=pc(l),l=P(P(l));else return a}a.m=3;a.i=function(a){var b=M(a);a=P(a);var d=M(a);a=P(a);var l=M(a);a=N(a);return c(b,
d,l,a)};a.g=c;return a}(),b=function(b,e,f,h){switch(arguments.length){case 3:return a.call(this,b,e,f);default:return c.g(b,e,f,Q(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.m=3;b.i=c.i;b.d=a;b.g=c.g;return b}();function wc(a){var b="function"==n(a);return b?b:a?t(t(null)?null:a.Lb)?!0:a.Tb?!1:v(db,a):v(db,a)}function yc(a){var b=null!=a;return(b?a?a.f&131072||a.wb||(a.f?0:v(sb,a)):v(sb,a):b)?tb(a):null}function zc(a){return a?a.f&16777216||a.Rb?!0:a.f?!1:v(Bb,a):v(Bb,a)}
function Ac(a){return null==a?!1:a?a.f&1024||a.Pb?!0:a.f?!1:v(lb,a):v(lb,a)}function Bc(a){return a?a.f&16384||a.Sb?!0:a.f?!1:v(pb,a):v(pb,a)}function Cc(a){return a?a.o&512||a.Mb?!0:!1:!1}function Dc(a){var b=[];Na(a,function(a){return function(b,e){return a.push(e)}}(b));return b}function Ec(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}function Fc(a){return t(a)?!0:!1}
function cc(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(bb(a)===bb(b))return a&&(a.o&2048||a.Ba)?a.Ca(null,b):a>b?1:a<b?-1:0;if(w)throw Error("compare on non-nil objects of different types");return null}
var Gc=function(){function a(a,b,c,h){for(;;){var k=cc(sc.a(a,h),sc.a(b,h));if(0===k&&h+1<c)h+=1;else return k}}function b(a,b){var f=U(a),h=U(b);return f<h?-1:f>h?1:w?c.h(a,b,f,0):null}var c=null,c=function(c,e,f,h){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,f,h)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.h=a;return c}(),V=function(){function a(a,b,c){for(c=L(c);;)if(c)b=a.a?a.a(b,M(c)):a.call(null,b,M(c)),c=P(c);else return b}function b(a,
b){var c=L(b);return c?Hc.d?Hc.d(a,M(c),P(c)):Hc.call(null,a,M(c),P(c)):a.ta?"":a.call(null)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}(),Hc=function(){function a(a,b,c){return c&&(c.f&524288||c.yb)?c.M(null,a,b):c instanceof Array?kc.d(c,a,b):"string"===typeof c?kc.d(c,a,b):v(vb,c)?wb.d(c,a,b):w?V.d(a,b,c):null}function b(a,b){return b&&(b.f&524288||b.yb)?
b.L(null,a):b instanceof Array?kc.a(b,a):"string"===typeof b?kc.a(b,a):v(vb,b)?wb.a(b,a):w?V.a(a,b):null}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}();function Ic(a){a=(a-a%2)/2;return 0<=a?Math.floor.c?Math.floor.c(a):Math.floor.call(null,a):Math.ceil.c?Math.ceil.c(a):Math.ceil.call(null,a)}
function Jc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var z=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=Q(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){for(var e=new Sa(b.c(a)),l=d;;)if(t(l))e=e.append(b.c(M(l))),l=P(l);else return e.toString()}a.m=1;a.i=function(a){var b=M(a);a=N(a);return c(b,a)};a.g=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.g(b,Q(arguments,
1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.i=c.i;b.ta=function(){return""};b.c=a;b.g=c.g;return b}();function nc(a,b){return Fc(zc(b)?function(){for(var c=L(a),d=L(b);;){if(null==c)return null==d;if(null==d)return!1;if(J.a(M(c),M(d)))c=P(c),d=P(d);else return w?!1:null}}():null)}function Kc(a,b,c,d,e){this.l=a;this.first=b;this.da=c;this.count=d;this.k=e;this.f=65937646;this.o=8192}g=Kc.prototype;g.toString=function(){return Pb(this)};g.G=function(){return this.l};
g.ca=function(){return 1===this.count?null:this.da};g.B=function(){return this.count};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){return this.first};g.R=function(){return 1===this.count?O:this.da};g.A=function(){return this};g.H=function(a,b){return new Kc(b,this.first,this.da,this.count,this.k)};
g.F=function(a,b){return new Kc(this.l,b,this,this.count+1,null)};function Lc(a){this.l=a;this.f=65937614;this.o=8192}g=Lc.prototype;g.toString=function(){return Pb(this)};g.G=function(){return this.l};g.ca=function(){return null};g.B=function(){return 0};g.v=function(){return 0};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){return null};g.R=function(){return O};g.A=function(){return null};g.H=function(a,b){return new Lc(b)};
g.F=function(a,b){return new Kc(this.l,b,null,1,null)};var O=new Lc(null),Mc=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof fc&&0===a.j)b=a.b;else a:{for(b=[];;)if(null!=a)b.push(a.O(null)),a=a.ca(null);else break a;b=void 0}a=b.length;for(var e=O;;)if(0<a){var f=a-1,e=e.F(null,b[a-1]);a=f}else return e}a.m=0;a.i=function(a){a=L(a);return b(a)};a.g=b;return a}();
function Nc(a,b,c,d){this.l=a;this.first=b;this.da=c;this.k=d;this.f=65929452;this.o=8192}g=Nc.prototype;g.toString=function(){return Pb(this)};g.G=function(){return this.l};g.ca=function(){return null==this.da?null:L(this.da)};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){return this.first};g.R=function(){return null==this.da?O:this.da};g.A=function(){return this};
g.H=function(a,b){return new Nc(b,this.first,this.da,this.k)};g.F=function(a,b){return new Nc(null,b,this,this.k)};function T(a,b){var c=null==b;return(c?c:b&&(b.f&64||b.va))?new Nc(null,a,b,null):new Nc(null,a,L(b),null)}function W(a,b,c,d){this.Q=a;this.name=b;this.fa=c;this.ka=d;this.f=2153775105;this.o=4096}g=W.prototype;g.u=function(a,b){return H(b,":"+z.c(this.fa))};g.v=function(){var a=this.ka;return null!=a?a:this.ka=a=ac(Wb(this.name),Zb(this.Q))+2654435769};
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return tc.a(c,this);case 3:return tc.d(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.c=function(a){return tc.a(a,this)};g.a=function(a,b){return tc.d(a,this,b)};g.t=function(a,b){return b instanceof W?this.fa===b.fa:!1};g.toString=function(){return":"+z.c(this.fa)};
var Pc=function(){function a(a,b){return new W(a,b,""+z.c(t(a)?""+z.c(a)+"/":null)+z.c(b),null)}function b(a){if(a instanceof W)return a;if(a instanceof ec){var b;if(a&&(a.o&4096||a.xb))b=a.Q;else throw Error("Doesn't support namespace: "+z.c(a));return new W(b,Oc.c?Oc.c(a):Oc.call(null,a),a.ga,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new W(b[0],b[1],a,null):new W(null,b[0],a,null)):null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,
c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}();function Qc(a,b,c,d){this.l=a;this.ya=b;this.p=c;this.k=d;this.o=0;this.f=32374988}g=Qc.prototype;g.toString=function(){return Pb(this)};function Rc(a){null!=a.ya&&(a.p=a.ya.ta?"":a.ya.call(null),a.ya=null);return a.p}g.G=function(){return this.l};g.ca=function(){Ab(this);return null==this.p?null:P(this.p)};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};
g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){Ab(this);return null==this.p?null:M(this.p)};g.R=function(){Ab(this);return null!=this.p?N(this.p):O};g.A=function(){Rc(this);if(null==this.p)return null;for(var a=this.p;;)if(a instanceof Qc)a=Rc(a);else return this.p=a,L(this.p)};g.H=function(a,b){return new Qc(b,this.ya,this.p,this.k)};g.F=function(a,b){return T(b,this)};function Sc(a,b){this.Ka=a;this.end=b;this.o=0;this.f=2}Sc.prototype.B=function(){return this.end};
Sc.prototype.add=function(a){this.Ka[this.end]=a;return this.end+=1};Sc.prototype.$=function(){var a=new Tc(this.Ka,0,this.end);this.Ka=null;return a};function Tc(a,b,c){this.b=a;this.q=b;this.end=c;this.o=0;this.f=524306}g=Tc.prototype;g.L=function(a,b){return kc.h(this.b,b,this.b[this.q],this.q+1)};g.M=function(a,b,c){return kc.h(this.b,b,c,this.q)};g.hb=function(){if(this.q===this.end)throw Error("-drop-first of empty chunk");return new Tc(this.b,this.q+1,this.end)};
g.w=function(a,b){return this.b[this.q+b]};g.N=function(a,b,c){return 0<=b&&b<this.end-this.q?this.b[this.q+b]:c};g.B=function(){return this.end-this.q};
var Uc=function(){function a(a,b,c){return new Tc(a,b,c)}function b(a,b){return new Tc(a,b,a.length)}function c(a){return new Tc(a,0,a.length)}var d=null,d=function(d,f,h){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,h)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.a=b;d.d=a;return d}();function Vc(a,b,c,d){this.$=a;this.X=b;this.l=c;this.k=d;this.f=31850732;this.o=1536}g=Vc.prototype;g.toString=function(){return Pb(this)};
g.G=function(){return this.l};g.ca=function(){if(1<fb(this.$))return new Vc(Kb(this.$),this.X,this.l,null);var a=Ab(this.X);return null==a?null:a};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.O=function(){return C.a(this.$,0)};g.R=function(){return 1<fb(this.$)?new Vc(Kb(this.$),this.X,this.l,null):null==this.X?O:this.X};g.A=function(){return this};g.Ma=function(){return this.$};g.Na=function(){return null==this.X?O:this.X};
g.H=function(a,b){return new Vc(this.$,this.X,b,this.k)};g.F=function(a,b){return T(b,this)};g.La=function(){return null==this.X?null:this.X};function Wc(a){for(var b=[];;)if(L(a))b.push(M(a)),a=P(a);else return b}function Xc(a,b){if(lc(a))return U(a);for(var c=a,d=b,e=0;;)if(0<d&&L(c))c=P(c),d-=1,e+=1;else return e}
var $c=function Yc(b){return null==b?null:null==P(b)?L(M(b)):w?T(M(b),Yc(P(b))):null},ad=function(){function a(a,b,c,d){return T(a,T(b,T(c,d)))}function b(a,b,c){return T(a,T(b,c))}var c=null,d=function(){function a(c,d,e,m,p){var q=null;4<arguments.length&&(q=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,m,q)}function b(a,c,d,e,f){return T(a,T(c,T(d,T(e,$c(f)))))}a.m=4;a.i=function(a){var c=M(a);a=P(a);var d=M(a);a=P(a);var e=M(a);a=P(a);var p=M(a);a=N(a);return b(c,d,e,
p,a)};a.g=b;return a}(),c=function(c,f,h,k,l){switch(arguments.length){case 1:return L(c);case 2:return T(c,f);case 3:return b.call(this,c,f,h);case 4:return a.call(this,c,f,h,k);default:return d.g(c,f,h,k,Q(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.m=4;c.i=d.i;c.c=function(a){return L(a)};c.a=function(a,b){return T(a,b)};c.d=b;c.h=a;c.g=d.g;return c}(),bd=function(){var a=null,b=function(){function a(c,f,h,k){var l=null;3<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,
3),0));return b.call(this,c,f,h,l)}function b(a,c,d,k){for(;;)if(a=Ib(a,c,d),t(k))c=M(k),d=pc(k),k=P(P(k));else return a}a.m=3;a.i=function(a){var c=M(a);a=P(a);var h=M(a);a=P(a);var k=M(a);a=N(a);return b(c,h,k,a)};a.g=b;return a}(),a=function(a,d,e,f){switch(arguments.length){case 3:return Ib(a,d,e);default:return b.g(a,d,e,Q(arguments,3))}throw Error("Invalid arity: "+arguments.length);};a.m=3;a.i=b.i;a.d=function(a,b,e){return Ib(a,b,e)};a.g=b.g;return a}();
function cd(a,b,c){var d=L(c);if(0===b)return a.ta?"":a.call(null);c=D(d);var e=E(d);if(1===b)return a.c?a.c(c):a.c?a.c(c):a.call(null,c);var d=D(e),f=E(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=D(f),h=E(f);if(3===b)return a.d?a.d(c,d,e):a.d?a.d(c,d,e):a.call(null,c,d,e);var f=D(h),k=E(h);if(4===b)return a.h?a.h(c,d,e,f):a.h?a.h(c,d,e,f):a.call(null,c,d,e,f);var h=D(k),l=E(k);if(5===b)return a.C?a.C(c,d,e,f,h):a.C?a.C(c,d,e,f,h):a.call(null,c,d,e,f,h);var k=D(l),m=E(l);if(6===
b)return a.ba?a.ba(c,d,e,f,h,k):a.ba?a.ba(c,d,e,f,h,k):a.call(null,c,d,e,f,h,k);var l=D(m),p=E(m);if(7===b)return a.la?a.la(c,d,e,f,h,k,l):a.la?a.la(c,d,e,f,h,k,l):a.call(null,c,d,e,f,h,k,l);var m=D(p),q=E(p);if(8===b)return a.Za?a.Za(c,d,e,f,h,k,l,m):a.Za?a.Za(c,d,e,f,h,k,l,m):a.call(null,c,d,e,f,h,k,l,m);var p=D(q),s=E(q);if(9===b)return a.$a?a.$a(c,d,e,f,h,k,l,m,p):a.$a?a.$a(c,d,e,f,h,k,l,m,p):a.call(null,c,d,e,f,h,k,l,m,p);var q=D(s),u=E(s);if(10===b)return a.Oa?a.Oa(c,d,e,f,h,k,l,m,p,q):a.Oa?
a.Oa(c,d,e,f,h,k,l,m,p,q):a.call(null,c,d,e,f,h,k,l,m,p,q);var s=D(u),A=E(u);if(11===b)return a.Pa?a.Pa(c,d,e,f,h,k,l,m,p,q,s):a.Pa?a.Pa(c,d,e,f,h,k,l,m,p,q,s):a.call(null,c,d,e,f,h,k,l,m,p,q,s);var u=D(A),F=E(A);if(12===b)return a.Qa?a.Qa(c,d,e,f,h,k,l,m,p,q,s,u):a.Qa?a.Qa(c,d,e,f,h,k,l,m,p,q,s,u):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u);var A=D(F),y=E(F);if(13===b)return a.Ra?a.Ra(c,d,e,f,h,k,l,m,p,q,s,u,A):a.Ra?a.Ra(c,d,e,f,h,k,l,m,p,q,s,u,A):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A);var F=D(y),K=E(y);
if(14===b)return a.Sa?a.Sa(c,d,e,f,h,k,l,m,p,q,s,u,A,F):a.Sa?a.Sa(c,d,e,f,h,k,l,m,p,q,s,u,A,F):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F);var y=D(K),R=E(K);if(15===b)return a.Ta?a.Ta(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y):a.Ta?a.Ta(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F,y);var K=D(R),S=E(R);if(16===b)return a.Ua?a.Ua(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K):a.Ua?a.Ua(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K);var R=D(S),ga=E(S);if(17===b)return a.Va?
a.Va(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R):a.Va?a.Va(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R);var S=D(ga),Ha=E(ga);if(18===b)return a.Wa?a.Wa(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S):a.Wa?a.Wa(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S);ga=D(Ha);Ha=E(Ha);if(19===b)return a.Xa?a.Xa(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S,ga):a.Xa?a.Xa(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S,ga):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S,ga);var sa=
D(Ha);E(Ha);if(20===b)return a.Ya?a.Ya(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S,ga,sa):a.Ya?a.Ya(c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S,ga,sa):a.call(null,c,d,e,f,h,k,l,m,p,q,s,u,A,F,y,K,R,S,ga,sa);throw Error("Only up to 20 arguments supported on functions");}
var dd=function(){function a(a,b,c,d,e){b=ad.h(b,c,d,e);c=a.m;return a.i?(d=Xc(b,c+1),d<=c?cd(a,d,b):a.i(b)):a.apply(a,Wc(b))}function b(a,b,c,d){b=ad.d(b,c,d);c=a.m;return a.i?(d=Xc(b,c+1),d<=c?cd(a,d,b):a.i(b)):a.apply(a,Wc(b))}function c(a,b,c){b=ad.a(b,c);c=a.m;if(a.i){var d=Xc(b,c+1);return d<=c?cd(a,d,b):a.i(b)}return a.apply(a,Wc(b))}function d(a,b){var c=a.m;if(a.i){var d=Xc(b,c+1);return d<=c?cd(a,d,b):a.i(b)}return a.apply(a,Wc(b))}var e=null,f=function(){function a(c,d,e,f,h,u){var A=null;
5<arguments.length&&(A=Q(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,f,h,A)}function b(a,c,d,e,f,h){c=T(c,T(d,T(e,T(f,$c(h)))));d=a.m;return a.i?(e=Xc(c,d+1),e<=d?cd(a,e,c):a.i(c)):a.apply(a,Wc(c))}a.m=5;a.i=function(a){var c=M(a);a=P(a);var d=M(a);a=P(a);var e=M(a);a=P(a);var f=M(a);a=P(a);var h=M(a);a=N(a);return b(c,d,e,f,h,a)};a.g=b;return a}(),e=function(e,k,l,m,p,q){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,m);case 5:return a.call(this,e,k,l,m,p);default:return f.g(e,k,l,m,p,Q(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.m=5;e.i=f.i;e.a=d;e.d=c;e.h=b;e.C=a;e.g=f.g;return e}();function ed(a,b){for(;;){if(null==L(b))return!0;if(t(a.c?a.c(M(b)):a.call(null,M(b)))){var c=a,d=P(b);a=c;b=d}else return w?!1:null}}function fd(a){return a}
var gd=function(){function a(a,b,c,e){return new Qc(null,function(){var m=L(b),p=L(c),q=L(e);return m&&p&&q?T(a.d?a.d(M(m),M(p),M(q)):a.call(null,M(m),M(p),M(q)),d.h(a,N(m),N(p),N(q))):null},null,null)}function b(a,b,c){return new Qc(null,function(){var e=L(b),m=L(c);return e&&m?T(a.a?a.a(M(e),M(m)):a.call(null,M(e),M(m)),d.d(a,N(e),N(m))):null},null,null)}function c(a,b){return new Qc(null,function(){var c=L(b);if(c){if(Cc(c)){for(var e=Lb(c),m=U(e),p=new Sc(Array(m),0),q=0;;)if(q<m){var s=a.c?a.c(C.a(e,
q)):a.call(null,C.a(e,q));p.add(s);q+=1}else break;e=p.$();c=d.a(a,Mb(c));return 0===fb(e)?c:new Vc(e,c,null,null)}return T(a.c?a.c(M(c)):a.call(null,M(c)),d.a(a,N(c)))}return null},null,null)}var d=null,e=function(){function a(c,d,e,f,q){var s=null;4<arguments.length&&(s=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,s)}function b(a,c,e,f,h){var s=function A(a){return new Qc(null,function(){var b=d.a(L,a);return ed(fd,b)?T(d.a(M,b),A(d.a(N,b))):null},null,null)};return d.a(function(){return function(b){return dd.a(a,
b)}}(s),s(qc.g(h,f,Q([e,c],0))))}a.m=4;a.i=function(a){var c=M(a);a=P(a);var d=M(a);a=P(a);var e=M(a);a=P(a);var f=M(a);a=N(a);return b(c,d,e,f,a)};a.g=b;return a}(),d=function(d,h,k,l,m){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.g(d,h,k,l,Q(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.i=e.i;d.a=c;d.d=b;d.h=a;d.g=e.g;return d}();
function hd(a){return function c(a,e){return new Qc(null,function(){var f=L(a);return f?T(M(f),c(N(f),e)):L(e)?c(M(e),N(e)):null},null,null)}(null,a)}
var id=function(){function a(a,b){return hd(gd.a(a,b))}var b=null,c=function(){function a(c,d,k){var l=null;2<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,2),0));return b.call(this,c,d,l)}function b(a,c,d){return hd(dd.h(gd,a,c,d))}a.m=2;a.i=function(a){var c=M(a);a=P(a);var d=M(a);a=N(a);return b(c,d,a)};a.g=b;return a}(),b=function(b,e,f){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.g(b,e,Q(arguments,2))}throw Error("Invalid arity: "+arguments.length);
};b.m=2;b.i=c.i;b.a=a;b.g=c.g;return b}();function jd(a,b){this.n=a;this.b=b}function kd(a){return new jd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function ld(a){a=a.e;return 32>a?0:a-1>>>5<<5}function md(a,b,c){for(;;){if(0===b)return c;var d=kd(a);d.b[0]=c;c=d;b-=5}}
var od=function nd(b,c,d,e){var f=new jd(d.n,B(d.b)),h=b.e-1>>>c&31;5===c?f.b[h]=e:(d=d.b[h],b=null!=d?nd(b,c-5,d,e):md(null,c-5,e),f.b[h]=b);return f};function pd(a,b){throw Error("No item "+z.c(a)+" in vector of length "+z.c(b));}function qd(a){var b=a.root;for(a=a.shift;;)if(0<a)a-=5,b=b.b[0];else return b.b}function rd(a,b){if(b>=ld(a))return a.D;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.b[b>>>d&31],d=e;else return c.b}function sd(a,b){return 0<=b&&b<a.e?rd(a,b):pd(b,a.e)}
var ud=function td(b,c,d,e,f){var h=new jd(d.n,B(d.b));if(0===c)h.b[e&31]=f;else{var k=e>>>c&31;b=td(b,c-5,d.b[k],e,f);h.b[k]=b}return h};function X(a,b,c,d,e,f){this.l=a;this.e=b;this.shift=c;this.root=d;this.D=e;this.k=f;this.f=167668511;this.o=8196}g=X.prototype;g.toString=function(){return Pb(this)};g.I=function(a,b){return G.d(this,b,null)};g.J=function(a,b,c){return"number"===typeof b?C.d(this,b,c):c};g.w=function(a,b){return sd(this,b)[b&31]};
g.N=function(a,b,c){return 0<=b&&b<this.e?rd(this,b)[b&31]:c};g.ab=function(a,b,c){if(0<=b&&b<this.e)return ld(this)<=b?(a=B(this.D),a[b&31]=c,new X(this.l,this.e,this.shift,this.root,a,null)):new X(this.l,this.e,this.shift,ud(this,this.shift,this.root,b,c),this.D,null);if(b===this.e)return gb(this,c);if(w)throw Error("Index "+z.c(b)+" out of bounds  [0,"+z.c(this.e)+"]");return null};g.G=function(){return this.l};g.B=function(){return this.e};g.ib=function(){return C.a(this,0)};
g.jb=function(){return C.a(this,1)};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.Ea=function(){return new vd(this.e,this.shift,wd.c?wd.c(this.root):wd.call(null,this.root),xd.c?xd.c(this.D):xd.call(null,this.D))};g.L=function(a,b){return jc.a(this,b)};g.M=function(a,b,c){return jc.d(this,b,c)};g.sa=function(a,b,c){if("number"===typeof b)return qb(this,b,c);throw Error("Vector's key for assoc must be a number.");};
g.A=function(){return 0===this.e?null:32>=this.e?new fc(this.D,0):w?Y.h?Y.h(this,qd(this),0,0):Y.call(null,this,qd(this),0,0):null};g.H=function(a,b){return new X(b,this.e,this.shift,this.root,this.D,this.k)};
g.F=function(a,b){if(32>this.e-ld(this)){for(var c=this.D.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.D[e],e+=1;else break;d[c]=b;return new X(this.l,this.e+1,this.shift,this.root,d,null)}c=(d=this.e>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=kd(null),d.b[0]=this.root,e=md(null,this.shift,new jd(null,this.D)),d.b[1]=e):d=od(this,this.shift,this.root,new jd(null,this.D));return new X(this.l,this.e+1,c,d,[b],null)};
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.w(null,c);case 3:return this.N(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.c=function(a){return this.w(null,a)};g.a=function(a,b){return this.N(null,a,b)};
var Z=new jd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),yd=new X(null,0,5,Z,[],0);function zd(a,b,c,d,e,f){this.r=a;this.T=b;this.j=c;this.q=d;this.l=e;this.k=f;this.f=32243948;this.o=1536}g=zd.prototype;g.toString=function(){return Pb(this)};
g.ca=function(){if(this.q+1<this.T.length){var a=Y.h?Y.h(this.r,this.T,this.j,this.q+1):Y.call(null,this.r,this.T,this.j,this.q+1);return null==a?null:a}return Nb(this)};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return jc.a(Ad.d?Ad.d(this.r,this.j+this.q,U(this.r)):Ad.call(null,this.r,this.j+this.q,U(this.r)),b)};
g.M=function(a,b,c){return jc.d(Ad.d?Ad.d(this.r,this.j+this.q,U(this.r)):Ad.call(null,this.r,this.j+this.q,U(this.r)),b,c)};g.O=function(){return this.T[this.q]};g.R=function(){if(this.q+1<this.T.length){var a=Y.h?Y.h(this.r,this.T,this.j,this.q+1):Y.call(null,this.r,this.T,this.j,this.q+1);return null==a?O:a}return Mb(this)};g.A=function(){return this};g.Ma=function(){return Uc.a(this.T,this.q)};
g.Na=function(){var a=this.j+this.T.length;return a<fb(this.r)?Y.h?Y.h(this.r,rd(this.r,a),a,0):Y.call(null,this.r,rd(this.r,a),a,0):O};g.H=function(a,b){return Y.C?Y.C(this.r,this.T,this.j,this.q,b):Y.call(null,this.r,this.T,this.j,this.q,b)};g.F=function(a,b){return T(b,this)};g.La=function(){var a=this.j+this.T.length;return a<fb(this.r)?Y.h?Y.h(this.r,rd(this.r,a),a,0):Y.call(null,this.r,rd(this.r,a),a,0):null};
var Y=function(){function a(a,b,c,d,l){return new zd(a,b,c,d,l,null)}function b(a,b,c,d){return new zd(a,b,c,d,null,null)}function c(a,b,c){return new zd(a,sd(a,b),b,c,null,null)}var d=null,d=function(d,f,h,k,l){switch(arguments.length){case 3:return c.call(this,d,f,h);case 4:return b.call(this,d,f,h,k);case 5:return a.call(this,d,f,h,k,l)}throw Error("Invalid arity: "+arguments.length);};d.d=c;d.h=b;d.C=a;return d}();
function Bd(a,b,c,d,e){this.l=a;this.Y=b;this.start=c;this.end=d;this.k=e;this.f=166617887;this.o=8192}g=Bd.prototype;g.toString=function(){return Pb(this)};g.I=function(a,b){return G.d(this,b,null)};g.J=function(a,b,c){return"number"===typeof b?C.d(this,b,c):c};g.w=function(a,b){return 0>b||this.end<=this.start+b?pd(b,this.end-this.start):C.a(this.Y,this.start+b)};g.N=function(a,b,c){return 0>b||this.end<=this.start+b?c:C.d(this.Y,this.start+b,c)};
g.ab=function(a,b,c){var d=this,e=d.start+b;return Cd.C?Cd.C(d.l,vc.d(d.Y,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):Cd.call(null,d.l,vc.d(d.Y,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};g.G=function(){return this.l};g.B=function(){return this.end-this.start};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return jc.a(this,b)};g.M=function(a,b,c){return jc.d(this,b,c)};
g.sa=function(a,b,c){if("number"===typeof b)return qb(this,b,c);throw Error("Subvec's key for assoc must be a number.");};g.A=function(){var a=this;return function(b){return function d(e){return e===a.end?null:T(C.a(a.Y,e),new Qc(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};g.H=function(a,b){return Cd.C?Cd.C(b,this.Y,this.start,this.end,this.k):Cd.call(null,b,this.Y,this.start,this.end,this.k)};
g.F=function(a,b){return Cd.C?Cd.C(this.l,qb(this.Y,this.end,b),this.start,this.end+1,null):Cd.call(null,this.l,qb(this.Y,this.end,b),this.start,this.end+1,null)};g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.w(null,c);case 3:return this.N(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.c=function(a){return this.w(null,a)};
g.a=function(a,b){return this.N(null,a,b)};function Cd(a,b,c,d,e){for(;;)if(b instanceof Bd)c=b.start+c,d=b.start+d,b=b.Y;else{var f=U(b);if(0>c||0>d||c>f||d>f)throw Error("Index out of bounds");return new Bd(a,b,c,d,e)}}
var Ad=function(){function a(a,b,c){return Cd(null,a,b,c,null)}function b(a,b){return c.d(a,b,U(a))}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.d=a;return c}();function Dd(a,b){return a===b.n?b:new jd(a,B(b.b))}function wd(a){return new jd({},B(a.b))}
function xd(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Ec(a,0,b,0,a.length);return b}var Fd=function Ed(b,c,d,e){d=Dd(b.root.n,d);var f=b.e-1>>>c&31;if(5===c)b=e;else{var h=d.b[f];b=null!=h?Ed(b,c-5,h,e):md(b.root.n,c-5,e)}d.b[f]=b;return d};function vd(a,b,c,d){this.e=a;this.shift=b;this.root=c;this.D=d;this.f=275;this.o=88}g=vd.prototype;
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.I(null,c);case 3:return this.J(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.c=function(a){return this.I(null,a)};g.a=function(a,b){return this.J(null,a,b)};g.I=function(a,b){return G.d(this,b,null)};g.J=function(a,b,c){return"number"===typeof b?C.d(this,b,c):c};
g.w=function(a,b){if(this.root.n)return sd(this,b)[b&31];throw Error("nth after persistent!");};g.N=function(a,b,c){return 0<=b&&b<this.e?C.a(this,b):c};g.B=function(){if(this.root.n)return this.e;throw Error("count after persistent!");};
g.kb=function(a,b,c){var d=this;if(d.root.n){if(0<=b&&b<d.e)return ld(this)<=b?d.D[b&31]=c:(a=function(){return function f(a,k){var l=Dd(d.root.n,k);if(0===a)l.b[b&31]=c;else{var m=b>>>a&31,p=f(a-5,l.b[m]);l.b[m]=p}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.e)return Gb(this,c);if(w)throw Error("Index "+z.c(b)+" out of bounds for TransientVector of length"+z.c(d.e));return null}throw Error("assoc! after persistent!");};
g.xa=function(a,b,c){if("number"===typeof b)return Jb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
g.Fa=function(a,b){if(this.root.n){if(32>this.e-ld(this))this.D[this.e&31]=b;else{var c=new jd(this.root.n,this.D),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.D=d;if(this.e>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=md(this.root.n,this.shift,c);this.root=new jd(this.root.n,d);this.shift=e}else this.root=Fd(this,this.shift,this.root,c)}this.e+=1;return this}throw Error("conj! after persistent!");};g.Ga=function(){if(this.root.n){this.root.n=null;var a=this.e-ld(this),b=Array(a);Ec(this.D,0,b,0,a);return new X(null,this.e,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function Gd(){this.o=0;this.f=2097152}Gd.prototype.t=function(){return!1};var Hd=new Gd;
function Id(a,b){return Fc(Ac(b)?U(a)===U(b)?ed(fd,gd.a(function(a){return J.a(tc.d(b,M(a),Hd),pc(a))},a)):null:null)}
function Jd(a,b){var c=a.b;if(b instanceof W)a:{for(var d=c.length,e=b.fa,f=0;;){if(d<=f){c=-1;break a}var h=c[f];if(h instanceof W&&e===h.fa){c=f;break a}if(w)f+=2;else{c=null;break a}}c=void 0}else if(da(b)||"number"===typeof b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(b===c[e]){c=e;break a}if(w)e+=2;else{c=null;break a}}c=void 0}else if(b instanceof ec)a:{d=c.length;e=b.ga;for(f=0;;){if(d<=f){c=-1;break a}h=c[f];if(h instanceof ec&&e===h.ga){c=f;break a}if(w)f+=2;else{c=null;break a}}c=
void 0}else if(null==b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(null==c[e]){c=e;break a}if(w)e+=2;else{c=null;break a}}c=void 0}else if(w)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(J.a(b,c[e])){c=e;break a}if(w)e+=2;else{c=null;break a}}c=void 0}else c=null;return c}function Kd(a,b,c){this.b=a;this.j=b;this.qa=c;this.o=0;this.f=32374990}g=Kd.prototype;g.toString=function(){return Pb(this)};g.G=function(){return this.qa};
g.ca=function(){return this.j<this.b.length-2?new Kd(this.b,this.j+2,this.qa):null};g.B=function(){return(this.b.length-this.j)/2};g.v=function(){return hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){return new X(null,2,5,Z,[this.b[this.j],this.b[this.j+1]],null)};g.R=function(){return this.j<this.b.length-2?new Kd(this.b,this.j+2,this.qa):O};g.A=function(){return this};
g.H=function(a,b){return new Kd(this.b,this.j,b)};g.F=function(a,b){return T(b,this)};function Va(a,b,c,d){this.l=a;this.e=b;this.b=c;this.k=d;this.f=16647951;this.o=8196}g=Va.prototype;g.toString=function(){return Pb(this)};g.I=function(a,b){return G.d(this,b,null)};g.J=function(a,b,c){a=Jd(this,b);return-1===a?c:this.b[a+1]};g.G=function(){return this.l};g.B=function(){return this.e};g.v=function(){var a=this.k;return null!=a?a:this.k=a=ic(this)};g.t=function(a,b){return Id(this,b)};
g.Ea=function(){return new Ld({},this.b.length,B(this.b))};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};
g.sa=function(a,b,c){a=Jd(this,b);if(-1===a){if(this.e<Md){a=this.b;for(var d=a.length,e=Array(d+2),f=0;;)if(f<d)e[f]=a[f],f+=1;else break;e[d]=b;e[d+1]=c;return new Va(this.l,this.e+1,e,null)}a=ub;d=kb;e=Nd;null!=e?e&&(e.o&4||e.Nb)?(e=Hc.d(Gb,Fb(e),this),e=Hb(e)):e=Hc.d(gb,e,this):e=Hc.d(qc,O,this);return a(d(e,b,c),this.l)}return c===this.b[a+1]?this:w?(b=B(this.b),b[a+1]=c,new Va(this.l,this.e,b,null)):null};g.A=function(){var a=this.b;return 0<=a.length-2?new Kd(a,0,null):null};
g.H=function(a,b){return new Va(b,this.e,this.b,this.k)};g.F=function(a,b){if(Bc(b))return kb(this,C.a(b,0),C.a(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=M(d);if(Bc(e))c=kb(c,C.a(e,0),C.a(e,1)),d=P(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.I(null,c);case 3:return this.J(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.c=function(a){return this.I(null,a)};g.a=function(a,b){return this.J(null,a,b)};var Od=new Va(null,0,[],null),Md=8;function Ld(a,b,c){this.ma=a;this.ia=b;this.b=c;this.o=56;this.f=258}g=Ld.prototype;
g.xa=function(a,b,c){if(t(this.ma)){a=Jd(this,b);if(-1===a)return this.ia+2<=2*Md?(this.ia+=2,this.b.push(b),this.b.push(c),this):bd.d(Pd.a?Pd.a(this.ia,this.b):Pd.call(null,this.ia,this.b),b,c);c!==this.b[a+1]&&(this.b[a+1]=c);return this}throw Error("assoc! after persistent!");};
g.Fa=function(a,b){if(t(this.ma)){if(b?b.f&2048||b.vb||(b.f?0:v(mb,b)):v(mb,b))return Ib(this,Qd.c?Qd.c(b):Qd.call(null,b),Rd.c?Rd.c(b):Rd.call(null,b));for(var c=L(b),d=this;;){var e=M(c);if(t(e))c=P(c),d=Ib(d,Qd.c?Qd.c(e):Qd.call(null,e),Rd.c?Rd.c(e):Rd.call(null,e));else return d}}else throw Error("conj! after persistent!");};g.Ga=function(){if(t(this.ma))return this.ma=!1,new Va(null,Ic(this.ia),this.b,null);throw Error("persistent! called twice");};g.I=function(a,b){return G.d(this,b,null)};
g.J=function(a,b,c){if(t(this.ma))return a=Jd(this,b),-1===a?c:this.b[a+1];throw Error("lookup after persistent!");};g.B=function(){if(t(this.ma))return Ic(this.ia);throw Error("count after persistent!");};function Pd(a,b){for(var c=Fb(Nd),d=0;;)if(d<a)c=bd.d(c,b[d],b[d+1]),d+=2;else return c}function Sd(){this.Z=!1}function Td(a,b){return a===b?!0:a===b||a instanceof W&&b instanceof W&&a.fa===b.fa?!0:w?J.a(a,b):null}
var Ud=function(){function a(a,b,c,h,k){a=B(a);a[b]=c;a[h]=k;return a}function b(a,b,c){a=B(a);a[b]=c;return a}var c=null,c=function(c,e,f,h,k){switch(arguments.length){case 3:return b.call(this,c,e,f);case 5:return a.call(this,c,e,f,h,k)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.C=a;return c}(),Vd=function(){function a(a,b,c,h,k,l){a=a.oa(b);a.b[c]=h;a.b[k]=l;return a}function b(a,b,c,h){a=a.oa(b);a.b[c]=h;return a}var c=null,c=function(c,e,f,h,k,l){switch(arguments.length){case 4:return b.call(this,
c,e,f,h);case 6:return a.call(this,c,e,f,h,k,l)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.ba=a;return c}();function Wd(a,b,c){this.n=a;this.s=b;this.b=c}g=Wd.prototype;g.oa=function(a){if(a===this.n)return this;var b=Jc(this.s),c=Array(0>b?4:2*(b+1));Ec(this.b,0,c,0,2*b);return new Wd(a,this.s,c)};g.za=function(){return Xd.c?Xd.c(this.b):Xd.call(null,this.b)};
g.ha=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.s&e))return d;var f=Jc(this.s&e-1),e=this.b[2*f],f=this.b[2*f+1];return null==e?f.ha(a+5,b,c,d):Td(c,e)?f:w?d:null};
g.V=function(a,b,c,d,e,f){var h=1<<(c>>>b&31),k=Jc(this.s&h-1);if(0===(this.s&h)){var l=Jc(this.s);if(2*l<this.b.length){a=this.oa(a);b=a.b;f.Z=!0;a:for(c=2*(l-k),f=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[f];l-=1;c-=1;f-=1}b[2*k]=d;b[2*k+1]=e;a.s|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Yd.V(a,b+5,c,d,e,f);for(e=d=0;;)if(32>d)0!==
(this.s>>>d&1)&&(k[d]=null!=this.b[e]?Yd.V(a,b+5,$b(this.b[e]),this.b[e],this.b[e+1],f):this.b[e+1],e+=2),d+=1;else break;return new Zd(a,l+1,k)}return w?(b=Array(2*(l+4)),Ec(this.b,0,b,0,2*k),b[2*k]=d,b[2*k+1]=e,Ec(this.b,2*k,b,2*(k+1),2*(l-k)),f.Z=!0,a=this.oa(a),a.b=b,a.s|=h,a):null}l=this.b[2*k];h=this.b[2*k+1];return null==l?(l=h.V(a,b+5,c,d,e,f),l===h?this:Vd.h(this,a,2*k+1,l)):Td(d,l)?e===h?this:Vd.h(this,a,2*k+1,e):w?(f.Z=!0,Vd.ba(this,a,2*k,null,2*k+1,$d.la?$d.la(a,b+5,l,h,c,d,e):$d.call(null,
a,b+5,l,h,c,d,e))):null};
g.U=function(a,b,c,d,e){var f=1<<(b>>>a&31),h=Jc(this.s&f-1);if(0===(this.s&f)){var k=Jc(this.s);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Yd.U(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.s>>>c&1)&&(h[c]=null!=this.b[d]?Yd.U(a+5,$b(this.b[d]),this.b[d],this.b[d+1],e):this.b[d+1],d+=2),c+=1;else break;return new Zd(null,k+1,h)}a=Array(2*(k+1));Ec(this.b,0,a,
0,2*h);a[2*h]=c;a[2*h+1]=d;Ec(this.b,2*h,a,2*(h+1),2*(k-h));e.Z=!0;return new Wd(null,this.s|f,a)}k=this.b[2*h];f=this.b[2*h+1];return null==k?(k=f.U(a+5,b,c,d,e),k===f?this:new Wd(null,this.s,Ud.d(this.b,2*h+1,k))):Td(c,k)?d===f?this:new Wd(null,this.s,Ud.d(this.b,2*h+1,d)):w?(e.Z=!0,new Wd(null,this.s,Ud.C(this.b,2*h,null,2*h+1,$d.ba?$d.ba(a+5,k,f,b,c,d):$d.call(null,a+5,k,f,b,c,d)))):null};var Yd=new Wd(null,0,[]);function Zd(a,b,c){this.n=a;this.e=b;this.b=c}g=Zd.prototype;
g.oa=function(a){return a===this.n?this:new Zd(a,this.e,B(this.b))};g.za=function(){return ae.c?ae.c(this.b):ae.call(null,this.b)};g.ha=function(a,b,c,d){var e=this.b[b>>>a&31];return null!=e?e.ha(a+5,b,c,d):d};g.V=function(a,b,c,d,e,f){var h=c>>>b&31,k=this.b[h];if(null==k)return a=Vd.h(this,a,h,Yd.V(a,b+5,c,d,e,f)),a.e+=1,a;b=k.V(a,b+5,c,d,e,f);return b===k?this:Vd.h(this,a,h,b)};
g.U=function(a,b,c,d,e){var f=b>>>a&31,h=this.b[f];if(null==h)return new Zd(null,this.e+1,Ud.d(this.b,f,Yd.U(a+5,b,c,d,e)));a=h.U(a+5,b,c,d,e);return a===h?this:new Zd(null,this.e,Ud.d(this.b,f,a))};function be(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Td(c,a[d]))return d;d+=2}else return-1}function ce(a,b,c,d){this.n=a;this.ea=b;this.e=c;this.b=d}g=ce.prototype;g.oa=function(a){if(a===this.n)return this;var b=Array(2*(this.e+1));Ec(this.b,0,b,0,2*this.e);return new ce(a,this.ea,this.e,b)};
g.za=function(){return Xd.c?Xd.c(this.b):Xd.call(null,this.b)};g.ha=function(a,b,c,d){a=be(this.b,this.e,c);return 0>a?d:Td(c,this.b[a])?this.b[a+1]:w?d:null};
g.V=function(a,b,c,d,e,f){if(c===this.ea){b=be(this.b,this.e,d);if(-1===b){if(this.b.length>2*this.e)return a=Vd.ba(this,a,2*this.e,d,2*this.e+1,e),f.Z=!0,a.e+=1,a;c=this.b.length;b=Array(c+2);Ec(this.b,0,b,0,c);b[c]=d;b[c+1]=e;f.Z=!0;f=this.e+1;a===this.n?(this.b=b,this.e=f,a=this):a=new ce(this.n,this.ea,f,b);return a}return this.b[b+1]===e?this:Vd.h(this,a,b+1,e)}return(new Wd(a,1<<(this.ea>>>b&31),[null,this,null,null])).V(a,b,c,d,e,f)};
g.U=function(a,b,c,d,e){return b===this.ea?(a=be(this.b,this.e,c),-1===a?(a=2*this.e,b=Array(a+2),Ec(this.b,0,b,0,a),b[a]=c,b[a+1]=d,e.Z=!0,new ce(null,this.ea,this.e+1,b)):J.a(this.b[a],d)?this:new ce(null,this.ea,this.e,Ud.d(this.b,a+1,d))):(new Wd(null,1<<(this.ea>>>a&31),[null,this])).U(a,b,c,d,e)};
var $d=function(){function a(a,b,c,h,k,l,m){var p=$b(c);if(p===k)return new ce(null,p,2,[c,h,l,m]);var q=new Sd;return Yd.V(a,b,p,c,h,q).V(a,b,k,l,m,q)}function b(a,b,c,h,k,l){var m=$b(b);if(m===h)return new ce(null,m,2,[b,c,k,l]);var p=new Sd;return Yd.U(a,m,b,c,p).U(a,h,k,l,p)}var c=null,c=function(c,e,f,h,k,l,m){switch(arguments.length){case 6:return b.call(this,c,e,f,h,k,l);case 7:return a.call(this,c,e,f,h,k,l,m)}throw Error("Invalid arity: "+arguments.length);};c.ba=b;c.la=a;return c}();
function de(a,b,c,d,e){this.l=a;this.W=b;this.j=c;this.p=d;this.k=e;this.o=0;this.f=32374860}g=de.prototype;g.toString=function(){return Pb(this)};g.G=function(){return this.l};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){return null==this.p?new X(null,2,5,Z,[this.W[this.j],this.W[this.j+1]],null):M(this.p)};
g.R=function(){return null==this.p?Xd.d?Xd.d(this.W,this.j+2,null):Xd.call(null,this.W,this.j+2,null):Xd.d?Xd.d(this.W,this.j,P(this.p)):Xd.call(null,this.W,this.j,P(this.p))};g.A=function(){return this};g.H=function(a,b){return new de(b,this.W,this.j,this.p,this.k)};g.F=function(a,b){return T(b,this)};
var Xd=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new de(null,a,b,null,null);var h=a[b+1];if(t(h)&&(h=h.za(),t(h)))return new de(null,a,b+2,h,null);b+=2}else return null;else return new de(null,a,b,c,null)}function b(a){return c.d(a,0,null)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.d=a;return c}();
function ee(a,b,c,d,e){this.l=a;this.W=b;this.j=c;this.p=d;this.k=e;this.o=0;this.f=32374860}g=ee.prototype;g.toString=function(){return Pb(this)};g.G=function(){return this.l};g.v=function(){var a=this.k;return null!=a?a:this.k=a=hc(this)};g.t=function(a,b){return nc(this,b)};g.L=function(a,b){return V.a(b,this)};g.M=function(a,b,c){return V.d(b,c,this)};g.O=function(){return M(this.p)};g.R=function(){return ae.h?ae.h(null,this.W,this.j,P(this.p)):ae.call(null,null,this.W,this.j,P(this.p))};
g.A=function(){return this};g.H=function(a,b){return new ee(b,this.W,this.j,this.p,this.k)};g.F=function(a,b){return T(b,this)};
var ae=function(){function a(a,b,c,h){if(null==h)for(h=b.length;;)if(c<h){var k=b[c];if(t(k)&&(k=k.za(),t(k)))return new ee(a,b,c+1,k,null);c+=1}else return null;else return new ee(a,b,c,h,null)}function b(a){return c.h(null,a,0,null)}var c=null,c=function(c,e,f,h){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,f,h)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.h=a;return c}();
function fe(a,b,c,d,e,f){this.l=a;this.e=b;this.root=c;this.P=d;this.S=e;this.k=f;this.f=16123663;this.o=8196}g=fe.prototype;g.toString=function(){return Pb(this)};g.I=function(a,b){return G.d(this,b,null)};g.J=function(a,b,c){return null==b?this.P?this.S:c:null==this.root?c:w?this.root.ha(0,$b(b),b,c):null};g.G=function(){return this.l};g.B=function(){return this.e};g.v=function(){var a=this.k;return null!=a?a:this.k=a=ic(this)};g.t=function(a,b){return Id(this,b)};
g.Ea=function(){return new ge({},this.root,this.e,this.P,this.S)};g.sa=function(a,b,c){if(null==b)return this.P&&c===this.S?this:new fe(this.l,this.P?this.e:this.e+1,this.root,!0,c,null);a=new Sd;b=(null==this.root?Yd:this.root).U(0,$b(b),b,c,a);return b===this.root?this:new fe(this.l,a.Z?this.e+1:this.e,b,this.P,this.S,null)};g.A=function(){if(0<this.e){var a=null!=this.root?this.root.za():null;return this.P?T(new X(null,2,5,Z,[null,this.S],null),a):a}return null};
g.H=function(a,b){return new fe(b,this.e,this.root,this.P,this.S,this.k)};g.F=function(a,b){if(Bc(b))return kb(this,C.a(b,0),C.a(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=M(d);if(Bc(e))c=kb(c,C.a(e,0),C.a(e,1)),d=P(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
g.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.I(null,c);case 3:return this.J(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.c=function(a){return this.I(null,a)};g.a=function(a,b){return this.J(null,a,b)};var Nd=new fe(null,0,null,!1,null,0);function uc(a,b){for(var c=a.length,d=0,e=Fb(Nd);;)if(d<c)var f=d+1,e=e.xa(null,a[d],b[d]),d=f;else return Hb(e)}
function ge(a,b,c,d,e){this.n=a;this.root=b;this.count=c;this.P=d;this.S=e;this.o=56;this.f=258}g=ge.prototype;g.xa=function(a,b,c){return he(this,b,c)};g.Fa=function(a,b){var c;a:{if(this.n){if(b?b.f&2048||b.vb||(b.f?0:v(mb,b)):v(mb,b)){c=he(this,Qd.c?Qd.c(b):Qd.call(null,b),Rd.c?Rd.c(b):Rd.call(null,b));break a}c=L(b);for(var d=this;;){var e=M(c);if(t(e))c=P(c),d=he(d,Qd.c?Qd.c(e):Qd.call(null,e),Rd.c?Rd.c(e):Rd.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
g.Ga=function(){var a;if(this.n)this.n=null,a=new fe(null,this.count,this.root,this.P,this.S,null);else throw Error("persistent! called twice");return a};g.I=function(a,b){return null==b?this.P?this.S:null:null==this.root?null:this.root.ha(0,$b(b),b)};g.J=function(a,b,c){return null==b?this.P?this.S:c:null==this.root?c:this.root.ha(0,$b(b),b,c)};g.B=function(){if(this.n)return this.count;throw Error("count after persistent!");};
function he(a,b,c){if(a.n){if(null==b)a.S!==c&&(a.S=c),a.P||(a.count+=1,a.P=!0);else{var d=new Sd;b=(null==a.root?Yd:a.root).V(a.n,0,$b(b),b,c,d);b!==a.root&&(a.root=b);d.Z&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var ie=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){a=L(a);for(var b=Fb(Nd);;)if(a){var e=P(P(a)),b=bd.d(b,M(a),pc(a));a=e}else return Hb(b)}a.m=0;a.i=function(a){a=L(a);return b(a)};a.g=b;return a}();function Qd(a){return nb(a)}function Rd(a){return ob(a)}function Oc(a){if(a&&(a.o&4096||a.xb))return a.name;if("string"===typeof a)return a;throw Error("Doesn't support name: "+z.c(a));}
var je=function(){function a(a,b){for(;;)if(L(b)&&0<a){var c=a-1,h=P(b);a=c;b=h}else return null}function b(a){for(;;)if(L(a))a=P(a);else return null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}(),ke=function(){function a(a,b){je.a(a,b);return b}function b(a){je.c(a);return a}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,
c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}();function re(a,b){var c=a.exec(b);return null==c?null:1===U(c)?M(c):Hb(Hc.d(Gb,Fb(yd),c))}
function se(a,b,c,d,e,f,h){var k=Ta;try{Ta=null==Ta?null:Ta-1;if(null!=Ta&&0>Ta)return H(a,"#");H(a,c);L(h)&&(b.d?b.d(M(h),a,f):b.call(null,M(h),a,f));for(var l=P(h),m=$a.c(f)-1;;)if(!l||null!=m&&0===m){L(l)&&0===m&&(H(a,d),H(a,"..."));break}else{H(a,d);b.d?b.d(M(l),a,f):b.call(null,M(l),a,f);var p=P(l);c=m-1;l=p;m=c}return H(a,e)}finally{Ta=k}}
var te=function(){function a(a,d){var e=null;1<arguments.length&&(e=Q(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=L(b),f=null,h=0,k=0;;)if(k<h){var l=f.w(null,k);H(a,l);k+=1}else if(e=L(e))f=e,Cc(f)?(e=Lb(f),h=Mb(f),f=e,l=U(e),e=h,h=l):(l=M(f),H(a,l),e=P(f),f=null,h=0),k=0;else return null}a.m=1;a.i=function(a){var d=M(a);a=N(a);return b(d,a)};a.g=b;return a}(),ue={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};
function ve(a){return'"'+z.c(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return ue[a]}))+'"'}
var $=function we(b,c,d){if(null==b)return H(c,"nil");if(void 0===b)return H(c,"#\x3cundefined\x3e");if(w){t(function(){var c=tc.a(d,Ya);return t(c)?(c=b?b.f&131072||b.wb?!0:b.f?!1:v(sb,b):v(sb,b))?yc(b):c:c}())&&(H(c,"^"),we(yc(b),c,d),H(c," "));if(null==b)return H(c,"nil");if(b.ob)return b.Eb(c);if(b&&(b.f&2147483648||b.K))return b.u(null,c,d);if(bb(b)===Boolean||"number"===typeof b)return H(c,""+z.c(b));if(null!=b&&b.constructor===Object)return H(c,"#js "),xe.h?xe.h(gd.a(function(c){return new X(null,
2,5,Z,[Pc.c(c),b[c]],null)},Dc(b)),we,c,d):xe.call(null,gd.a(function(c){return new X(null,2,5,Z,[Pc.c(c),b[c]],null)},Dc(b)),we,c,d);if(b instanceof Array)return se(c,we,"#js ["," ","]",d,b);if(da(b))return t(Xa.c(d))?H(c,ve(b)):H(c,b);if(wc(b))return te.g(c,Q(["#\x3c",""+z.c(b),"\x3e"],0));if(b instanceof Date){var e=function(b,c){for(var d=""+z.c(b);;)if(U(d)<c)d="0"+z.c(d);else return d};return te.g(c,Q(['#inst "',""+z.c(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",e(b.getUTCDate(),2),"T",
e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))}return b instanceof RegExp?te.g(c,Q(['#"',b.source,'"'],0)):(b?b.f&2147483648||b.K||(b.f?0:v(Cb,b)):v(Cb,b))?Db(b,c,d):w?te.g(c,Q(["#\x3c",""+z.c(b),"\x3e"],0)):null}return null};
function ye(a,b){var c=new Sa;a:{var d=new Ob(c);$(M(a),d,b);for(var e=L(P(a)),f=null,h=0,k=0;;)if(k<h){var l=f.w(null,k);H(d," ");$(l,d,b);k+=1}else if(e=L(e))f=e,Cc(f)?(e=Lb(f),h=Mb(f),f=e,l=U(e),e=h,h=l):(l=M(f),H(d," "),$(l,d,b),e=P(f),f=null,h=0),k=0;else break a}return c}
var ze=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b=Ua();return null==a||ab(L(a))?"":""+z.c(ye(a,b))}a.m=0;a.i=function(a){a=L(a);return b(a)};a.g=b;return a}();function xe(a,b,c,d){return se(c,function(a,c,d){b.d?b.d(nb(a),c,d):b.call(null,nb(a),c,d);H(c," ");return b.d?b.d(ob(a),c,d):b.call(null,ob(a),c,d)},"{",", ","}",d,L(a))}fc.prototype.K=!0;
fc.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};Qc.prototype.K=!0;Qc.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};de.prototype.K=!0;de.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};Kd.prototype.K=!0;Kd.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};zd.prototype.K=!0;zd.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};Nc.prototype.K=!0;Nc.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};
fe.prototype.K=!0;fe.prototype.u=function(a,b,c){return xe(this,$,b,c)};ee.prototype.K=!0;ee.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};Bd.prototype.K=!0;Bd.prototype.u=function(a,b,c){return se(b,$,"["," ","]",c,this)};Vc.prototype.K=!0;Vc.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};X.prototype.K=!0;X.prototype.u=function(a,b,c){return se(b,$,"["," ","]",c,this)};Lc.prototype.K=!0;Lc.prototype.u=function(a,b){return H(b,"()")};Va.prototype.K=!0;
Va.prototype.u=function(a,b,c){return xe(this,$,b,c)};Kc.prototype.K=!0;Kc.prototype.u=function(a,b,c){return se(b,$,"("," ",")",c,this)};X.prototype.Ba=!0;X.prototype.Ca=function(a,b){return Gc.a(this,b)};Bd.prototype.Ba=!0;Bd.prototype.Ca=function(a,b){return Gc.a(this,b)};W.prototype.Ba=!0;W.prototype.Ca=function(a,b){return bc(this,b)};ec.prototype.Ba=!0;ec.prototype.Ca=function(a,b){return bc(this,b)};
function Ae(a,b){if(a?a.zb:a)return a.zb(a,b);var c;c=Ae[n(null==a?null:a)];if(!c&&(c=Ae._,!c))throw x("IReset.-reset!",a);return c.call(null,a,b)}
var Be=function(){function a(a,b,c,d,e){if(a?a.Db:a)return a.Db(a,b,c,d,e);var p;p=Be[n(null==a?null:a)];if(!p&&(p=Be._,!p))throw x("ISwap.-swap!",a);return p.call(null,a,b,c,d,e)}function b(a,b,c,d){if(a?a.Cb:a)return a.Cb(a,b,c,d);var e;e=Be[n(null==a?null:a)];if(!e&&(e=Be._,!e))throw x("ISwap.-swap!",a);return e.call(null,a,b,c,d)}function c(a,b,c){if(a?a.Bb:a)return a.Bb(a,b,c);var d;d=Be[n(null==a?null:a)];if(!d&&(d=Be._,!d))throw x("ISwap.-swap!",a);return d.call(null,a,b,c)}function d(a,b){if(a?
a.Ab:a)return a.Ab(a,b);var c;c=Be[n(null==a?null:a)];if(!c&&(c=Be._,!c))throw x("ISwap.-swap!",a);return c.call(null,a,b)}var e=null,e=function(e,h,k,l,m){switch(arguments.length){case 2:return d.call(this,e,h);case 3:return c.call(this,e,h,k);case 4:return b.call(this,e,h,k,l);case 5:return a.call(this,e,h,k,l,m)}throw Error("Invalid arity: "+arguments.length);};e.a=d;e.d=c;e.h=b;e.C=a;return e}();function Ce(a,b,c,d){this.state=a;this.l=b;this.Kb=c;this.sb=d;this.f=2153938944;this.o=16386}g=Ce.prototype;
g.v=function(){return this[fa]||(this[fa]=++ha)};g.lb=function(a,b,c){a=L(this.sb);for(var d=null,e=0,f=0;;)if(f<e){var h=d.w(null,f),k=sc.d(h,0,null),h=sc.d(h,1,null);h.h?h.h(k,this,b,c):h.call(null,k,this,b,c);f+=1}else if(a=L(a))Cc(a)?(d=Lb(a),a=Mb(a),k=d,e=U(d),d=k):(d=M(a),k=sc.d(d,0,null),h=sc.d(d,1,null),h.h?h.h(k,this,b,c):h.call(null,k,this,b,c),a=P(a),d=null,e=0),f=0;else return null};g.u=function(a,b,c){H(b,"#\x3cAtom: ");$(this.state,b,c);return H(b,"\x3e")};g.G=function(){return this.l};
g.tb=function(){return this.state};g.t=function(a,b){return this===b};
var Ee=function(){function a(a){return new Ce(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=Q(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d=(null==c?0:c?c.f&64||c.va||(c.f?0:v(ib,c)):v(ib,c))?dd.a(ie,c):c,e=tc.a(d,De),d=tc.a(d,Ya);return new Ce(a,d,e,null)}a.m=1;a.i=function(a){var c=M(a);a=N(a);return b(c,a)};a.g=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,b);default:return c.g(b,
Q(arguments,1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.i=c.i;b.c=a;b.g=c.g;return b}();function Fe(a,b){if(a instanceof Ce){var c=a.Kb;if(null!=c&&!t(c.c?c.c(b):c.call(null,b)))throw Error("Assert failed: Validator rejected reference state\n"+z.c(ze.g(Q([Mc(new ec(null,"validate","validate",1439230700,null),new ec(null,"new-value","new-value",-1567397401,null))],0))));c=a.state;a.state=b;null!=a.sb&&Eb(a,c,b);return b}return Ae(a,b)}
var Ge=function(){function a(a,b,c,d){return a instanceof Ce?Fe(a,b.d?b.d(a.state,c,d):b.call(null,a.state,c,d)):Be.h(a,b,c,d)}function b(a,b,c){return a instanceof Ce?Fe(a,b.a?b.a(a.state,c):b.call(null,a.state,c)):Be.d(a,b,c)}function c(a,b){return a instanceof Ce?Fe(a,b.c?b.c(a.state):b.call(null,a.state)):Be.a(a,b)}var d=null,e=function(){function a(c,d,e,f,q){var s=null;4<arguments.length&&(s=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,s)}function b(a,c,d,e,f){return a instanceof
Ce?Fe(a,dd.C(c,a.state,d,e,f)):Be.C(a,c,d,e,f)}a.m=4;a.i=function(a){var c=M(a);a=P(a);var d=M(a);a=P(a);var e=M(a);a=P(a);var f=M(a);a=N(a);return b(c,d,e,f,a)};a.g=b;return a}(),d=function(d,h,k,l,m){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.g(d,h,k,l,Q(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.i=e.i;d.a=c;d.d=b;d.h=a;d.g=e.g;return d}();var Ya=new W(null,"meta","meta"),Za=new W(null,"dup","dup"),w=new W(null,"else","else"),De=new W(null,"validator","validator"),dc=new W(null,"default","default"),Wa=new W(null,"flush-on-newline","flush-on-newline"),Xa=new W(null,"readably","readably"),$a=new W(null,"print-length","print-length");r&&Ia("9");!ya||Ia("528");xa&&Ia("1.9b")||r&&Ia("8")||wa&&Ia("9.5")||ya&&Ia("528");xa&&!Ia("8")||r&&Ia("9");var He=document.createElement("div");He.innerHTML="   \x3clink/\x3e\x3ctable\x3e\x3c/table\x3e\x3ca href\x3d'/a' style\x3d'top:1px;float:left;opacity:.55;'\x3ea\x3c/a\x3e\x3cinput type\x3d'checkbox'/\x3e";var Ie=J.a(He.firstChild.nodeType,3),Je=J.a(He.getElementsByTagName("tbody").length,0);J.a(He.getElementsByTagName("link").length,0);function Ke(a){var b=Le;if("string"===typeof b)return a.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),"\x3c$1\x3e\x3c/$2\x3e");if(t(b.hasOwnProperty("source")))return a.replace(new RegExp(b.source,"g"),"\x3c$1\x3e\x3c/$2\x3e");if(w)throw"Invalid match arg: "+z.c(b);return null};var Me=/<|&#?\w+;/,Ne=/^\s+/,Le=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/i,Oe=/<([\w:]+)/,Pe=/<tbody/i,Qe=new X(null,3,5,Z,[1,"\x3cselect multiple\x3d'multiple'\x3e","\x3c/select\x3e"],null),Re=new X(null,3,5,Z,[1,"\x3ctable\x3e","\x3c/table\x3e"],null),Se=new X(null,3,5,Z,[3,"\x3ctable\x3e\x3ctbody\x3e\x3ctr\x3e","\x3c/tr\x3e\x3c/tbody\x3e\x3c/table\x3e"],null),Te=uc(["td","optgroup","tfoot","tr","area",dc,"option","legend","thead","col","caption","th","colgroup","tbody"],
[Se,Qe,Re,new X(null,3,5,Z,[2,"\x3ctable\x3e\x3ctbody\x3e","\x3c/tbody\x3e\x3c/table\x3e"],null),new X(null,3,5,Z,[1,"\x3cmap\x3e","\x3c/map\x3e"],null),new X(null,3,5,Z,[0,"",""],null),Qe,new X(null,3,5,Z,[1,"\x3cfieldset\x3e","\x3c/fieldset\x3e"],null),Re,new X(null,3,5,Z,[2,"\x3ctable\x3e\x3ctbody\x3e\x3c/tbody\x3e\x3ccolgroup\x3e","\x3c/colgroup\x3e\x3c/table\x3e"],null),Re,Se,Re,Re]);
function Ue(a,b,c,d){b=ab(re(Pe,b));J.a(c,"table")&&b?(c=a.firstChild,a=t(c)?a.firstChild.childNodes:c):a=J.a(d,"\x3ctable\x3e")&&b?divchildNodes:yd;a=L(a);c=null;for(var e=b=0;;)if(e<b)d=c.w(null,e),J.a(d.nodeName,"tbody")&&J.a(d.childNodes.length,0)&&d.parentNode.removeChild(d),e+=1;else if(a=L(a))c=a,Cc(c)?(a=Lb(c),b=Mb(c),c=a,d=U(a),a=b,b=d):(d=M(c),J.a(d.nodeName,"tbody")&&J.a(d.childNodes.length,0)&&d.parentNode.removeChild(d),a=P(c),c=null,b=0),e=0;else break}
function Ve(a,b){a.insertBefore(document.createTextNode(M(re(Ne,b))),a.firstChild)}function We(a){var b=Ke(a);a=(""+z.c(pc(re(Oe,b)))).toLowerCase();var c=tc.d(Te,a,dc.c(Te)),d=sc.d(c,0,null),e=sc.d(c,1,null),f=sc.d(c,2,null),c=function(){var a;a=document.createElement("div");a.innerHTML=""+z.c(e)+z.c(b)+z.c(f);for(var c=d;;)if(0<c)c-=1,a=a.lastChild;else return a}();t(Je)&&Ue(c,b,a,e);t(function(){var a=ab(Ie);return a?re(Ne,b):a}())&&Ve(c,b);return c.childNodes}
function Xe(a){return t(re(Me,a))?We(a):document.createTextNode(a)}function Ye(a){if(a?a.cb:a)return a.cb();var b;b=Ye[n(null==a?null:a)];if(!b&&(b=Ye._,!b))throw x("DomContent.nodes",a);return b.call(null,a)}
var Ze=function(){function a(a,b){return b<a.length?new Qc(null,function(){return T(a.item(b),c.a(a,b+1))},null,null):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}(),$e=function(){function a(a,b){return b<a.length?new Qc(null,function(){return T(a[b],c.a(a,b+1))},null,null):null}function b(a){return c.a(a,0)}var c=null,c=function(c,
e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}();function af(a){return t(a.item)?Ze.c(a):$e.c(a)}function bf(a){if(t(a)){var b=ab(a.nodeName);return b?a.length:b}return a}Ye._=function(a){return null==a?O:(a?a.f&8388608||a.wa||(a.f?0:v(zb,a)):v(zb,a))?L(a):t(bf(a))?af(a):dc?L(new X(null,1,5,Z,[a],null)):null};Ye.string=function(a){return ke.c(Ye(Xe(a)))};
t("undefined"!=typeof NodeList)&&(g=NodeList.prototype,g.wa=!0,g.A=function(){return af(this)},g.ua=!0,g.w=function(a,b){return this.item(b)},g.N=function(a,b,c){return this.length<=b?c:sc.a(this,b)},g.Da=!0,g.B=function(){return this.length});t("undefined"!=typeof StaticNodeList)&&(g=StaticNodeList.prototype,g.wa=!0,g.A=function(){return af(this)},g.ua=!0,g.w=function(a,b){return this.item(b)},g.N=function(a,b,c){return this.length<=b?c:sc.a(this,b)},g.Da=!0,g.B=function(){return this.length});
t("undefined"!=typeof HTMLCollection)&&(g=HTMLCollection.prototype,g.wa=!0,g.A=function(){return af(this)},g.ua=!0,g.w=function(a,b){return this.item(b)},g.N=function(a,b,c){return this.length<=b?c:sc.a(this,b)},g.Da=!0,g.B=function(){return this.length});/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var cf=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!da(a))return[a];if(da(c)&&(c=da(c)?document.getElementById(c):c,!c))return[];c=c||document;var e=c.ownerDocument||c.documentElement;sa=c.contentType&&"application/xml"==c.contentType||wa&&(c.doctype||"[object XMLDocument]"==e.toString())||!!e&&(r?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.Ha?e:b(e)}function b(a){if(a&&a.Ha)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;
Ka++;if(r&&sa){var c=Ka+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(r&&a.Fb)try{for(d=1;e=a[d];d++)y(e)&&b.push(e)}catch(f){}else for(a[0]&&(a[0]._zipIdx=Ka),d=1;e=a[d];d++)a[d]._zipIdx!=Ka&&b.push(e),e._zipIdx=Ka;return b}function c(a,b){if(!b)return 1;var c=pf(a);return b[c]?0:b[c]=1}function d(a,b){if(me){var c=ne[a];if(c&&!b)return c}if(c=oe[a])return c;var c=a.charAt(0),f=-1==a.indexOf(" ");0<=a.indexOf("#")&&
f&&(b=!0);if(!me||b||-1!="\x3e~+".indexOf(c)||r&&-1!=a.indexOf(":")||ga&&0<=a.indexOf(".")||-1!=a.indexOf(":contains")||-1!=a.indexOf("|\x3d")){var h=a.split(/\s*,\s*/);return oe[a]=2>h.length?e(a):function(a){for(var b=0,c=[],d;d=h[b++];)c=c.concat(e(d)(a));return c}}var k=0<="\x3e~+".indexOf(a.charAt(a.length-1))?a+" *":a;return ne[a]=function(b){try{if(9!=b.nodeType&&!f)throw"";var c=b.querySelectorAll(k);r?c.Fb=!0:c.Ha=!0;return c}catch(e){return d(a,!0)(b)}}}function e(a){var b=R(ja(a));if(1==
b.length){var c=f(b[0]);return function(a){if(a=c(a,[]))a.Ha=!0;return a}}return function(a){a=S(a);for(var c,d,e=b.length,h,k,l=0;l<e;l++){k=[];c=b[l];d=a.length-1;0<d&&(h={},k.Ha=!0);d=f(c);for(var le=0;c=a[le];le++)d(c,k,h);if(!k.length)break;a=k}return k}}function f(a){var b=pe[a.pa];if(b)return b;var c=a.qb,c=c?c.Ia:"",d=m(a,{na:1}),e="*"==a.tag,f=document.getElementsByClassName;if(c)f={na:1},e&&(f.tag=1),d=m(a,f),"+"==c?b=l(d):"~"==c?b=k(d):"\x3e"==c&&(b=h(d));else if(a.id)d=!a.rb&&e?Ma:m(a,
{na:1,id:1}),b=function(b,c){var e;e=b?new Ra(9==b.nodeType?b:b.ownerDocument||b.document):ia||(ia=new Ra);var f=a.id;if((f=(e=da(f)?e.bb.getElementById(f):f)&&d(e))&&!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return S(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.aa.length&&!ga)var d=m(a,{na:1,aa:1,id:1}),p=a.aa.join(" "),b=function(a,b){for(var c=S(0,b),e,f=0,h=a.getElementsByClassName(p);e=h[f++];)d(e,a)&&c.push(e);return c};else e||a.rb?(d=m(a,
{na:1,tag:1,id:1}),b=function(b,c){for(var e=S(0,c),f,h=0,k=b.getElementsByTagName(a.eb());f=k[h++];)d(f,b)&&e.push(f);return e}):b=function(b,c){for(var d=S(0,c),e,f=0,h=b.getElementsByTagName(a.eb());e=h[f++];)d.push(e);return d};return pe[a.pa]=b}function h(a){a=a||Ma;return function(b,d,e){for(var f=0,h=b[Ha];b=h[f++];)Sb(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function k(a){return function(b,d,e){for(b=b[Tb];b;){if(Sb(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[Tb]}return d}}function l(a){return function(b,
d,e){for(;b=b[Tb];)if(!xc||y(b)){e&&!c(b,e)||!a(b)||d.push(b);break}return d}}function m(a,b){if(!a)return Ma;b=b||{};var c=null;b.na||(c=K(c,y));b.tag||"*"!=a.tag&&(c=K(c,function(b){return b&&b.tagName==a.eb()}));b.aa||ma(a.aa,function(a,b){var d=new RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=K(c,function(a){return d.test(a.className)});c.count=b});b.ja||ma(a.ja,function(a){var b=a.name;Zc[b]&&(c=K(c,Zc[b](b,a.value)))});b.Aa||ma(a.Aa,function(a){var b,d=a.Ja;a.type&&qe[a.type]?b=qe[a.type](d,a.fb):d.length&&
(b=qf(d));b&&(c=K(c,b))});b.id||a.id&&(c=K(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=Ma);return c}function p(a){return s(a)%2}function q(a){return!(s(a)%2)}function s(a){var b=a.parentNode,c=0,d=b[Ha],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Tb])Sb(b)&&(b._i=++c,a===b&&(e=c));return e}function u(a){for(;a=a[Tb];)if(Sb(a))return!1;return!0}function A(a){for(;a=a[rf];)if(Sb(a))return!1;return!0}
function F(a,b){return a?"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(sa?a.getAttribute(b):a.getAttribute(b,2))||"":""}function y(a){return 1==a.nodeType}function K(a,b){return a?b?function(){return a.apply(window,arguments)&&b.apply(window,arguments)}:a:b}function R(a){function b(){0<=m&&(I.id=c(m,u).replace(/\\/g,""),m=-1);if(0<=p){var a=p==u?null:c(p,u);0>"\x3e~+".indexOf(a)?I.tag=a:I.Ia=a;p=-1}0<=l&&(I.aa.push(c(l+1,u).replace(/\\/g,"")),l=-1)}function c(b,
d){return ja(a.slice(b,d))}a=0<="\x3e~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],e=-1,f=-1,h=-1,k=-1,l=-1,m=-1,p=-1,q="",s="",A,u=0,F=a.length,I=null,y=null;q=s,s=a.charAt(u),u<F;u++)"\\"!=q&&(I||(A=u,I={pa:null,ja:[],Aa:[],aa:[],tag:null,Ia:null,id:null,eb:function(){return sa?this.Hb:this.tag}},p=u),0<=e?"]"==s?(y.Ja?y.fb=c(h||e+1,u):y.Ja=c(e+1,u),!(e=y.fb)||'"'!=e.charAt(0)&&"'"!=e.charAt(0)||(y.fb=e.slice(1,-1)),I.Aa.push(y),y=null,e=h=-1):"\x3d"==s&&(h=0<="|~^$*".indexOf(q)?q:"",y.type=
h+s,y.Ja=c(e+1,u-h.length),h=u+1):0<=f?")"==s&&(0<=k&&(y.value=c(f+1,u)),k=f=-1):"#"==s?(b(),m=u+1):"."==s?(b(),l=u):":"==s?(b(),k=u):"["==s?(b(),e=u,y={}):"("==s?(0<=k&&(y={name:c(k+1,u),value:null},I.ja.push(y)),f=u):" "==s&&q!=s&&(b(),0<=k&&I.ja.push({name:c(k+1,u)}),I.rb=I.ja.length||I.Aa.length||I.aa.length,I.Ub=I.pa=c(A,u),I.Hb=I.tag=I.Ia?null:I.tag||"*",I.tag&&(I.tag=I.tag.toUpperCase()),d.length&&d[d.length-1].Ia&&(I.qb=d.pop(),I.pa=I.qb.pa+" "+I.pa),d.push(I),I=null));return d}function S(a,
b){var c=b||[];a&&c.push(a);return c}var ga=ya&&"BackCompat"==document.compatMode,Ha=document.firstChild.children?"children":"childNodes",sa=!1,qe={"*\x3d":function(a,b){return function(c){return 0<=F(c,a).indexOf(b)}},"^\x3d":function(a,b){return function(c){return 0==F(c,a).indexOf(b)}},"$\x3d":function(a,b){return function(c){c=" "+F(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~\x3d":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+F(b,a)+" ").indexOf(c)}},"|\x3d":function(a,
b){b=" "+b;return function(c){c=" "+F(c,a);return c==b||0==c.indexOf(b+"-")}},"\x3d":function(a,b){return function(c){return F(c,a)==b}}},xc="undefined"==typeof document.firstChild.nextElementSibling,Tb=xc?"nextSibling":"nextElementSibling",rf=xc?"previousSibling":"previousElementSibling",Sb=xc?y:Ma,Zc={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return A},"last-child":function(){return u},"only-child":function(){return function(a){return A(a)&&
u(a)?!0:!1}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=R(b)[0],d={na:1};"*"!=c.tag&&(d.tag=1);c.aa.length||(d.aa=1);var e=m(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return p;if("even"==b)return q;if(-1!=b.indexOf("n")){var c=
b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,h=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(h=e,e%=d));if(0<d)return function(a){a=s(a);return a>=f&&(0>h||a<=h)&&a%d==e};b=e}var k=parseInt(b,10);return function(a){return s(a)==k}}},qf=r?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return sa?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},
pe={},oe={},ne={},me=!!document.querySelectorAll&&(!ya||Ia("526")),Ka=0,pf=r?function(a){return sa?a.getAttribute("_uid")||a.setAttribute("_uid",++Ka)||Ka:a.uniqueID}:function(a){return a._uid||(a._uid=++Ka)};a.ja=Zc;return a}();ba("goog.dom.query",cf);ba("goog.dom.query.pseudos",cf.ja);var df,ef=function(){function a(a,b){"undefined"===typeof df&&(df=function(a,b,c,d){this.pb=a;this.gb=b;this.Jb=c;this.Gb=d;this.o=0;this.f=393216},df.ob=!0,df.nb="domina.css/t5119",df.Eb=function(a){return H(a,"domina.css/t5119")},df.prototype.cb=function(){var a=this;return id.a(function(){return function(b){b=cf(a.pb,b);return null==b?O:(b?b.f&8388608||b.wa||(b.f?0:v(zb,b)):v(zb,b))?L(b):t(bf(b))?af(b):dc?L(new X(null,1,5,Z,[b],null)):null}}(this),Ye(a.gb))},df.prototype.G=function(){return this.Gb},
df.prototype.H=function(a,b){return new df(this.pb,this.gb,this.Jb,b)});return new df(b,a,c,null)}function b(a){return c.a(Oa()[0],a)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.a=a;return c}();for(var ff=Ee.c(Od),gf=L(ef.c("textarea").cb()),hf=null,jf=0,kf=0;;)if(kf<jf){var lf=hf.w(null,kf);Ge.h(ff,vc,lf.id,CodeMirror.fromTextArea(lf,{lineNumbers:!0,fontSize:15,mode:"javascript"}));kf+=1}else{var mf=L(gf);if(mf){var nf=mf;if(Cc(nf))var of=Lb(nf),sf=Mb(nf),tf=of,uf=U(of),gf=sf,hf=tf,jf=uf;else{var vf=M(nf);Ge.h(ff,vc,vf.id,CodeMirror.fromTextArea(vf,{lineNumbers:!0,fontSize:15,mode:"javascript"}));gf=P(nf);hf=null;jf=0}kf=0}else break}
window.document.evaluate=function(a){a=tc.a(rb(ff),a);var b=RegExp("\n\\/\\/.*","g"),b=a.getValue().replace(b,""),c=window.eval(b);return void 0===c?a.setValue(""+z.c(b)+"\n// undefined"):a.setValue(""+z.c(b)+"\n// "+z.c(JSON.stringify(c)))};
})();
