// transit-js 0.1.540
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){var aa=this;
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function k(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};function l(a,b){this.k=a|0;this.h=b|0}var ca={};function da(a){if(-128<=a&&128>a){var b=ca[a];if(b)return b}b=new l(a|0,0>a?-1:0);-128<=a&&128>a&&(ca[a]=b);return b}function m(a){return isNaN(a)||!isFinite(a)?n:a<=-ea?p:a+1>=ea?fa:0>a?q(m(-a)):new l(a%r|0,a/r|0)}function s(a,b){return new l(a,b)}
function ga(a,b){if(0==a.length)throw Error("number format error: empty string");var c=b||10;if(2>c||36<c)throw Error("radix out of range: "+c);if("-"==a.charAt(0))return q(ga(a.substring(1),c));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var d=m(Math.pow(c,8)),e=n,f=0;f<a.length;f+=8){var g=Math.min(8,a.length-f),h=parseInt(a.substring(f,f+g),c);8>g?(g=m(Math.pow(c,g)),e=e.multiply(g).add(m(h))):(e=e.multiply(d),e=e.add(m(h)))}return e}
var r=4294967296,ea=r*r/2,n=da(0),ha=da(1),ia=da(-1),fa=s(-1,2147483647),p=s(0,-2147483648),ja=da(16777216);function ka(a){return a.h*r+(0<=a.k?a.k:r+a.k)}
l.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(u(this))return"0";if(0>this.h){if(v(this,p)){var b=m(a),c=w(this,b),b=la(c.multiply(b),this);return c.toString(a)+b.k.toString(a)}return"-"+q(this).toString(a)}for(var c=m(Math.pow(a,6)),b=this,d="";;){var e=w(b,c),f=la(b,e.multiply(c)).k.toString(a),b=e;if(u(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function u(a){return 0==a.h&&0==a.k}function v(a,b){return a.h==b.h&&a.k==b.k}
l.prototype.compare=function(a){if(v(this,a))return 0;var b=0>this.h,c=0>a.h;return b&&!c?-1:!b&&c?1:0>la(this,a).h?-1:1};function q(a){return v(a,p)?p:s(~a.k,~a.h).add(ha)}l.prototype.add=function(a){var b=this.h>>>16,c=this.h&65535,d=this.k>>>16,e=a.h>>>16,f=a.h&65535,g=a.k>>>16,h;h=0+((this.k&65535)+(a.k&65535));a=0+(h>>>16);a+=d+g;d=0+(a>>>16);d+=c+f;c=0+(d>>>16);c=c+(b+e)&65535;return s((a&65535)<<16|h&65535,c<<16|d&65535)};function la(a,b){return a.add(q(b))}
l.prototype.multiply=function(a){if(u(this)||u(a))return n;if(v(this,p))return 1==(a.k&1)?p:n;if(v(a,p))return 1==(this.k&1)?p:n;if(0>this.h)return 0>a.h?q(this).multiply(q(a)):q(q(this).multiply(a));if(0>a.h)return q(this.multiply(q(a)));if(0>this.compare(ja)&&0>a.compare(ja))return m(ka(this)*ka(a));var b=this.h>>>16,c=this.h&65535,d=this.k>>>16,e=this.k&65535,f=a.h>>>16,g=a.h&65535,h=a.k>>>16;a=a.k&65535;var N,t,A,Fa;Fa=0+e*a;A=0+(Fa>>>16);A+=d*a;t=0+(A>>>16);A=(A&65535)+e*h;t+=A>>>16;A&=65535;
t+=c*a;N=0+(t>>>16);t=(t&65535)+d*h;N+=t>>>16;t&=65535;t+=e*g;N+=t>>>16;t&=65535;N=N+(b*a+c*h+d*g+e*f)&65535;return s(A<<16|Fa&65535,N<<16|t)};
function w(a,b){if(u(b))throw Error("division by zero");if(u(a))return n;if(v(a,p)){if(v(b,ha)||v(b,ia))return p;if(v(b,p))return ha;var c;c=1;if(0==c)c=a;else{var d=a.h;c=32>c?s(a.k>>>c|d<<32-c,d>>c):s(d>>c-32,0<=d?0:-1)}c=w(c,b).shiftLeft(1);if(v(c,n))return 0>b.h?ha:ia;d=la(a,b.multiply(c));return c.add(w(d,b))}if(v(b,p))return n;if(0>a.h)return 0>b.h?w(q(a),q(b)):q(w(q(a),b));if(0>b.h)return q(w(a,q(b)));for(var e=n,d=a;0<=d.compare(b);){c=Math.max(1,Math.floor(ka(d)/ka(b)));for(var f=Math.ceil(Math.log(c)/
Math.LN2),f=48>=f?1:Math.pow(2,f-48),g=m(c),h=g.multiply(b);0>h.h||0<h.compare(d);)c-=f,g=m(c),h=g.multiply(b);u(g)&&(g=ha);e=e.add(g);d=la(d,h)}return e}l.prototype.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.k;return 32>a?s(b<<a,this.h<<a|b>>>32-a):s(0,b<<a-32)};function ma(a,b){b&=63;if(0==b)return a;var c=a.h;return 32>b?s(a.k>>>b|c<<32-b,c>>>b):32==b?s(c,0):s(c>>>b-32,0)};var x="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},y="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===ba(a)};function z(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(y(a)){if(y(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!z(a[c],b[c]))return!1;return!0}return!1}if(a.s)return a.s(b);if(null!=b&&"object"===typeof b){if(b.s)return b.s(a);var d=c=0,e=x(b).length,f;for(f in a)if(a.hasOwnProperty(f))if(d++,"$com$cognitect$transit$hashCode$"==f)b[f]||(c=-1);else if(!b.hasOwnProperty(f)||!z(a[f],b[f]))return!1;return d+c===e}}return!1}
function na(a,b){return a^b+2654435769+(a<<6)+(a>>2)}var oa={},pa=0;function qa(a){var b=0;if(null!=a.forEach)a.forEach(function(a,c){b=(b+(B(c)^B(a)))%4503599627370496});else for(var c=x(a),d=0;d<c.length;d++){var e=c[d];if("$com$cognitect$transit$hashCode$"!==e)var f=a[e],b=(b+(B(e)^B(f)))%4503599627370496}return b}function ra(a){var b=0;if(y(a))for(var c=0;c<a.length;c++)b=na(b,B(a[c]));else a.forEach&&a.forEach(function(a){b=na(b,B(a))});return b}
function B(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":var b=oa[a];if(null==b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;pa++;256<=pa&&(oa={},pa=1);oa[a]=b}a=b;return a;default:if(a instanceof Date)return a.valueOf();if(y(a))return ra(a);if(a.v)return a.v();if(a.$com$cognitect$transit$hashCode$)return a.$com$cognitect$transit$hashCode$;b=qa(a);return a.$com$cognitect$transit$hashCode$=b}};var sa={},ta=ga("9007199254740992"),ua=ga("-9007199254740992");function va(a){if("number"===typeof a||a instanceof l)return a;a=ga(a,10);return 0<a.compare(ta)||0>a.compare(ua)?a:ka(a)}l.prototype.q=function(a){return z(this,a)};l.prototype.equiv=l.prototype.q;l.prototype.s=function(a){return a instanceof l&&v(this,a)};l.prototype.v=function(){return this.k};function C(a){this.value=a}C.prototype.toString=function(){return"[BigInteger: "+this.value+"]"};C.prototype.q=function(a){return z(this,a)};
C.prototype.equiv=C.prototype.q;C.prototype.s=function(a){return a instanceof C&&this.value===a.value};C.prototype.v=function(){return B(this.value)};function wa(a){return new C(a)}function D(a){this.value=a}D.prototype.toString=function(){return"[BigDecimal: "+this.value+"]"};D.prototype.q=function(a){return z(this,a)};D.prototype.equiv=D.prototype.q;D.prototype.s=function(a){return a instanceof D&&this.value===a.value};D.prototype.v=function(){return B(this.value)};
function xa(a){return new D(a)}function E(a){this.name=a;this.a=-1}E.prototype.toString=function(){return":"+this.name};E.prototype.q=function(a){return z(this,a)};E.prototype.equiv=E.prototype.q;E.prototype.s=function(a){return a instanceof E&&this.name==a.name};E.prototype.v=function(){-1===this.a&&(this.a=B(this.name));return this.a};function ya(a){return new E(a)}function F(a){this.name=a;this.a=-1}F.prototype.toString=function(){return"[Symbol: "+this.name+"]"};
F.prototype.q=function(a){return z(this,a)};F.prototype.equiv=F.prototype.q;F.prototype.s=function(a){return a instanceof F&&this.name==a.name};F.prototype.v=function(){-1===this.a&&(this.a=B(this.name));return this.a};function za(a){return new F(a)}function Aa(a,b,c){var d="";c=c||b+1;for(var e=8*(7-b),f=da(255).shiftLeft(e);b<c;b++,e-=8,f=ma(f,8)){var g=ma(s(a.k&f.k,a.h&f.h),e).toString(16);1==g.length&&(g="0"+g);d+=g}return d}function G(a,b){this.Y=a;this.aa=b;this.a=-1}
G.prototype.toString=function(a){var b=this.Y,c=this.aa;a=""+(Aa(b,0,4)+"-");a+=Aa(b,4,6)+"-";a+=Aa(b,6,8)+"-";a+=Aa(c,0,2)+"-";return a+=Aa(c,2,8)};G.prototype.q=function(a){return z(this,a)};G.prototype.equiv=G.prototype.q;G.prototype.s=function(a){return a instanceof G&&v(this.Y,a.Y)&&v(this.aa,a.aa)};
function Ba(a){a=a.replace(/-/g,"");for(var b=null,c=null,d=c=0,e=24,f=0,f=c=0,e=24;8>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;f=8;for(e=24;16>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;b=s(d,c);c=0;f=16;for(e=24;24>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;for(e=f=24;32>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;c=s(d,c);return new G(b,c)}function Ca(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)}
Date.prototype.s=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.v=function(){return this.valueOf()};function H(a){this.D=a;this.a=-1}H.prototype.q=function(a){return z(this,a)};H.prototype.equiv=H.prototype.q;H.prototype.s=function(a){return a instanceof H?this.D=a.D:!1};H.prototype.v=function(){-1===this.a&&(this.a=B(this.D));return this.a};function Da(a){return new H(a)}function I(a){this.uri=a;this.a=-1}
I.prototype.toString=function(){return"[URI: "+this.uri+"]"};I.prototype.q=function(a){return z(this,a)};I.prototype.equiv=I.prototype.q;I.prototype.s=function(a){return a instanceof I?this.uri=a.uri:!1};I.prototype.v=function(){-1===this.a&&(this.a=B(this.uri));return this.a};function Ea(a){return new I(a)}function J(a,b){this.B=a;this.type=b||0;this.o=0}
J.prototype.next=function(){if(this.o<this.B.length){var a=null,a=0===this.type?this.B[this.o]:1===this.type?this.B[this.o+1]:[this.B[this.o],this.B[this.o+1]],a={value:a,done:!1};this.o+=2;return a}return{value:null,done:!0}};J.prototype.next=J.prototype.next;function K(a,b){this.map=a;this.type=b||0;this.keys=Ga(this.map);this.o=0;this.K=null;this.G=0}
K.prototype.next=function(){if(this.o<this.map.size){null!=this.K&&this.G<this.K.length||(this.K=this.map.map[this.keys[this.o]],this.G=0);var a=null,a=0===this.type?this.K[this.G]:1===this.type?this.K[this.G+1]:[this.K[this.G],this.K[this.G+1]],a={value:a,done:!1};this.o++;this.G+=2;return a}return{value:null,done:!0}};K.prototype.next=K.prototype.next;
function Ha(a,b){if((b instanceof L||b instanceof M)&&a.size===b.size){for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!z(d[e+1],b.get(d[e])))return!1;return!0}if(null!=b&&"object"===typeof b&&(c=x(b).length-(b.hasOwnProperty("$com$cognitect$transit$hashCode$")&&1||0),a.size===c)){for(d in b)if("$com$cognitect$transit$hashCode$"!==d&&!z(b[d],a.get(d)))return!1;return!0}return!1}function M(a){this.j=a;this.g=null;this.a=-1;this.size=a.length/2;this.ca=0}M.prototype.toString=function(){return"[TransitArrayMap]"};
function Ia(a){if(a.g)throw Error("Invalid operation, already converted");if(8>a.size)return!1;a.ca++;return 32<a.ca?(a.g=O(a.j,!1,!0),a.j=[],!0):!1}M.prototype.clear=function(){this.g?this.g.clear():this.j=[];this.size=0};M.prototype.clear=M.prototype.clear;M.prototype.keys=function(){return this.g?this.g.keys():new J(this.j,0)};M.prototype.keys=M.prototype.keys;M.prototype.I=function(){if(this.g)return this.g.I();for(var a=[],b=0,c=0;c<this.j.length;b++,c+=2)a[b]=this.j[c];return a};
M.prototype.keySet=M.prototype.I;M.prototype.B=function(){return this.g?this.g.B():new J(this.j,2)};M.prototype.entries=M.prototype.B;M.prototype.L=function(){return this.g?this.g.L():new J(this.j,1)};M.prototype.values=M.prototype.L;M.prototype.forEach=function(a){if(this.g)this.g.forEach(a);else for(var b=0;b<this.j.length;b+=2)a(this.j[b+1],this.j[b])};M.prototype.forEach=M.prototype.forEach;
M.prototype.get=function(a){if(this.g)return this.g.get(a);if(Ia(this))return this.get(a);for(var b=0;b<this.j.length;b+=2)if(z(this.j[b],a))return this.j[b+1];return null};M.prototype.get=M.prototype.get;M.prototype.H=function(a){if(this.g)return this.g.H(a);if(Ia(this))return this.H(a);for(var b=0;b<this.j.length;b+=2)if(z(this.j[b],a))return!0;return!1};M.prototype.has=M.prototype.H;
M.prototype.set=function(a,b){if(this.g)this.g.set(a,b),this.size=this.g.size;else{for(var c=0;c<this.j.length;c+=2)if(z(this.j[c],a)){this.j[c+1]=b;return}this.j.push(a);this.j.push(b);this.size++;32<this.size&&(this.g=O(this.j,!1,!0),this.j=null)}};M.prototype.set=M.prototype.set;M.prototype["delete"]=function(a){if(this.g)this.g["delete"](a),this.size=this.g.size;else for(var b=0;b<this.j.length;b+=2)if(z(this.j[b],a)){this.j.splice(b,2);this.size--;break}};
M.prototype.v=function(){if(this.g)return this.g.v();-1===this.a&&(this.a=qa(this));return this.a};M.prototype.s=function(a){return this.g?Ha(this.g,a):Ha(this,a)};function L(a,b,c){this.map=b||{};this.M=a||[];this.size=c||0;this.a=-1}L.prototype.toString=function(){return"[TransitMap]"};L.prototype.clear=function(){this.map={};this.M=[];this.size=0;this.a=-1};L.prototype.clear=L.prototype.clear;function Ga(a){return null!=a.M?a.M:x(a.map)}
L.prototype["delete"]=function(a){this.M=null;for(var b=B(a),c=this.map[b],d=0;d<c.length;d+=2)if(z(a,c[d])){c.splice(d,2);0===c.length&&delete this.map[b];this.size--;break}};L.prototype.B=function(){return new K(this,2)};L.prototype.entries=L.prototype.B;L.prototype.forEach=function(a){for(var b=Ga(this),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};L.prototype.forEach=L.prototype.forEach;
L.prototype.get=function(a){var b=B(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2){if(z(a,b[c]))return b[c+1]}else return null};L.prototype.get=L.prototype.get;L.prototype.H=function(a){var b=B(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2)if(z(a,b[c]))return!0;return!1};L.prototype.has=L.prototype.H;L.prototype.keys=function(){return new K(this,0)};L.prototype.keys=L.prototype.keys;
L.prototype.I=function(){for(var a=Ga(this),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};L.prototype.keySet=L.prototype.I;L.prototype.set=function(a,b){var c=B(a),d=this.map[c];if(null==d)this.M&&this.M.push(c),this.map[c]=[a,b],this.size++;else{for(var c=!0,e=0;e<d.length;e+=2)if(z(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};L.prototype.set=L.prototype.set;L.prototype.L=function(){return new K(this,1)};L.prototype.values=L.prototype.L;
L.prototype.v=function(){-1===this.a&&(this.a=qa(this));return this.a};L.prototype.s=function(a){return Ha(this,a)};
function O(a,b,c){a=a||[];b=!1===b?b:!0;if((!0!==c||!c)&&64>=a.length){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(z(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new M(a)}var d={},e=[],f=0;for(b=0;b<a.length;b+=2){c=B(a[b]);var g=d[c];if(null==g)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var h=!0;for(c=0;c<g.length;c+=2)if(z(g[c],a[b])){g[c+1]=a[b+1];h=!1;break}h&&(g.push(a[b]),g.push(a[b+1]),f++)}}return new L(e,d,f)}
function P(a){this.map=a;this.size=a.size}P.prototype.toString=function(){return"[TransitSet]"};P.prototype.add=function(){throw Error("Unsupported operation: add");};P.prototype.add=P.prototype.add;P.prototype.clear=function(){this.map=new L;this.size=0};P.prototype.clear=P.prototype.clear;P.prototype["delete"]=function(a){this.map["delete"](a);this.size=this.map.size};P.prototype.B=function(){return this.map.B()};P.prototype.entries=P.prototype.B;
P.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};P.prototype.forEach=P.prototype.forEach;P.prototype.H=function(a){return this.map.H(a)};P.prototype.has=P.prototype.H;P.prototype.keys=function(){return this.map.keys()};P.prototype.keys=P.prototype.keys;P.prototype.I=function(){return this.map.I()};P.prototype.keySet=P.prototype.I;P.prototype.L=function(){return this.map.L()};P.prototype.values=P.prototype.L;
P.prototype.s=function(a){if(a instanceof P){if(this.size===a.size)return z(this.map,a.map)}else return!1};P.prototype.v=function(){return B(this.map)};function Ja(a){for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=B(a[e]),g=b[f];if(null==g)c.push(f),b[f]=[a[e],a[e]],d++;else{for(var f=!0,h=0;h<g.length;h+=2)if(z(g[h],a[e])){f=!1;break}f&&(g.push(a[e]),g.push(a[e]),d++)}}return new P(new L(c,b,d))}function Q(a){this.F=a;this.a=-1}Q.prototype.q=function(a){return z(this,a)};Q.prototype.equiv=Q.prototype.q;
Q.prototype.s=function(a){return a instanceof Q?z(this.F,a.F):!1};Q.prototype.v=function(){-1===this.a&&(this.a=B(this.F));return this.a};Q.prototype.toString=function(){return"[Quoted]"};function Ka(a){return new Q(a)}function R(a,b){this.tag=a;this.e=b;this.a=-1}R.prototype.toString=function(){return"[TaggedValue: "+tag+", "+rep+"]"};R.prototype.q=function(a){return z(this,a)};R.prototype.equiv=R.prototype.q;R.prototype.s=function(a){return a instanceof R?this.tag===a.tag&&z(this.e,a.e):!1};
R.prototype.v=function(){-1===this.a&&(this.a=na(B(this.tag),B(this.e)));return this.a};function S(a,b){return new R(a,b)}function T(a){this.V=a}T.prototype.q=function(a){return z(this,a)};T.prototype.equiv=T.prototype.q;T.prototype.s=function(a){return a instanceof T?z(this.V,a.V):!1};T.prototype.v=function(){-1==this.a&&(this.a=B(this.F));return this.a};function La(a){return new T(a)}function U(a){this.e=a;this.a=-1}U.prototype.q=function(a){return z(this,a)};U.prototype.equiv=U.prototype.q;
U.prototype.s=function(a){return a instanceof U?z(this.e,a.e):!1};U.prototype.v=function(){-1===this.a&&(this.a=B(this.e));return this.a};function Ma(a,b){if(3<a.length){if(b)return!0;var c=a.charAt(1);return"~"===a.charAt(0)?":"===c||"$"===c||"#"===c:!1}return!1}function Na(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return 0===b?"^"+a:"^"+String.fromCharCode(b+48)+a}function Oa(){this.ea=this.Q=this.o=0;this.A={}}
Oa.prototype.write=function(a,b){if(Ma(a,b)){4096===this.ea?(this.clear(),this.Q=0,this.A={}):1936===this.o&&this.clear();var c=this.A[a];return null==c?(this.A[a]=[Na(this.o),this.Q],this.o++,a):c[1]!=this.Q?(c[1]=this.Q,c[0]=Na(this.o),this.o++,a):c[0]}return a};Oa.prototype.clear=function(){this.o=0;this.Q++};function Pa(){this.o=0;this.A=[]}Pa.prototype.write=function(a){1936==this.o&&(this.o=0);this.A[this.o]=a;this.o++;return a};
Pa.prototype.ba=function(a){return this.A[2===a.length?a.charCodeAt(1)-48:44*(a.charCodeAt(1)-48)+(a.charCodeAt(2)-48)]};Pa.prototype.clear=function(){this.o=0};function Qa(a){this.D=a}
function V(a){this.options=a||{};this.w={};for(var b in this.R.w)this.w[b]=this.R.w[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error("Cannot override handler for ground types");this.w[b]=this.options.handlers[b]}this.S=null!=this.options.preferStrings?this.options.preferStrings:this.R.S;this.W=this.options.defaultHandler||this.R.W;this.C=this.options.mapBuilder;this.N=this.options.arrayBuilder}
V.prototype.R={w:{_:function(){return null},"?":function(a){return"t"===a},b:function(a){return Da(a)},i:function(a){return va(a)},n:function(a){return wa(a)},d:function(a){return parseFloat(a)},f:function(a){return xa(a)},c:function(a){return a},":":function(a){return ya(a)},$:function(a){return za(a)},r:function(a){return Ea(a)},"'":function(a){return a},m:function(a){return Ca(a)},t:function(a){return new Date(a)},u:function(a){return Ba(a)},set:function(a){return Ja(a)},list:function(a){return La(a)},
cmap:function(a){return O(a,!1)}},W:function(a,b){return S(a,b)},S:!0};
V.prototype.l=function(a,b,c,d){if(null==a)return null;switch(typeof a){case "string":return Ma(a,c)?(a=Ra(this,a),b&&b.write(a,c),b=a):b="^"===a.charAt(0)?b.ba(a,c):Ra(this,a),b;case "object":if(y(a))if("^ "===a[0])if(this.C)if(17>a.length&&this.C.P){d=[];for(c=1;c<a.length;c+=2)d.push(this.l(a[c],b,!0,!1)),d.push(this.l(a[c+1],b,!1,!1));b=this.C.P(d)}else{d=this.C.Z();for(c=1;c<a.length;c+=2)d=this.C.add(d,this.l(a[c],b,!0,!1),this.l(a[c+1],b,!1,!1));b=this.C.X(d)}else{d=[];for(c=1;c<a.length;c+=
2)d.push(this.l(a[c],b,!0,!1)),d.push(this.l(a[c+1],b,!1,!1));b=O(d,!1)}else b=Sa(this,a,b,d);else{c=x(a);var e=c[0];if((d=1==c.length?this.l(e,b,!1,!1):null)&&d instanceof Qa)a=a[e],c=this.w[d.D],b=null!=c?c(this.l(a,b,!1,!0)):S(d.D,this.l(a,b,!1,!1));else if(this.C)if(16>c.length&&this.C.P){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.l(e,b,!0,!1)),f.push(this.l(a[e],b,!1,!1));b=this.C.P(f)}else{f=this.C.Z();for(d=0;d<c.length;d++)e=c[d],f=this.C.add(f,this.l(e,b,!0,!1),this.l(a[e],b,!1,!1));
b=this.C.X(f)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.l(e,b,!0,!1)),f.push(this.l(a[e],b,!1,!1));b=O(f,!1)}}return b}return a};V.prototype.decode=V.prototype.l;
function Sa(a,b,c,d){if(d){var e=[];for(d=0;d<b.length;d++)e.push(a.l(b[d],c,!1,!1));return e}if(2===b.length&&"string"===typeof b[0]&&(d=a.l(b[0],c,!1,!1))&&d instanceof Qa)return b=b[1],e=a.w[d.D],null!=e?e=e(a.l(b,c,!1,!0)):S(d.D,a.l(b,c,!1,!1));if(a.N){if(32>=b.length&&a.N.P){e=[];for(d=0;d<b.length;d++)e.push(a.l(b[d],c,!1,!1));return a.N.P(e)}e=a.N.Z();for(d=0;d<b.length;d++)e=a.N.add(e,a.l(b[d],c,!1,!1));return a.N.X(e)}e=[];for(d=0;d<b.length;d++)e.push(a.l(b[d],c,!1,!1));return e}
function Ra(a,b){if("~"===b.charAt(0)){var c=b.charAt(1);if("~"===c||"^"===c||"`"===c)return b.substring(1);if("#"===c)return new Qa(b.substring(2));var d=a.w[c];return null==d?a.W(c,b.substring(2)):d(b.substring(2))}return b};function Ta(a){this.fa=new V(a)}function Ua(a,b){this.ha=a;this.options=b||{};this.A=this.options.cache?this.options.cache:new Pa}Ua.prototype.ba=function(a){var b=this.A;a=this.ha.fa.l(JSON.parse(a),b);this.A.clear();return a};Ua.prototype.read=Ua.prototype.ba;var Va=0;function Wa(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a.com$cognitect$transit$ctor$guid;null==b&&(a.com$cognitect$transit$ctor$guid=b=++Va);return b}function W(a){return null==a?null:a.constructor}function X(a,b){for(var c=a.toString(),d=c.length;d<b;d++)c="0"+c;return c}function Xa(){}Xa.prototype.tag=function(){return"_"};Xa.prototype.e=function(){return null};
Xa.prototype.p=function(){return"null"};function Ya(){}Ya.prototype.tag=function(){return"s"};Ya.prototype.e=function(a){return a};Ya.prototype.p=function(a){return a};function Za(){}Za.prototype.tag=function(){return"i"};Za.prototype.e=function(a){return a};Za.prototype.p=function(a){return a.toString()};function $a(){}$a.prototype.tag=function(){return"i"};$a.prototype.e=function(a){return a.toString()};$a.prototype.p=function(a){return a.toString()};function ab(){}ab.prototype.tag=function(){return"n"};
ab.prototype.e=function(a){return a.value};ab.prototype.p=function(a){return a.value};function bb(){}bb.prototype.tag=function(){return"f"};bb.prototype.e=function(a){return a.value};bb.prototype.p=function(a){return a.value};function cb(){}cb.prototype.tag=function(){return"?"};cb.prototype.e=function(a){return a};cb.prototype.p=function(a){return a.toString()};function db(){}db.prototype.tag=function(){return"array"};db.prototype.e=function(a){return a};db.prototype.p=function(){return null};
function eb(){}eb.prototype.tag=function(){return"map"};eb.prototype.e=function(a){return a};eb.prototype.p=function(){return null};function fb(){}fb.prototype.tag=function(){return"t"};fb.prototype.e=function(a){return a.getUTCFullYear()+"-"+X(a.getUTCMonth()+1,2)+"-"+X(a.getUTCDate(),2)+"T"+X(a.getUTCHours(),2)+":"+X(a.getUTCMinutes(),2)+":"+X(a.getUTCSeconds(),2)+"."+X(a.getUTCMilliseconds(),3)+"Z"};fb.prototype.p=function(a,b){return b.e(a)};function gb(){}gb.prototype.tag=function(){return"m"};
gb.prototype.e=function(a){return a.valueOf()};gb.prototype.p=function(a){return a.valueOf().toString()};function hb(){}hb.prototype.tag=function(){return"b"};hb.prototype.e=function(a){return a.D};hb.prototype.p=function(a){return a.D};function ib(){}ib.prototype.tag=function(){return"u"};ib.prototype.e=function(a){return a.toString()};ib.prototype.p=function(a){return a.toString()};function jb(){}jb.prototype.tag=function(){return"r"};jb.prototype.e=function(a){return a.uri};jb.prototype.p=function(a){return a.uri};
function kb(){}kb.prototype.tag=function(){return":"};kb.prototype.e=function(a){return a.name};kb.prototype.p=function(a,b){return b.e(a)};function lb(){}lb.prototype.tag=function(){return"$"};lb.prototype.e=function(a){return a.name};lb.prototype.p=function(a,b){return b.e(a)};function mb(){}mb.prototype.tag=function(){return"'"};mb.prototype.e=function(a){return a.F};mb.prototype.p=function(){return null};function nb(){}nb.prototype.tag=function(a){return a.tag};nb.prototype.e=function(a){return a.e};
nb.prototype.p=function(){return null};function ob(){}ob.prototype.tag=function(){return"set"};ob.prototype.e=function(a){var b=[];a.forEach(function(a){b.push(a)});return S("array",b)};ob.prototype.p=function(){return null};function pb(){}pb.prototype.tag=function(){return"map"};pb.prototype.e=function(a){return a};pb.prototype.p=function(){return null};function qb(){}qb.prototype.tag=function(){return"map"};qb.prototype.e=function(a){return a};qb.prototype.p=function(){return null};
function rb(){}rb.prototype.tag=function(){return"list"};rb.prototype.e=function(a){return S("array",a.V)};rb.prototype.p=function(){return null};
function sb(){this.w={};this.set(null,new Xa);this.set(String,new Ya);this.set(Number,new Za);this.set(l,new $a);this.set(C,new ab);this.set(D,new bb);this.set(Boolean,new cb);this.set(Array,new db);this.set(Object,new eb);this.set(Date,new gb);this.set(H,new hb);this.set(G,new ib);this.set(I,new jb);this.set(E,new kb);this.set(F,new lb);this.set(Q,new mb);this.set(R,new nb);this.set(P,new ob);this.set(M,new pb);this.set(L,new qb);this.set(T,new rb)}sb.prototype.get=function(a){return this.w[Wa(a)]};
sb.prototype.set=function(a,b){this.w[Wa(a)]=b};function tb(a){this.J=a||{};this.S=null!=this.J.preferStrings?this.J.preferStrings:!0;this.da=this.J.objectBuilder||null;this.w=new sb;if(this.J.handlers){var b=this;this.J.handlers.forEach(function(a,d){b.w.set(d,a)})}this.T=this.J.unpack||function(a){return a instanceof M&&null===a.g?a.j:!1};this.U=this.J&&this.J.verbose||!1}function Y(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a}
function ub(a,b,c){var d=[];if(y(b))for(var e=0;e<b.length;e++)d.push(Z(a,b[e],!1,c));else b.forEach(function(b){d.push(Z(a,b,!1,c))});return d}function vb(a,b){if("string"!==typeof b){var c=a.w.get(W(b));return c&&1===c.tag(b).length}return!0}function wb(a,b){var c=a.T(b),d=!0;if(c)for(var e=0;e<c.length&&(d=vb(a,c[e]),d);e+=2);else for(c=b.I(),e=0;e<c.length&&(d=vb(a,c[e]),d);e++);return d}
function xb(a,b,c){if(b.constructor===Object||null!=b.forEach){if(a.U){if(null!=b.forEach)if(wb(a,b)){var d={};b.forEach(function(b,e){d[Z(a,e,!0,!1)]=Z(a,b,!1,c)})}else{var e=a.T(b),f=[],g=Y("~#","cmap","",!0,c);if(e)for(var h=0;h<e.length;h+=2)f.push(Z(a,e[h],!0,!1)),f.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Z(a,d,!0,!1));f.push(Z(a,b,!1,c))});d={};d[g]=f}else for(d={},e=x(b),h=0;h<e.length;h++)d[Z(a,e[h],!0,!1)]=Z(a,b[e[h]],!1,c);return d}if(null!=b.forEach){if(wb(a,b)){e=a.T(b);
d=["^ "];if(e)for(h=0;h<e.length;h+=2)d.push(Z(a,e[h],!0,c)),d.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,e){d.push(Z(a,e,!0,c));d.push(Z(a,b,!1,c))});return d}e=a.T(b);f=[];g=Y("~#","cmap","",!0,c);if(e)for(h=0;h<e.length;h+=2)f.push(Z(a,e[h],!0,c)),f.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Z(a,d,!0,c));f.push(Z(a,b,!1,c))});return[g,f]}d=["^ "];e=x(b);for(h=0;h<e.length;h++)d.push(Z(a,e[h],!0,c)),d.push(Z(a,b[e[h]],!1,c));return d}if(null!=a.da)return a.da(b,function(b){return Z(a,
b,!0,c)},function(b){return Z(a,b,!1,c)});h=Error("Not supported");h.data={F:b,type:W(b).name};throw h;}
function Z(a,b,c,d){var e=a.w.get(W(b)),f=e?e.tag(b):null,g=e?e.e(b):null;if(null!=e&&null!=f)switch(f){case "_":return c?Y("~","_","",c,d):null;case "s":return 0<g.length?(a=g.charAt(0),a="~"===a||"^"===a||"`"===a?"~"+g:g):a=g,Y("","",a,c,d);case "?":return c?Y("~","?",g.toString()[0],c,d):g;case "i":return c||"string"===typeof g||g instanceof l?Y("~","i",g.toString(),c,d):g;case "d":return c?Y(g.ia,"d",g,c,d):g;case "b":return Y("~","b",g,c,d);case "'":return b={},c=Y("~#","'","",!0,d),b[c]=Z(a,
g,!1,d),b;case "array":return ub(a,g,d);case "map":return xb(a,g,d);default:a:{if(1===f.length){if("string"===typeof g){d=Y("~",f,g,c,d);break a}if(c||a.S){(a=a.U&&new fb)?(f=a.tag(b),g=a.p(b,a)):g=e.p(b,e);if(null!==g){d=Y("~",f,g,c,d);break a}d=Error("Cannot be encoded as string");d.data={tag:f,e:g,F:b};throw d;}}b=f;c=g;a.U?(g={},g[Y("~#",b,"",!0,d)]=Z(a,c,!1,d),d=g):d=[Y("~#",b,"",!0,d),Z(a,c,!1,d)]}return d}else throw d=Error("Not supported"),d.data={F:b,type:W(b).name},d;}
function yb(a,b){var c=a.w.get(W(b));if(null!=c)return 1===c.tag(b).length?Ka(b):b;c=Error("Not supported");c.data={F:b,type:W(b).name};throw c;}function $(a,b){this.O=a;this.options=b||{};this.A=!1===this.options.cache?null:this.options.cache?this.options.cache:new Oa}$.prototype.ga=function(){return this.O};$.prototype.marshaller=$.prototype.ga;
$.prototype.write=function(a,b){var c=null,c=b||{};asMapKey=c.asMapKey||!1;cache=this.O.U?!1:this.A;if(!1===c.marshalTop)c=Z(this.O,a,asMapKey,cache);else var c=this.O,d=asMapKey,e=cache,c=JSON.stringify(Z(c,yb(c,a),d,e));null!=this.A&&this.A.clear();return c};$.prototype.write=$.prototype.write;$.prototype.register=function(a,b){this.O.w.set(a,b)};$.prototype.register=$.prototype.register;k("transit.reader",function(a,b){if("json"===a||"json-verbose"===a||null==a){var c=new Ta(b);return new Ua(c,b)}throw Error("Cannot create reader of type "+a);});k("transit.writer",function(a,b){if("json"===a||"json-verbose"===a||null==a){"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0);var c=new tb(b);return new $(c,b)}c=Error('Type must be "json"');c.data={type:a};throw c;});k("transit.makeBuilder",function(a){function b(){}b.prototype.Z=a.init;b.prototype.add=a.add;b.prototype.X=a.finalize;return new b});
k("transit.makeWriteHandler",function(a){function b(){}b.prototype.tag=a.tag;b.prototype.e=a.rep;b.prototype.p=a.stringRep;return new b});k("transit.date",Ca);k("transit.integer",va);k("transit.isInteger",function(a){return a instanceof l});k("transit.uuid",function(a){return Ba(a)});k("transit.isUUID",function(a){return a instanceof G});k("transit.bigInt",wa);k("transit.isBigInt",function(a){return a instanceof C});k("transit.bigDec",xa);k("transit.isBigDec",function(a){return a instanceof D});
k("transit.keyword",ya);k("transit.isKeyword",function(a){return a instanceof E});k("transit.symbol",za);k("transit.isSymbol",function(a){return a instanceof F});k("transit.binary",Da);k("transit.isBinary",function(a){return a instanceof H});k("transit.uri",Ea);k("transit.isURI",function(a){return a instanceof I});k("transit.map",O);k("transit.isMap",function(a){return a instanceof M||a instanceof L});k("transit.set",Ja);k("transit.isSet",function(a){return a instanceof P});k("transit.list",La);
k("transit.isList",function(a){return a instanceof T});k("transit.quoted",Ka);k("transit.isQuoted",function(a){return a instanceof sa.ja});k("transit.tagged",S);k("transit.isTaggedValue",sa.ka);k("transit.link",function(a){return new U(a)});k("transit.isLink",function(a){return a instanceof U});k("transit.hash",B);k("transit.hashMapLike",qa);k("transit.hashArrayLike",ra);k("transit.equals",z);k("transit.extendToEQ",function(a,b){a.v=b.hashCode;a.s=b.equals;return a});
k("transit.mapToObject",function(a){var b={};a.forEach(function(a,d){if("string"!==typeof d)throw Error("Cannot convert map with non-string keys");b[d]=a});return b});k("transit.decoder",function(a){return new V(a)});k("transit.UUIDfromString",Ba);k("transit.randomUUID",sa.la);k("transit.stringableKeys",wb);})();
