// transit-js 0.8.609
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){var aa=this;
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function k(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};function l(a,b){this.h=a|0;this.e=b|0}var ca={};function m(a){if(-128<=a&&128>a){var b=ca[a];if(b)return b}b=new l(a|0,0>a?-1:0);-128<=a&&128>a&&(ca[a]=b);return b}function n(a){return isNaN(a)||!isFinite(a)?p:a<=-da?q:a+1>=da?ea:0>a?r(n(-a)):new l(a%s|0,a/s|0)}function u(a,b){return new l(a,b)}
function v(a,b){if(0==a.length)throw Error("number format error: empty string");var c=b||10;if(2>c||36<c)throw Error("radix out of range: "+c);if("-"==a.charAt(0))return r(v(a.substring(1),c));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var d=n(Math.pow(c,8)),e=p,f=0;f<a.length;f+=8){var g=Math.min(8,a.length-f),h=parseInt(a.substring(f,f+g),c);8>g?(g=n(Math.pow(c,g)),e=e.multiply(g).add(n(h))):(e=e.multiply(d),e=e.add(n(h)))}return e}
var s=4294967296,da=s*s/2,p=m(0),w=m(1),fa=m(-1),ea=u(-1,2147483647),q=u(0,-2147483648),ga=m(16777216);function x(a){return a.e*s+(0<=a.h?a.h:s+a.h)}
l.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(y(this))return"0";if(0>this.e){if(z(this,q)){var b=n(a),c=A(this,b),b=B(c.multiply(b),this);return c.toString(a)+b.h.toString(a)}return"-"+r(this).toString(a)}for(var c=n(Math.pow(a,6)),b=this,d="";;){var e=A(b,c),f=B(b,e.multiply(c)).h.toString(a),b=e;if(y(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function y(a){return 0==a.e&&0==a.h}function z(a,b){return a.e==b.e&&a.h==b.h}
l.prototype.compare=function(a){if(z(this,a))return 0;var b=0>this.e,c=0>a.e;return b&&!c?-1:!b&&c?1:0>B(this,a).e?-1:1};function r(a){return z(a,q)?q:u(~a.h,~a.e).add(w)}l.prototype.add=function(a){var b=this.e>>>16,c=this.e&65535,d=this.h>>>16,e=a.e>>>16,f=a.e&65535,g=a.h>>>16,h;h=0+((this.h&65535)+(a.h&65535));a=0+(h>>>16);a+=d+g;d=0+(a>>>16);d+=c+f;c=0+(d>>>16);c=c+(b+e)&65535;return u((a&65535)<<16|h&65535,c<<16|d&65535)};function B(a,b){return a.add(r(b))}
l.prototype.multiply=function(a){if(y(this)||y(a))return p;if(z(this,q))return 1==(a.h&1)?q:p;if(z(a,q))return 1==(this.h&1)?q:p;if(0>this.e)return 0>a.e?r(this).multiply(r(a)):r(r(this).multiply(a));if(0>a.e)return r(this.multiply(r(a)));if(0>this.compare(ga)&&0>a.compare(ga))return n(x(this)*x(a));var b=this.e>>>16,c=this.e&65535,d=this.h>>>16,e=this.h&65535,f=a.e>>>16,g=a.e&65535,h=a.h>>>16;a=a.h&65535;var I,t,C,sa;sa=0+e*a;C=0+(sa>>>16);C+=d*a;t=0+(C>>>16);C=(C&65535)+e*h;t+=C>>>16;C&=65535;t+=
c*a;I=0+(t>>>16);t=(t&65535)+d*h;I+=t>>>16;t&=65535;t+=e*g;I+=t>>>16;t&=65535;I=I+(b*a+c*h+d*g+e*f)&65535;return u(C<<16|sa&65535,I<<16|t)};
function A(a,b){if(y(b))throw Error("division by zero");if(y(a))return p;if(z(a,q)){if(z(b,w)||z(b,fa))return q;if(z(b,q))return w;var c;c=1;if(0==c)c=a;else{var d=a.e;c=32>c?u(a.h>>>c|d<<32-c,d>>c):u(d>>c-32,0<=d?0:-1)}c=A(c,b).shiftLeft(1);if(z(c,p))return 0>b.e?w:fa;d=B(a,b.multiply(c));return c.add(A(d,b))}if(z(b,q))return p;if(0>a.e)return 0>b.e?A(r(a),r(b)):r(A(r(a),b));if(0>b.e)return r(A(a,r(b)));for(var e=p,d=a;0<=d.compare(b);){c=Math.max(1,Math.floor(x(d)/x(b)));for(var f=Math.ceil(Math.log(c)/
Math.LN2),f=48>=f?1:Math.pow(2,f-48),g=n(c),h=g.multiply(b);0>h.e||0<h.compare(d);)c-=f,g=n(c),h=g.multiply(b);y(g)&&(g=w);e=e.add(g);d=B(d,h)}return e}l.prototype.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.h;return 32>a?u(b<<a,this.e<<a|b>>>32-a):u(0,b<<a-32)};function ha(a,b){b&=63;if(0==b)return a;var c=a.e;return 32>b?u(a.h>>>b|c<<32-b,c>>>b):32==b?u(c,0):u(c>>>b-32,0)};var D="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},E="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===ba(a)};function F(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(E(a)){if(E(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!F(a[c],b[c]))return!1;return!0}return!1}if(a.s)return a.s(b);if(null!=b&&"object"===typeof b){if(b.s)return b.s(a);var d=c=0,e=D(b).length,f;for(f in a)if(a.hasOwnProperty(f))if(d++,"$com$cognitect$transit$hashCode$"==f)b[f]||(c=-1);else if(!b.hasOwnProperty(f)||!F(a[f],b[f]))return!1;return d+c===e}}return!1}
function ia(a,b){return a^b+2654435769+(a<<6)+(a>>2)}var ja={},ka=0;function G(a){var b=0;if(null!=a.forEach)a.forEach(function(a,c){b=(b+(H(c)^H(a)))%4503599627370496});else for(var c=D(a),d=0;d<c.length;d++){var e=c[d];if("$com$cognitect$transit$hashCode$"!==e)var f=a[e],b=(b+(H(e)^H(f)))%4503599627370496}return b}
function la(a){var b=a.$com$cognitect$transit$hashCode$||0;if(0===b)if(E(a)){for(var c=0;c<a.length;c++)b=ia(b,H(a[c]));a.$com$cognitect$transit$hashCode$=b}else a.forEach&&a.forEach(function(a){b=ia(b,H(a))});return b}
function H(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":var b=ja[a];if(null==b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;ka++;256<=ka&&(ja={},ka=1);ja[a]=b}a=b;return a;default:return a instanceof Date?a.valueOf():E(a)?la(a):a.A?a.A():a.$com$cognitect$transit$hashCode$?a.$com$cognitect$transit$hashCode$:G(a)}};var ma={};function J(a,b){this.tag=a;this.rep=b;this.l=-1}J.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};J.prototype.B=function(a){return F(this,a)};J.prototype.equiv=J.prototype.B;J.prototype.s=function(a){return a instanceof J?this.tag===a.tag&&F(this.rep,a.rep):!1};J.prototype.A=function(){-1===this.l&&(this.l=ia(H(this.tag),H(this.rep)));return this.l};function K(a,b){return new J(a,b)}var na=v("9007199254740992"),oa=v("-9007199254740992");
function pa(a){if("number"===typeof a||a instanceof l)return a;a=v(a,10);return 0<a.compare(na)||0>a.compare(oa)?a:x(a)}l.prototype.B=function(a){return F(this,a)};l.prototype.equiv=l.prototype.B;l.prototype.s=function(a){return a instanceof l&&z(this,a)};l.prototype.A=function(){return this.h};function qa(a){return K("n",a)}function ra(a){return K("f",a)}function L(a){this.name=a;this.l=-1}L.prototype.toString=function(){return":"+this.name};L.prototype.B=function(a){return F(this,a)};
L.prototype.equiv=L.prototype.B;L.prototype.s=function(a){return a instanceof L&&this.name==a.name};L.prototype.A=function(){-1===this.l&&(this.l=H(this.name));return this.l};function ta(a){return new L(a)}function M(a){this.name=a;this.l=-1}M.prototype.toString=function(){return"[Symbol: "+this.name+"]"};M.prototype.B=function(a){return F(this,a)};M.prototype.equiv=M.prototype.B;M.prototype.s=function(a){return a instanceof M&&this.name==a.name};
M.prototype.A=function(){-1===this.l&&(this.l=H(this.name));return this.l};function ua(a){return new M(a)}function N(a,b,c){var d="";c=c||b+1;for(var e=8*(7-b),f=m(255).shiftLeft(e);b<c;b++,e-=8,f=ha(f,8)){var g=ha(u(a.h&f.h,a.e&f.e),e).toString(16);1==g.length&&(g="0"+g);d+=g}return d}function O(a,b){this.V=a;this.X=b;this.l=-1}O.prototype.toString=function(a){var b=this.V,c=this.X;a=""+(N(b,0,4)+"-");a+=N(b,4,6)+"-";a+=N(b,6,8)+"-";a+=N(c,0,2)+"-";return a+=N(c,2,8)};
O.prototype.B=function(a){return F(this,a)};O.prototype.equiv=O.prototype.B;O.prototype.s=function(a){return a instanceof O&&z(this.V,a.V)&&z(this.X,a.X)};
function va(a){a=a.replace(/-/g,"");for(var b=null,c=null,d=c=0,e=24,f=0,f=c=0,e=24;8>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;f=8;for(e=24;16>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;b=u(d,c);c=0;f=16;for(e=24;24>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;for(e=f=24;32>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;c=u(d,c);return new O(b,c)}function wa(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)}
Date.prototype.s=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.A=function(){return this.valueOf()};function xa(a){return K("b",a)}function ya(a){return K("r",a)}function P(a,b){this.v=a;this.type=b||0;this.k=0}P.prototype.next=function(){if(this.k<this.v.length){var a=null,a=0===this.type?this.v[this.k]:1===this.type?this.v[this.k+1]:[this.v[this.k],this.v[this.k+1]],a={value:a,done:!1};this.k+=2;return a}return{value:null,done:!0}};P.prototype.next=P.prototype.next;
function Q(a,b){this.map=a;this.type=b||0;this.keys=za(this.map);this.k=0;this.G=null;this.C=0}Q.prototype.next=function(){if(this.k<this.map.size){null!=this.G&&this.C<this.G.length||(this.G=this.map.map[this.keys[this.k]],this.C=0);var a=null,a=0===this.type?this.G[this.C]:1===this.type?this.G[this.C+1]:[this.G[this.C],this.G[this.C+1]],a={value:a,done:!1};this.k++;this.C+=2;return a}return{value:null,done:!0}};Q.prototype.next=Q.prototype.next;
function Aa(a,b){if((b instanceof R||b instanceof S)&&a.size===b.size){for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!F(d[e+1],b.get(d[e])))return!1;return!0}if(null!=b&&"object"===typeof b&&(c=D(b).length-(b.hasOwnProperty("$com$cognitect$transit$hashCode$")&&1||0),a.size===c)){for(d in b)if("$com$cognitect$transit$hashCode$"!==d&&!F(b[d],a.get(d)))return!1;return!0}return!1}function S(a){this.g=a;this.a=null;this.l=-1;this.size=a.length/2;this.aa=0}S.prototype.toString=function(){return"[TransitArrayMap]"};
function Ba(a){if(a.a)throw Error("Invalid operation, already converted");if(8>a.size)return!1;a.aa++;return 32<a.aa?(a.a=T(a.g,!1,!0),a.g=[],!0):!1}S.prototype.clear=function(){this.a?this.a.clear():this.g=[];this.size=0};S.prototype.clear=S.prototype.clear;S.prototype.keys=function(){return this.a?this.a.keys():new P(this.g,0)};S.prototype.keys=S.prototype.keys;S.prototype.H=function(){if(this.a)return this.a.H();for(var a=[],b=0,c=0;c<this.g.length;b++,c+=2)a[b]=this.g[c];return a};
S.prototype.keySet=S.prototype.H;S.prototype.v=function(){return this.a?this.a.v():new P(this.g,2)};S.prototype.entries=S.prototype.v;S.prototype.I=function(){return this.a?this.a.I():new P(this.g,1)};S.prototype.values=S.prototype.I;S.prototype.forEach=function(a){if(this.a)this.a.forEach(a);else for(var b=0;b<this.g.length;b+=2)a(this.g[b+1],this.g[b])};S.prototype.forEach=S.prototype.forEach;
S.prototype.get=function(a){if(this.a)return this.a.get(a);if(Ba(this))return this.get(a);for(var b=0;b<this.g.length;b+=2)if(F(this.g[b],a))return this.g[b+1];return null};S.prototype.get=S.prototype.get;S.prototype.D=function(a){if(this.a)return this.a.D(a);if(Ba(this))return this.D(a);for(var b=0;b<this.g.length;b+=2)if(F(this.g[b],a))return!0;return!1};S.prototype.has=S.prototype.D;
S.prototype.set=function(a,b){if(this.a)this.a.set(a,b),this.size=this.a.size;else{for(var c=0;c<this.g.length;c+=2)if(F(this.g[c],a)){this.g[c+1]=b;return}this.g.push(a);this.g.push(b);this.size++;32<this.size&&(this.a=T(this.g,!1,!0),this.g=null)}};S.prototype.set=S.prototype.set;S.prototype["delete"]=function(a){if(this.a)this.a["delete"](a),this.size=this.a.size;else for(var b=0;b<this.g.length;b+=2)if(F(this.g[b],a)){this.g.splice(b,2);this.size--;break}};
S.prototype.A=function(){if(this.a)return this.a.A();-1===this.l&&(this.l=G(this));return this.l};S.prototype.s=function(a){return this.a?Aa(this.a,a):Aa(this,a)};function R(a,b,c){this.map=b||{};this.J=a||[];this.size=c||0;this.l=-1}R.prototype.toString=function(){return"[TransitMap]"};R.prototype.clear=function(){this.map={};this.J=[];this.size=0;this.l=-1};R.prototype.clear=R.prototype.clear;function za(a){return null!=a.J?a.J:D(a.map)}
R.prototype["delete"]=function(a){this.J=null;for(var b=H(a),c=this.map[b],d=0;d<c.length;d+=2)if(F(a,c[d])){c.splice(d,2);0===c.length&&delete this.map[b];this.size--;break}};R.prototype.v=function(){return new Q(this,2)};R.prototype.entries=R.prototype.v;R.prototype.forEach=function(a){for(var b=za(this),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};R.prototype.forEach=R.prototype.forEach;
R.prototype.get=function(a){var b=H(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2){if(F(a,b[c]))return b[c+1]}else return null};R.prototype.get=R.prototype.get;R.prototype.D=function(a){var b=H(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2)if(F(a,b[c]))return!0;return!1};R.prototype.has=R.prototype.D;R.prototype.keys=function(){return new Q(this,0)};R.prototype.keys=R.prototype.keys;
R.prototype.H=function(){for(var a=za(this),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};R.prototype.keySet=R.prototype.H;R.prototype.set=function(a,b){var c=H(a),d=this.map[c];if(null==d)this.J&&this.J.push(c),this.map[c]=[a,b],this.size++;else{for(var c=!0,e=0;e<d.length;e+=2)if(F(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};R.prototype.set=R.prototype.set;R.prototype.I=function(){return new Q(this,1)};R.prototype.values=R.prototype.I;
R.prototype.A=function(){-1===this.l&&(this.l=G(this));return this.l};R.prototype.s=function(a){return Aa(this,a)};
function T(a,b,c){a=a||[];b=!1===b?b:!0;if((!0!==c||!c)&&64>=a.length){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(F(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new S(a)}var d={},e=[],f=0;for(b=0;b<a.length;b+=2){c=H(a[b]);var g=d[c];if(null==g)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var h=!0;for(c=0;c<g.length;c+=2)if(F(g[c],a[b])){g[c+1]=a[b+1];h=!1;break}h&&(g.push(a[b]),g.push(a[b+1]),f++)}}return new R(e,d,f)}
function U(a){this.map=a;this.size=a.size}U.prototype.toString=function(){return"[TransitSet]"};U.prototype.add=function(){throw Error("Unsupported operation: add");};U.prototype.add=U.prototype.add;U.prototype.clear=function(){this.map=new R;this.size=0};U.prototype.clear=U.prototype.clear;U.prototype["delete"]=function(a){this.map["delete"](a);this.size=this.map.size};U.prototype.v=function(){return this.map.v()};U.prototype.entries=U.prototype.v;
U.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};U.prototype.forEach=U.prototype.forEach;U.prototype.D=function(a){return this.map.D(a)};U.prototype.has=U.prototype.D;U.prototype.keys=function(){return this.map.keys()};U.prototype.keys=U.prototype.keys;U.prototype.H=function(){return this.map.H()};U.prototype.keySet=U.prototype.H;U.prototype.I=function(){return this.map.I()};U.prototype.values=U.prototype.I;
U.prototype.s=function(a){if(a instanceof U){if(this.size===a.size)return F(this.map,a.map)}else return!1};U.prototype.A=function(){return H(this.map)};function Ca(a){for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=H(a[e]),g=b[f];if(null==g)c.push(f),b[f]=[a[e],a[e]],d++;else{for(var f=!0,h=0;h<g.length;h+=2)if(F(g[h],a[e])){f=!1;break}f&&(g.push(a[e]),g.push(a[e]),d++)}}return new U(new R(c,b,d))}function Da(a){return K("'",a)}function Ea(a){return K("list",a)}function Fa(a){return K("link",a)};function Ga(a,b){if(3<a.length){if(b)return!0;var c=a.charAt(1);return"~"===a.charAt(0)?":"===c||"$"===c||"#"===c:!1}return!1}function Ha(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return 0===b?"^"+a:"^"+String.fromCharCode(b+48)+a}function Ia(){this.ca=this.N=this.k=0;this.q={}}
Ia.prototype.write=function(a,b){if(Ga(a,b)){4096===this.ca?(this.clear(),this.N=0,this.q={}):1936===this.k&&this.clear();var c=this.q[a];return null==c?(this.q[a]=[Ha(this.k),this.N],this.k++,a):c[1]!=this.N?(c[1]=this.N,c[0]=Ha(this.k),this.k++,a):c[0]}return a};Ia.prototype.clear=function(){this.k=0;this.N++};function Ja(){this.k=0;this.q=[]}Ja.prototype.write=function(a){1936==this.k&&(this.k=0);this.q[this.k]=a;this.k++;return a};
Ja.prototype.Z=function(a){return this.q[2===a.length?a.charCodeAt(1)-48:44*(a.charCodeAt(1)-48)+(a.charCodeAt(2)-48)]};Ja.prototype.clear=function(){this.k=0};function Ka(a){this.R=a}
function V(a){this.options=a||{};this.p={};for(var b in this.P.p)this.p[b]=this.P.p[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error("Cannot override handler for ground types");this.p[b]=this.options.handlers[b]}this.Q=null!=this.options.preferStrings?this.options.preferStrings:this.P.Q;this.T=this.options.defaultHandler||this.P.T;this.w=this.options.mapBuilder;this.K=this.options.arrayBuilder}
V.prototype.P={p:{_:function(){return null},"?":function(a){return"t"===a},b:function(a){return xa(a)},i:function(a){return pa(a)},n:function(a){return qa(a)},d:function(a){return parseFloat(a)},f:function(a){return ra(a)},c:function(a){return a},":":function(a){return ta(a)},$:function(a){return ua(a)},r:function(a){return ya(a)},"'":function(a){return a},m:function(a){return wa(a)},t:function(a){return new Date(a)},u:function(a){return va(a)},set:function(a){return Ca(a)},list:function(a){return Ea(a)},
link:function(a){return Fa(a)},cmap:function(a){return T(a,!1)}},T:function(a,b){return K(a,b)},Q:!0};
V.prototype.j=function(a,b,c,d){if(null==a)return null;switch(typeof a){case "string":return Ga(a,c)?(a=La(this,a),b&&b.write(a,c),b=a):b="^"===a.charAt(0)?b.Z(a,c):La(this,a),b;case "object":if(E(a))if("^ "===a[0])if(this.w)if(17>a.length&&this.w.M){d=[];for(c=1;c<a.length;c+=2)d.push(this.j(a[c],b,!0,!1)),d.push(this.j(a[c+1],b,!1,!1));b=this.w.M(d)}else{d=this.w.W();for(c=1;c<a.length;c+=2)d=this.w.add(d,this.j(a[c],b,!0,!1),this.j(a[c+1],b,!1,!1));b=this.w.U(d)}else{d=[];for(c=1;c<a.length;c+=
2)d.push(this.j(a[c],b,!0,!1)),d.push(this.j(a[c+1],b,!1,!1));b=T(d,!1)}else b=Ma(this,a,b,d);else{c=D(a);var e=c[0];if((d=1==c.length?this.j(e,b,!1,!1):null)&&d instanceof Ka)a=a[e],c=this.p[d.R],b=null!=c?c(this.j(a,b,!1,!0)):K(d.R,this.j(a,b,!1,!1));else if(this.w)if(16>c.length&&this.w.M){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.j(e,b,!0,!1)),f.push(this.j(a[e],b,!1,!1));b=this.w.M(f)}else{f=this.w.W();for(d=0;d<c.length;d++)e=c[d],f=this.w.add(f,this.j(e,b,!0,!1),this.j(a[e],b,!1,!1));
b=this.w.U(f)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.j(e,b,!0,!1)),f.push(this.j(a[e],b,!1,!1));b=T(f,!1)}}return b}return a};V.prototype.decode=V.prototype.j;
function Ma(a,b,c,d){if(d){var e=[];for(d=0;d<b.length;d++)e.push(a.j(b[d],c,!1,!1));return e}if(2===b.length&&"string"===typeof b[0]&&(d=a.j(b[0],c,!1,!1))&&d instanceof Ka)return b=b[1],e=a.p[d.R],null!=e?e=e(a.j(b,c,!1,!0)):K(d.R,a.j(b,c,!1,!1));if(a.K){if(32>=b.length&&a.K.M){e=[];for(d=0;d<b.length;d++)e.push(a.j(b[d],c,!1,!1));return a.K.M(e)}e=a.K.W();for(d=0;d<b.length;d++)e=a.K.add(e,a.j(b[d],c,!1,!1));return a.K.U(e)}e=[];for(d=0;d<b.length;d++)e.push(a.j(b[d],c,!1,!1));return e}
function La(a,b){if("~"===b.charAt(0)){var c=b.charAt(1);if("~"===c||"^"===c||"`"===c)return b.substring(1);if("#"===c)return new Ka(b.substring(2));var d=a.p[c];return null==d?a.T(c,b.substring(2)):d(b.substring(2))}return b};function Na(a){this.da=new V(a)}function Oa(a,b){this.fa=a;this.options=b||{};this.q=this.options.cache?this.options.cache:new Ja}Oa.prototype.Z=function(a){var b=this.q;a=this.fa.da.j(JSON.parse(a),b);this.q.clear();return a};Oa.prototype.read=Oa.prototype.Z;var Pa=0;function Qa(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a.com$cognitect$transit$ctor$guid;null==b&&(a.com$cognitect$transit$ctor$guid=b=++Pa);return b}function W(a){return null==a?null:a.constructor}function X(a,b){for(var c=a.toString(),d=c.length;d<b;d++)c="0"+c;return c}function Ra(){}Ra.prototype.tag=function(){return"_"};Ra.prototype.rep=function(){return null};
Ra.prototype.o=function(){return"null"};function Sa(){}Sa.prototype.tag=function(){return"s"};Sa.prototype.rep=function(a){return a};Sa.prototype.o=function(a){return a};function Ta(){}Ta.prototype.tag=function(){return"i"};Ta.prototype.rep=function(a){return a};Ta.prototype.o=function(a){return a.toString()};function Ua(){}Ua.prototype.tag=function(){return"i"};Ua.prototype.rep=function(a){return a.toString()};Ua.prototype.o=function(a){return a.toString()};function Va(){}Va.prototype.tag=function(){return"?"};
Va.prototype.rep=function(a){return a};Va.prototype.o=function(a){return a.toString()};function Wa(){}Wa.prototype.tag=function(){return"array"};Wa.prototype.rep=function(a){return a};Wa.prototype.o=function(){return null};function Xa(){}Xa.prototype.tag=function(){return"map"};Xa.prototype.rep=function(a){return a};Xa.prototype.o=function(){return null};function Ya(){}Ya.prototype.tag=function(){return"t"};
Ya.prototype.rep=function(a){return a.getUTCFullYear()+"-"+X(a.getUTCMonth()+1,2)+"-"+X(a.getUTCDate(),2)+"T"+X(a.getUTCHours(),2)+":"+X(a.getUTCMinutes(),2)+":"+X(a.getUTCSeconds(),2)+"."+X(a.getUTCMilliseconds(),3)+"Z"};Ya.prototype.o=function(a,b){return b.rep(a)};function Za(){}Za.prototype.tag=function(){return"m"};Za.prototype.rep=function(a){return a.valueOf()};Za.prototype.o=function(a){return a.valueOf().toString()};function $a(){}$a.prototype.tag=function(){return"u"};$a.prototype.rep=function(a){return a.toString()};
$a.prototype.o=function(a){return a.toString()};function ab(){}ab.prototype.tag=function(){return":"};ab.prototype.rep=function(a){return a.name};ab.prototype.o=function(a,b){return b.rep(a)};function bb(){}bb.prototype.tag=function(){return"$"};bb.prototype.rep=function(a){return a.name};bb.prototype.o=function(a,b){return b.rep(a)};function cb(){}cb.prototype.tag=function(a){return a.tag};cb.prototype.rep=function(a){return a.rep};cb.prototype.o=function(){return null};function db(){}
db.prototype.tag=function(){return"set"};db.prototype.rep=function(a){var b=[];a.forEach(function(a){b.push(a)});return K("array",b)};db.prototype.o=function(){return null};function eb(){}eb.prototype.tag=function(){return"map"};eb.prototype.rep=function(a){return a};eb.prototype.o=function(){return null};function fb(){}fb.prototype.tag=function(){return"map"};fb.prototype.rep=function(a){return a};fb.prototype.o=function(){return null};
function gb(){this.p={};this.set(null,new Ra);this.set(String,new Sa);this.set(Number,new Ta);this.set(l,new Ua);this.set(Boolean,new Va);this.set(Array,new Wa);this.set(Object,new Xa);this.set(Date,new Za);this.set(O,new $a);this.set(L,new ab);this.set(M,new bb);this.set(J,new cb);this.set(U,new db);this.set(S,new eb);this.set(R,new fb)}gb.prototype.get=function(a){return this.p[Qa(a)]};gb.prototype.set=function(a,b){this.p[Qa(a)]=b};function hb(a){this.F=a||{};this.Q=null!=this.F.preferStrings?this.F.preferStrings:!0;this.ba=this.F.objectBuilder||null;this.p=new gb;if(this.F.handlers){var b=this;this.F.handlers.forEach(function(a,d){b.p.set(d,a)})}this.S=this.F.unpack||function(a){return a instanceof S&&null===a.a?a.g:!1};this.O=this.F&&this.F.verbose||!1}function Y(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a}
function ib(a,b,c){var d=[];if(E(b))for(var e=0;e<b.length;e++)d.push(Z(a,b[e],!1,c));else b.forEach(function(b){d.push(Z(a,b,!1,c))});return d}function jb(a,b){if("string"!==typeof b){var c=a.p.get(W(b));return c&&1===c.tag(b).length}return!0}function kb(a,b){var c=a.S(b),d=!0;if(c)for(var e=0;e<c.length&&(d=jb(a,c[e]),d);e+=2);else for(c=b.keys(),step=c.next();!step.done;){d=jb(a,step.value);if(!d)break;step=c.next()}return d}
function lb(a,b,c){if(b.constructor===Object||null!=b.forEach){if(a.O){if(null!=b.forEach)if(kb(a,b)){var d={};b.forEach(function(b,e){d[Z(a,e,!0,!1)]=Z(a,b,!1,c)})}else{var e=a.S(b),f=[],g=Y("~#","cmap","",!0,c);if(e)for(var h=0;h<e.length;h+=2)f.push(Z(a,e[h],!0,!1)),f.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Z(a,d,!0,!1));f.push(Z(a,b,!1,c))});d={};d[g]=f}else for(d={},e=D(b),h=0;h<e.length;h++)d[Z(a,e[h],!0,!1)]=Z(a,b[e[h]],!1,c);return d}if(null!=b.forEach){if(kb(a,b)){e=a.S(b);
d=["^ "];if(e)for(h=0;h<e.length;h+=2)d.push(Z(a,e[h],!0,c)),d.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,e){d.push(Z(a,e,!0,c));d.push(Z(a,b,!1,c))});return d}e=a.S(b);f=[];g=Y("~#","cmap","",!0,c);if(e)for(h=0;h<e.length;h+=2)f.push(Z(a,e[h],!0,c)),f.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Z(a,d,!0,c));f.push(Z(a,b,!1,c))});return[g,f]}d=["^ "];e=D(b);for(h=0;h<e.length;h++)d.push(Z(a,e[h],!0,c)),d.push(Z(a,b[e[h]],!1,c));return d}if(null!=a.ba)return a.ba(b,function(b){return Z(a,
b,!0,c)},function(b){return Z(a,b,!1,c)});h=Error("Not supported");h.data={Y:b,type:W(b).name};throw h;}
function Z(a,b,c,d){var e=a.p.get(W(b)),f=e?e.tag(b):null,g=e?e.rep(b):null;if(null!=e&&null!=f)switch(f){case "_":return c?Y("~","_","",c,d):null;case "s":return 0<g.length?(a=g.charAt(0),a="~"===a||"^"===a||"`"===a?"~"+g:g):a=g,Y("","",a,c,d);case "?":return c?Y("~","?",g.toString()[0],c,d):g;case "i":return c||"string"===typeof g||g instanceof l?Y("~","i",g.toString(),c,d):g;case "d":return c?Y(g.ga,"d",g,c,d):g;case "b":return Y("~","b",g,c,d);case "'":return a.O?(b={},c=Y("~#","'","",!0,d),b[c]=
Z(a,g,!1,d),d=b):d=["^ ",Y("~#","'","",!0,d),Z(a,g,!1,d)],d;case "array":return ib(a,g,d);case "map":return lb(a,g,d);default:a:{if(1===f.length){if("string"===typeof g){d=Y("~",f,g,c,d);break a}if(c||a.Q){(a=a.O&&new Ya)?(f=a.tag(b),g=a.o(b,a)):g=e.o(b,e);if(null!==g){d=Y("~",f,g,c,d);break a}d=Error("Cannot be encoded as string");d.data={tag:f,rep:g,Y:b};throw d;}}b=f;c=g;a.O?(g={},g[Y("~#",b,"",!0,d)]=Z(a,c,!1,d),d=g):d=[Y("~#",b,"",!0,d),Z(a,c,!1,d)]}return d}else throw d=Error("Not supported"),
d.data={Y:b,type:W(b).name},d;}function mb(a,b){var c=a.p.get(W(b));if(null!=c)return 1===c.tag(b).length?Da(b):b;c=Error("Not supported");c.data={Y:b,type:W(b).name};throw c;}function $(a,b){this.L=a;this.options=b||{};this.q=!1===this.options.cache?null:this.options.cache?this.options.cache:new Ia}$.prototype.ea=function(){return this.L};$.prototype.marshaller=$.prototype.ea;
$.prototype.write=function(a,b){var c=null,c=b||{};asMapKey=c.asMapKey||!1;cache=this.L.O?!1:this.q;if(!1===c.marshalTop)c=Z(this.L,a,asMapKey,cache);else var c=this.L,d=asMapKey,e=cache,c=JSON.stringify(Z(c,mb(c,a),d,e));null!=this.q&&this.q.clear();return c};$.prototype.write=$.prototype.write;$.prototype.register=function(a,b){this.L.p.set(a,b)};$.prototype.register=$.prototype.register;k("transit.reader",function(a,b){if("json"===a||"json-verbose"===a||null==a){var c=new Na(b);return new Oa(c,b)}throw Error("Cannot create reader of type "+a);});k("transit.writer",function(a,b){if("json"===a||"json-verbose"===a||null==a){"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0);var c=new hb(b);return new $(c,b)}c=Error('Type must be "json"');c.data={type:a};throw c;});k("transit.makeBuilder",function(a){function b(){}b.prototype.W=a.init;b.prototype.add=a.add;b.prototype.U=a.finalize;return new b});
k("transit.makeWriteHandler",function(a){function b(){}b.prototype.tag=a.tag;b.prototype.rep=a.rep;b.prototype.o=a.stringRep;return new b});k("transit.date",wa);k("transit.integer",pa);k("transit.isInteger",function(a){return a instanceof l});k("transit.uuid",function(a){return va(a)});k("transit.isUUID",function(a){return a instanceof O});k("transit.bigInt",qa);k("transit.isBigInt",function(a){return a instanceof K&&"n"===a.tag});k("transit.bigDec",ra);
k("transit.isBigDec",function(a){return a instanceof J&&"f"===a.tag});k("transit.keyword",ta);k("transit.isKeyword",function(a){return a instanceof L});k("transit.symbol",ua);k("transit.isSymbol",function(a){return a instanceof M});k("transit.binary",xa);k("transit.isBinary",function(a){return a instanceof J&&"b"===a.tag});k("transit.uri",ya);k("transit.isURI",function(a){return a instanceof J&&"r"===a.tag});k("transit.map",T);k("transit.isMap",function(a){return a instanceof S||a instanceof R});
k("transit.set",Ca);k("transit.isSet",function(a){return a instanceof U});k("transit.list",Ea);k("transit.isList",function(a){return a instanceof ma.ha&&"list"===a.tag});k("transit.quoted",Da);k("transit.isQuoted",function(a){return a instanceof J&&"'"===a.tag});k("transit.tagged",K);k("transit.isTaggedValue",ma.ia);k("transit.link",Fa);k("transit.isLink",function(a){return a instanceof J&&"link"===a.tag});k("transit.hash",H);k("transit.hashKey","$com$cognitect$transit$hashCode$");
k("transit.hashMapLike",G);k("transit.hashArrayLike",la);k("transit.equals",F);k("transit.extendToEQ",function(a,b){a.A=b.hashCode;a.s=b.equals;return a});k("transit.mapToObject",function(a){var b={};a.forEach(function(a,d){if("string"!==typeof d)throw Error("Cannot convert map with non-string keys");b[d]=a});return b});k("transit.decoder",function(a){return new V(a)});k("transit.UUIDfromString",va);k("transit.randomUUID",ma.ja);k("transit.stringableKeys",kb);})();
