// transit-js 0.8.654
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){var aa=this;
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function k(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};function l(a,b){this.h=a|0;this.e=b|0}var ca={};function m(a){if(-128<=a&&128>a){var b=ca[a];if(b)return b}b=new l(a|0,0>a?-1:0);-128<=a&&128>a&&(ca[a]=b);return b}function n(a){return isNaN(a)||!isFinite(a)?p:a<=-da?q:a+1>=da?ea:0>a?r(n(-a)):new l(a%s|0,a/s|0)}function u(a,b){return new l(a,b)}
function v(a,b){if(0==a.length)throw Error("number format error: empty string");var c=b||10;if(2>c||36<c)throw Error("radix out of range: "+c);if("-"==a.charAt(0))return r(v(a.substring(1),c));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var d=n(Math.pow(c,8)),e=p,f=0;f<a.length;f+=8){var g=Math.min(8,a.length-f),h=parseInt(a.substring(f,f+g),c);8>g?(g=n(Math.pow(c,g)),e=e.multiply(g).add(n(h))):(e=e.multiply(d),e=e.add(n(h)))}return e}
var s=4294967296,da=s*s/2,p=m(0),w=m(1),fa=m(-1),ea=u(-1,2147483647),q=u(0,-2147483648),ga=m(16777216);function x(a){return a.e*s+(0<=a.h?a.h:s+a.h)}
l.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(y(this))return"0";if(0>this.e){if(z(this,q)){var b=n(a),c=A(this,b),b=B(c.multiply(b),this);return c.toString(a)+b.h.toString(a)}return"-"+r(this).toString(a)}for(var c=n(Math.pow(a,6)),b=this,d="";;){var e=A(b,c),f=B(b,e.multiply(c)).h.toString(a),b=e;if(y(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function y(a){return 0==a.e&&0==a.h}function z(a,b){return a.e==b.e&&a.h==b.h}
l.prototype.compare=function(a){if(z(this,a))return 0;var b=0>this.e,c=0>a.e;return b&&!c?-1:!b&&c?1:0>B(this,a).e?-1:1};function r(a){return z(a,q)?q:u(~a.h,~a.e).add(w)}l.prototype.add=function(a){var b=this.e>>>16,c=this.e&65535,d=this.h>>>16,e=a.e>>>16,f=a.e&65535,g=a.h>>>16,h;h=0+((this.h&65535)+(a.h&65535));a=0+(h>>>16);a+=d+g;d=0+(a>>>16);d+=c+f;c=0+(d>>>16);c=c+(b+e)&65535;return u((a&65535)<<16|h&65535,c<<16|d&65535)};function B(a,b){return a.add(r(b))}
l.prototype.multiply=function(a){if(y(this)||y(a))return p;if(z(this,q))return 1==(a.h&1)?q:p;if(z(a,q))return 1==(this.h&1)?q:p;if(0>this.e)return 0>a.e?r(this).multiply(r(a)):r(r(this).multiply(a));if(0>a.e)return r(this.multiply(r(a)));if(0>this.compare(ga)&&0>a.compare(ga))return n(x(this)*x(a));var b=this.e>>>16,c=this.e&65535,d=this.h>>>16,e=this.h&65535,f=a.e>>>16,g=a.e&65535,h=a.h>>>16;a=a.h&65535;var I,t,C,sa;sa=0+e*a;C=0+(sa>>>16);C+=d*a;t=0+(C>>>16);C=(C&65535)+e*h;t+=C>>>16;C&=65535;t+=
c*a;I=0+(t>>>16);t=(t&65535)+d*h;I+=t>>>16;t&=65535;t+=e*g;I+=t>>>16;t&=65535;I=I+(b*a+c*h+d*g+e*f)&65535;return u(C<<16|sa&65535,I<<16|t)};
function A(a,b){if(y(b))throw Error("division by zero");if(y(a))return p;if(z(a,q)){if(z(b,w)||z(b,fa))return q;if(z(b,q))return w;var c;c=1;if(0==c)c=a;else{var d=a.e;c=32>c?u(a.h>>>c|d<<32-c,d>>c):u(d>>c-32,0<=d?0:-1)}c=A(c,b).shiftLeft(1);if(z(c,p))return 0>b.e?w:fa;d=B(a,b.multiply(c));return c.add(A(d,b))}if(z(b,q))return p;if(0>a.e)return 0>b.e?A(r(a),r(b)):r(A(r(a),b));if(0>b.e)return r(A(a,r(b)));for(var e=p,d=a;0<=d.compare(b);){c=Math.max(1,Math.floor(x(d)/x(b)));for(var f=Math.ceil(Math.log(c)/
Math.LN2),f=48>=f?1:Math.pow(2,f-48),g=n(c),h=g.multiply(b);0>h.e||0<h.compare(d);)c-=f,g=n(c),h=g.multiply(b);y(g)&&(g=w);e=e.add(g);d=B(d,h)}return e}l.prototype.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.h;return 32>a?u(b<<a,this.e<<a|b>>>32-a):u(0,b<<a-32)};function ha(a,b){b&=63;if(0==b)return a;var c=a.e;return 32>b?u(a.h>>>b|c<<32-b,c>>>b):32==b?u(c,0):u(c>>>b-32,0)};var D="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},E="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===ba(a)};function F(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(E(a)){if(E(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!F(a[c],b[c]))return!1;return!0}return!1}if(a.s)return a.s(b);if(null!=b&&"object"===typeof b){if(b.s)return b.s(a);var d=c=0,e=D(b).length,f;for(f in a)if(a.hasOwnProperty(f))if(d++,"$com$cognitect$transit$hashCode$"==f)b[f]||(c=-1);else if(!b.hasOwnProperty(f)||!F(a[f],b[f]))return!1;return d+c===e}}return!1}
function ia(a,b){return a^b+2654435769+(a<<6)+(a>>2)}var ja={},ka=0;function la(a){var b=0;if(null!=a.forEach)a.forEach(function(a,c){b=(b+(G(c)^G(a)))%4503599627370496});else for(var c=D(a),d=0;d<c.length;d++){var e=c[d];if("$com$cognitect$transit$hashCode$"!==e)var f=a[e],b=(b+(G(e)^G(f)))%4503599627370496}return b}
function ma(a){var b=a.$com$cognitect$transit$hashCode$||0;if(0===b)if(E(a)){for(var c=0;c<a.length;c++)b=ia(b,G(a[c]));a.$com$cognitect$transit$hashCode$=b}else a.forEach&&a.forEach(function(a){b=ia(b,G(a))});return b}
function G(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":var b=ja[a];if(null==b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;ka++;256<=ka&&(ja={},ka=1);ja[a]=b}a=b;return a;default:return a instanceof Date?a.valueOf():E(a)?ma(a):a.w?a.w():a.$com$cognitect$transit$hashCode$?a.$com$cognitect$transit$hashCode$:la(a)}};var na={};function H(a,b){this.tag=a;this.rep=b;this.k=-1}H.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};H.prototype.B=function(a){return F(this,a)};H.prototype.equiv=H.prototype.B;H.prototype.s=function(a){return a instanceof H?this.tag===a.tag&&F(this.rep,a.rep):!1};H.prototype.w=function(){-1===this.k&&(this.k=ia(G(this.tag),G(this.rep)));return this.k};function J(a,b){return new H(a,b)}var oa=v("9007199254740992"),pa=v("-9007199254740992");
function qa(a){if("number"===typeof a||a instanceof l)return a;a=v(a,10);return 0<a.compare(oa)||0>a.compare(pa)?a:x(a)}l.prototype.B=function(a){return F(this,a)};l.prototype.equiv=l.prototype.B;l.prototype.s=function(a){return a instanceof l&&z(this,a)};l.prototype.w=function(){return this.h};function ra(a){return J("n",a)}function ta(a){return J("f",a)}function K(a){this.name=a;this.k=-1}K.prototype.toString=function(){return":"+this.name};K.prototype.B=function(a){return F(this,a)};
K.prototype.equiv=K.prototype.B;K.prototype.s=function(a){return a instanceof K&&this.name==a.name};K.prototype.w=function(){-1===this.k&&(this.k=G(this.name));return this.k};function ua(a){return new K(a)}function L(a){this.name=a;this.k=-1}L.prototype.toString=function(){return"[Symbol: "+this.name+"]"};L.prototype.B=function(a){return F(this,a)};L.prototype.equiv=L.prototype.B;L.prototype.s=function(a){return a instanceof L&&this.name==a.name};
L.prototype.w=function(){-1===this.k&&(this.k=G(this.name));return this.k};function va(a){return new L(a)}function M(a,b,c){var d="";c=c||b+1;for(var e=8*(7-b),f=m(255).shiftLeft(e);b<c;b++,e-=8,f=ha(f,8)){var g=ha(u(a.h&f.h,a.e&f.e),e).toString(16);1==g.length&&(g="0"+g);d+=g}return d}function N(a,b){this.V=a;this.X=b;this.k=-1}N.prototype.toString=function(a){var b=this.V,c=this.X;a=""+(M(b,0,4)+"-");a+=M(b,4,6)+"-";a+=M(b,6,8)+"-";a+=M(c,0,2)+"-";return a+=M(c,2,8)};
N.prototype.B=function(a){return F(this,a)};N.prototype.equiv=N.prototype.B;N.prototype.s=function(a){return a instanceof N&&z(this.V,a.V)&&z(this.X,a.X)};N.prototype.w=function(){-1===this.k&&(this.k=G(this.toString()));return this.k};
function wa(a){a=a.replace(/-/g,"");for(var b=null,c=null,d=c=0,e=24,f=0,f=c=0,e=24;8>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;f=8;for(e=24;16>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;b=u(d,c);c=0;f=16;for(e=24;24>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;for(e=f=24;32>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;c=u(d,c);return new N(b,c)}function xa(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)}
Date.prototype.s=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.w=function(){return this.valueOf()};function ya(a){return J("b",a)}function za(a){return J("r",a)}function O(a,b){this.v=a;this.type=b||0;this.l=0}O.prototype.next=function(){if(this.l<this.v.length){var a=null,a=0===this.type?this.v[this.l]:1===this.type?this.v[this.l+1]:[this.v[this.l],this.v[this.l+1]],a={value:a,done:!1};this.l+=2;return a}return{value:null,done:!0}};O.prototype.next=O.prototype.next;
function P(a,b){this.map=a;this.type=b||0;this.keys=Aa(this.map);this.l=0;this.G=null;this.C=0}P.prototype.next=function(){if(this.l<this.map.size){null!=this.G&&this.C<this.G.length||(this.G=this.map.map[this.keys[this.l]],this.C=0);var a=null,a=0===this.type?this.G[this.C]:1===this.type?this.G[this.C+1]:[this.G[this.C],this.G[this.C+1]],a={value:a,done:!1};this.l++;this.C+=2;return a}return{value:null,done:!0}};P.prototype.next=P.prototype.next;
function Ba(a,b){if((b instanceof Q||b instanceof R)&&a.size===b.size){for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!F(d[e+1],b.get(d[e])))return!1;return!0}if(null!=b&&"object"===typeof b&&(c=D(b).length-(b.hasOwnProperty("$com$cognitect$transit$hashCode$")&&1||0),a.size===c)){for(d in b)if("$com$cognitect$transit$hashCode$"!==d&&!F(b[d],a.get(d)))return!1;return!0}return!1}function R(a){this.g=a;this.a=null;this.k=-1;this.size=a.length/2;this.aa=0}R.prototype.toString=function(){return"[TransitArrayMap]"};
function Ca(a){if(a.a)throw Error("Invalid operation, already converted");if(8>a.size)return!1;a.aa++;return 32<a.aa?(a.a=S(a.g,!1,!0),a.g=[],!0):!1}R.prototype.clear=function(){this.a?this.a.clear():this.g=[];this.size=0};R.prototype.clear=R.prototype.clear;R.prototype.keys=function(){return this.a?this.a.keys():new O(this.g,0)};R.prototype.keys=R.prototype.keys;R.prototype.H=function(){if(this.a)return this.a.H();for(var a=[],b=0,c=0;c<this.g.length;b++,c+=2)a[b]=this.g[c];return a};
R.prototype.keySet=R.prototype.H;R.prototype.v=function(){return this.a?this.a.v():new O(this.g,2)};R.prototype.entries=R.prototype.v;R.prototype.I=function(){return this.a?this.a.I():new O(this.g,1)};R.prototype.values=R.prototype.I;R.prototype.forEach=function(a){if(this.a)this.a.forEach(a);else for(var b=0;b<this.g.length;b+=2)a(this.g[b+1],this.g[b])};R.prototype.forEach=R.prototype.forEach;
R.prototype.get=function(a){if(this.a)return this.a.get(a);if(Ca(this))return this.get(a);for(var b=0;b<this.g.length;b+=2)if(F(this.g[b],a))return this.g[b+1];return null};R.prototype.get=R.prototype.get;R.prototype.D=function(a){if(this.a)return this.a.D(a);if(Ca(this))return this.D(a);for(var b=0;b<this.g.length;b+=2)if(F(this.g[b],a))return!0;return!1};R.prototype.has=R.prototype.D;
R.prototype.set=function(a,b){if(this.a)this.a.set(a,b),this.size=this.a.size;else{for(var c=0;c<this.g.length;c+=2)if(F(this.g[c],a)){this.g[c+1]=b;return}this.g.push(a);this.g.push(b);this.size++;32<this.size&&(this.a=S(this.g,!1,!0),this.g=null)}};R.prototype.set=R.prototype.set;R.prototype["delete"]=function(a){if(this.a)this.a["delete"](a),this.size=this.a.size;else for(var b=0;b<this.g.length;b+=2)if(F(this.g[b],a)){this.g.splice(b,2);this.size--;break}};
R.prototype.w=function(){if(this.a)return this.a.w();-1===this.k&&(this.k=la(this));return this.k};R.prototype.s=function(a){return this.a?Ba(this.a,a):Ba(this,a)};function Q(a,b,c){this.map=b||{};this.J=a||[];this.size=c||0;this.k=-1}Q.prototype.toString=function(){return"[TransitMap]"};Q.prototype.clear=function(){this.map={};this.J=[];this.size=0;this.k=-1};Q.prototype.clear=Q.prototype.clear;function Aa(a){return null!=a.J?a.J:D(a.map)}
Q.prototype["delete"]=function(a){this.J=null;for(var b=G(a),c=this.map[b],d=0;d<c.length;d+=2)if(F(a,c[d])){c.splice(d,2);0===c.length&&delete this.map[b];this.size--;break}};Q.prototype.v=function(){return new P(this,2)};Q.prototype.entries=Q.prototype.v;Q.prototype.forEach=function(a){for(var b=Aa(this),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};Q.prototype.forEach=Q.prototype.forEach;
Q.prototype.get=function(a){var b=G(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2){if(F(a,b[c]))return b[c+1]}else return null};Q.prototype.get=Q.prototype.get;Q.prototype.D=function(a){var b=G(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2)if(F(a,b[c]))return!0;return!1};Q.prototype.has=Q.prototype.D;Q.prototype.keys=function(){return new P(this,0)};Q.prototype.keys=Q.prototype.keys;
Q.prototype.H=function(){for(var a=Aa(this),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};Q.prototype.keySet=Q.prototype.H;Q.prototype.set=function(a,b){var c=G(a),d=this.map[c];if(null==d)this.J&&this.J.push(c),this.map[c]=[a,b],this.size++;else{for(var c=!0,e=0;e<d.length;e+=2)if(F(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};Q.prototype.set=Q.prototype.set;Q.prototype.I=function(){return new P(this,1)};Q.prototype.values=Q.prototype.I;
Q.prototype.w=function(){-1===this.k&&(this.k=la(this));return this.k};Q.prototype.s=function(a){return Ba(this,a)};
function S(a,b,c){a=a||[];b=!1===b?b:!0;if((!0!==c||!c)&&64>=a.length){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(F(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new R(a)}var d={},e=[],f=0;for(b=0;b<a.length;b+=2){c=G(a[b]);var g=d[c];if(null==g)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var h=!0;for(c=0;c<g.length;c+=2)if(F(g[c],a[b])){g[c+1]=a[b+1];h=!1;break}h&&(g.push(a[b]),g.push(a[b+1]),f++)}}return new Q(e,d,f)}
function T(a){this.map=a;this.size=a.size}T.prototype.toString=function(){return"[TransitSet]"};T.prototype.add=function(){throw Error("Unsupported operation: add");};T.prototype.add=T.prototype.add;T.prototype.clear=function(){this.map=new Q;this.size=0};T.prototype.clear=T.prototype.clear;T.prototype["delete"]=function(a){this.map["delete"](a);this.size=this.map.size};T.prototype.v=function(){return this.map.v()};T.prototype.entries=T.prototype.v;
T.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};T.prototype.forEach=T.prototype.forEach;T.prototype.D=function(a){return this.map.D(a)};T.prototype.has=T.prototype.D;T.prototype.keys=function(){return this.map.keys()};T.prototype.keys=T.prototype.keys;T.prototype.H=function(){return this.map.H()};T.prototype.keySet=T.prototype.H;T.prototype.I=function(){return this.map.I()};T.prototype.values=T.prototype.I;
T.prototype.s=function(a){if(a instanceof T){if(this.size===a.size)return F(this.map,a.map)}else return!1};T.prototype.w=function(){return G(this.map)};function Da(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=G(a[e]),g=b[f];if(null==g)c.push(f),b[f]=[a[e],a[e]],d++;else{for(var f=!0,h=0;h<g.length;h+=2)if(F(g[h],a[e])){f=!1;break}f&&(g.push(a[e]),g.push(a[e]),d++)}}return new T(new Q(c,b,d))}function Ea(a){return J("'",a)}function Fa(a){return J("list",a)}
function Ga(a){return J("link",a)};function Ha(a,b){if(3<a.length){if(b)return!0;var c=a.charAt(1);return"~"===a.charAt(0)?":"===c||"$"===c||"#"===c:!1}return!1}function Ia(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return 0===b?"^"+a:"^"+String.fromCharCode(b+48)+a}function Ja(){this.da=this.N=this.l=0;this.q={}}
Ja.prototype.write=function(a,b){if(Ha(a,b)){4096===this.da?(this.clear(),this.N=0,this.q={}):1936===this.l&&this.clear();var c=this.q[a];return null==c?(this.q[a]=[Ia(this.l),this.N],this.l++,a):c[1]!=this.N?(c[1]=this.N,c[0]=Ia(this.l),this.l++,a):c[0]}return a};Ja.prototype.clear=function(){this.l=0;this.N++};function Ka(){this.l=0;this.q=[]}Ka.prototype.write=function(a){1936==this.l&&(this.l=0);this.q[this.l]=a;this.l++;return a};
Ka.prototype.Z=function(a){return this.q[2===a.length?a.charCodeAt(1)-48:44*(a.charCodeAt(1)-48)+(a.charCodeAt(2)-48)]};Ka.prototype.clear=function(){this.l=0};function La(a){this.R=a}
function U(a){this.options=a||{};this.p={};for(var b in this.P.p)this.p[b]=this.P.p[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.p[b]=this.options.handlers[b]}this.Q=null!=this.options.preferStrings?this.options.preferStrings:this.P.Q;this.T=this.options.defaultHandler||this.P.T;this.A=this.options.mapBuilder;this.K=this.options.arrayBuilder}
U.prototype.P={p:{_:function(){return null},"?":function(a){return"t"===a},b:function(a){return ya(a)},i:function(a){return qa(a)},n:function(a){return ra(a)},d:function(a){return parseFloat(a)},f:function(a){return ta(a)},c:function(a){return a},":":function(a){return ua(a)},$:function(a){return va(a)},r:function(a){return za(a)},"'":function(a){return a},m:function(a){return xa(a)},t:function(a){return new Date(a)},u:function(a){return wa(a)},set:function(a){return Da(a)},list:function(a){return Fa(a)},
link:function(a){return Ga(a)},cmap:function(a){return S(a,!1)}},T:function(a,b){return J(a,b)},Q:!0};
U.prototype.j=function(a,b,c,d){if(null==a)return null;switch(typeof a){case "string":return Ha(a,c)?(a=Ma(this,a),b&&b.write(a,c),b=a):b="^"===a.charAt(0)?b.Z(a,c):Ma(this,a),b;case "object":if(E(a))if("^ "===a[0])if(this.A)if(17>a.length&&this.A.M){d=[];for(c=1;c<a.length;c+=2)d.push(this.j(a[c],b,!0,!1)),d.push(this.j(a[c+1],b,!1,!1));b=this.A.M(d)}else{d=this.A.W();for(c=1;c<a.length;c+=2)d=this.A.add(d,this.j(a[c],b,!0,!1),this.j(a[c+1],b,!1,!1));b=this.A.U(d)}else{d=[];for(c=1;c<a.length;c+=
2)d.push(this.j(a[c],b,!0,!1)),d.push(this.j(a[c+1],b,!1,!1));b=S(d,!1)}else b=Na(this,a,b,d);else{c=D(a);var e=c[0];if((d=1==c.length?this.j(e,b,!1,!1):null)&&d instanceof La)a=a[e],c=this.p[d.R],b=null!=c?c(this.j(a,b,!1,!0)):J(d.R,this.j(a,b,!1,!1));else if(this.A)if(16>c.length&&this.A.M){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.j(e,b,!0,!1)),f.push(this.j(a[e],b,!1,!1));b=this.A.M(f)}else{f=this.A.W();for(d=0;d<c.length;d++)e=c[d],f=this.A.add(f,this.j(e,b,!0,!1),this.j(a[e],b,!1,!1));
b=this.A.U(f)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.j(e,b,!0,!1)),f.push(this.j(a[e],b,!1,!1));b=S(f,!1)}}return b}return a};U.prototype.decode=U.prototype.j;
function Na(a,b,c,d){if(d){var e=[];for(d=0;d<b.length;d++)e.push(a.j(b[d],c,!1,!1));return e}if(2===b.length&&"string"===typeof b[0]&&(d=a.j(b[0],c,!1,!1))&&d instanceof La)return b=b[1],e=a.p[d.R],null!=e?e=e(a.j(b,c,!1,!0)):J(d.R,a.j(b,c,!1,!1));if(a.K){if(32>=b.length&&a.K.M){e=[];for(d=0;d<b.length;d++)e.push(a.j(b[d],c,!1,!1));return a.K.M(e)}e=a.K.W();for(d=0;d<b.length;d++)e=a.K.add(e,a.j(b[d],c,!1,!1));return a.K.U(e)}e=[];for(d=0;d<b.length;d++)e.push(a.j(b[d],c,!1,!1));return e}
function Ma(a,b){if("~"===b.charAt(0)){var c=b.charAt(1);if("~"===c||"^"===c||"`"===c)return b.substring(1);if("#"===c)return new La(b.substring(2));var d=a.p[c];return null==d?a.T(c,b.substring(2)):d(b.substring(2))}return b};function Oa(a){this.ea=new U(a)}function Pa(a,b){this.ga=a;this.options=b||{};this.q=this.options.cache?this.options.cache:new Ka}Pa.prototype.Z=function(a){var b=this.q;a=this.ga.ea.j(JSON.parse(a),b);this.q.clear();return a};Pa.prototype.read=Pa.prototype.Z;var Qa=0;function Ra(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a.com$cognitect$transit$ctor$guid;null==b&&(a.com$cognitect$transit$ctor$guid=b=++Qa);return b}function V(a){return null==a?null:a.constructor}function W(a,b){for(var c=a.toString(),d=c.length;d<b;d++)c="0"+c;return c}function Sa(){}Sa.prototype.tag=function(){return"_"};Sa.prototype.rep=function(){return null};
Sa.prototype.o=function(){return"null"};function Ta(){}Ta.prototype.tag=function(){return"s"};Ta.prototype.rep=function(a){return a};Ta.prototype.o=function(a){return a};function Ua(){}Ua.prototype.tag=function(){return"i"};Ua.prototype.rep=function(a){return a};Ua.prototype.o=function(a){return a.toString()};function Va(){}Va.prototype.tag=function(){return"i"};Va.prototype.rep=function(a){return a.toString()};Va.prototype.o=function(a){return a.toString()};function Wa(){}Wa.prototype.tag=function(){return"?"};
Wa.prototype.rep=function(a){return a};Wa.prototype.o=function(a){return a.toString()};function Xa(){}Xa.prototype.tag=function(){return"array"};Xa.prototype.rep=function(a){return a};Xa.prototype.o=function(){return null};function Ya(){}Ya.prototype.tag=function(){return"map"};Ya.prototype.rep=function(a){return a};Ya.prototype.o=function(){return null};function Za(){}Za.prototype.tag=function(){return"t"};
Za.prototype.rep=function(a){return a.getUTCFullYear()+"-"+W(a.getUTCMonth()+1,2)+"-"+W(a.getUTCDate(),2)+"T"+W(a.getUTCHours(),2)+":"+W(a.getUTCMinutes(),2)+":"+W(a.getUTCSeconds(),2)+"."+W(a.getUTCMilliseconds(),3)+"Z"};Za.prototype.o=function(a,b){return b.rep(a)};function X(){}X.prototype.tag=function(){return"m"};X.prototype.rep=function(a){return a.valueOf()};X.prototype.o=function(a){return a.valueOf().toString()};X.prototype.ba=function(){return new Za};function $a(){}$a.prototype.tag=function(){return"u"};
$a.prototype.rep=function(a){return a.toString()};$a.prototype.o=function(a){return a.toString()};function ab(){}ab.prototype.tag=function(){return":"};ab.prototype.rep=function(a){return a.name};ab.prototype.o=function(a,b){return b.rep(a)};function bb(){}bb.prototype.tag=function(){return"$"};bb.prototype.rep=function(a){return a.name};bb.prototype.o=function(a,b){return b.rep(a)};function cb(){}cb.prototype.tag=function(a){return a.tag};cb.prototype.rep=function(a){return a.rep};
cb.prototype.o=function(){return null};function db(){}db.prototype.tag=function(){return"set"};db.prototype.rep=function(a){var b=[];a.forEach(function(a){b.push(a)});return J("array",b)};db.prototype.o=function(){return null};function eb(){}eb.prototype.tag=function(){return"map"};eb.prototype.rep=function(a){return a};eb.prototype.o=function(){return null};function fb(){}fb.prototype.tag=function(){return"map"};fb.prototype.rep=function(a){return a};fb.prototype.o=function(){return null};
function gb(){this.p={};this.set(null,new Sa);this.set(String,new Ta);this.set(Number,new Ua);this.set(l,new Va);this.set(Boolean,new Wa);this.set(Array,new Xa);this.set(Object,new Ya);this.set(Date,new X);this.set(N,new $a);this.set(K,new ab);this.set(L,new bb);this.set(H,new cb);this.set(T,new db);this.set(R,new eb);this.set(Q,new fb)}gb.prototype.get=function(a){return this.p[Ra(a)]};gb.prototype.set=function(a,b){this.p[Ra(a)]=b};function hb(a){this.F=a||{};this.Q=null!=this.F.preferStrings?this.F.preferStrings:!0;this.ca=this.F.objectBuilder||null;this.p=new gb;if(this.F.handlers){var b=this;this.F.handlers.forEach(function(a,d){b.p.set(d,a)})}this.S=this.F.unpack||function(a){return a instanceof R&&null===a.a?a.g:!1};this.O=this.F&&this.F.verbose||!1}function Y(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a}
function ib(a,b,c){var d=[];if(E(b))for(var e=0;e<b.length;e++)d.push(Z(a,b[e],!1,c));else b.forEach(function(b){d.push(Z(a,b,!1,c))});return d}function jb(a,b){if("string"!==typeof b){var c=a.p.get(V(b));return c&&1===c.tag(b).length}return!0}function kb(a,b){var c=a.S(b),d=!0;if(c)for(var e=0;e<c.length&&(d=jb(a,c[e]),d);e+=2);else for(c=b.keys(),step=c.next();!step.done;){d=jb(a,step.value);if(!d)break;step=c.next()}return d}
function lb(a,b,c){if(b.constructor===Object||null!=b.forEach){if(a.O){if(null!=b.forEach)if(kb(a,b)){var d={};b.forEach(function(b,e){d[Z(a,e,!0,!1)]=Z(a,b,!1,c)})}else{var e=a.S(b),f=[],g=Y("~#","cmap","",!0,c);if(e)for(var h=0;h<e.length;h+=2)f.push(Z(a,e[h],!0,!1)),f.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Z(a,d,!0,!1));f.push(Z(a,b,!1,c))});d={};d[g]=f}else for(d={},e=D(b),h=0;h<e.length;h++)d[Z(a,e[h],!0,!1)]=Z(a,b[e[h]],!1,c);return d}if(null!=b.forEach){if(kb(a,b)){e=a.S(b);
d=["^ "];if(e)for(h=0;h<e.length;h+=2)d.push(Z(a,e[h],!0,c)),d.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,e){d.push(Z(a,e,!0,c));d.push(Z(a,b,!1,c))});return d}e=a.S(b);f=[];g=Y("~#","cmap","",!0,c);if(e)for(h=0;h<e.length;h+=2)f.push(Z(a,e[h],!0,c)),f.push(Z(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Z(a,d,!0,c));f.push(Z(a,b,!1,c))});return[g,f]}d=["^ "];e=D(b);for(h=0;h<e.length;h++)d.push(Z(a,e[h],!0,c)),d.push(Z(a,b[e[h]],!1,c));return d}if(null!=a.ca)return a.ca(b,function(b){return Z(a,
b,!0,c)},function(b){return Z(a,b,!1,c)});h=V(b).name;e=Error("Cannot write "+h);e.data={Y:b,type:h};throw e;}
function Z(a,b,c,d){var e=a.p.get(V(b)),f=e?e.tag(b):null,g=e?e.rep(b):null;if(null!=e&&null!=f)switch(f){case "_":return c?Y("~","_","",c,d):null;case "s":return 0<g.length?(a=g.charAt(0),a="~"===a||"^"===a||"`"===a?"~"+g:g):a=g,Y("","",a,c,d);case "?":return c?Y("~","?",g.toString()[0],c,d):g;case "i":return c||"string"===typeof g||g instanceof l?Y("~","i",g.toString(),c,d):g;case "d":return c?Y(g.ha,"d",g,c,d):g;case "b":return Y("~","b",g,c,d);case "'":return a.O?(b={},c=Y("~#","'","",!0,d),b[c]=
Z(a,g,!1,d),d=b):d=[Y("~#","'","",!0,d),Z(a,g,!1,d)],d;case "array":return ib(a,g,d);case "map":return lb(a,g,d);default:a:{if(1===f.length){if("string"===typeof g){d=Y("~",f,g,c,d);break a}if(c||a.Q){(a=a.O&&e.ba())?(f=a.tag(b),g=a.o(b,a)):g=e.o(b,e);if(null!==g){d=Y("~",f,g,c,d);break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:g,Y:b};throw d;}}b=f;c=g;a.O?(g={},g[Y("~#",b,"",!0,d)]=Z(a,c,!1,d),d=g):d=[Y("~#",b,"",!0,d),Z(a,c,!1,d)]}return d}else throw d=V(b).name,a=Error("Cannot write "+
d),a.data={Y:b,type:d},a;}function mb(a,b){var c=a.p.get(V(b));if(null!=c)return 1===c.tag(b).length?Ea(b):b;var c=V(b).name,d=Error("Cannot write "+c);d.data={Y:b,type:c};throw d;}function $(a,b){this.L=a;this.options=b||{};this.q=!1===this.options.cache?null:this.options.cache?this.options.cache:new Ja}$.prototype.fa=function(){return this.L};$.prototype.marshaller=$.prototype.fa;
$.prototype.write=function(a,b){var c=null,c=b||{};asMapKey=c.asMapKey||!1;cache=this.L.O?!1:this.q;if(!1===c.marshalTop)c=Z(this.L,a,asMapKey,cache);else var c=this.L,d=asMapKey,e=cache,c=JSON.stringify(Z(c,mb(c,a),d,e));null!=this.q&&this.q.clear();return c};$.prototype.write=$.prototype.write;$.prototype.register=function(a,b){this.L.p.set(a,b)};$.prototype.register=$.prototype.register;k("transit.reader",function(a,b){if("json"===a||"json-verbose"===a||null==a){var c=new Oa(b);return new Pa(c,b)}throw Error("Cannot create reader of type "+a);});k("transit.writer",function(a,b){if("json"===a||"json-verbose"===a||null==a){"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0);var c=new hb(b);return new $(c,b)}c=Error('Type must be "json"');c.data={type:a};throw c;});k("transit.makeBuilder",function(a){function b(){}b.prototype.W=a.init;b.prototype.add=a.add;b.prototype.U=a.finalize;return new b});
k("transit.makeWriteHandler",function(a){function b(){}b.prototype.tag=a.tag;b.prototype.rep=a.rep;b.prototype.o=a.stringRep;b.prototype.ba=a.getVerboseHandler;return new b});k("transit.date",xa);k("transit.integer",qa);k("transit.isInteger",function(a){return a instanceof l});k("transit.uuid",function(a){return wa(a)});k("transit.isUUID",function(a){return a instanceof N});k("transit.bigInt",ra);k("transit.isBigInt",function(a){return a instanceof H&&"n"===a.tag});k("transit.bigDec",ta);
k("transit.isBigDec",function(a){return a instanceof H&&"f"===a.tag});k("transit.keyword",ua);k("transit.isKeyword",function(a){return a instanceof K});k("transit.symbol",va);k("transit.isSymbol",function(a){return a instanceof L});k("transit.binary",ya);k("transit.isBinary",function(a){return a instanceof H&&"b"===a.tag});k("transit.uri",za);k("transit.isURI",function(a){return a instanceof H&&"r"===a.tag});k("transit.map",S);k("transit.isMap",function(a){return a instanceof R||a instanceof Q});
k("transit.set",Da);k("transit.isSet",function(a){return a instanceof T});k("transit.list",Fa);k("transit.isList",function(a){return a instanceof na.ia&&"list"===a.tag});k("transit.quoted",Ea);k("transit.isQuoted",function(a){return a instanceof H&&"'"===a.tag});k("transit.tagged",J);k("transit.isTaggedValue",function(a){return a instanceof H});k("transit.link",Ga);k("transit.isLink",function(a){return a instanceof H&&"link"===a.tag});k("transit.hash",G);k("transit.hashKey","$com$cognitect$transit$hashCode$");
k("transit.hashMapLike",la);k("transit.hashArrayLike",ma);k("transit.equals",F);k("transit.extendToEQ",function(a,b){a.w=b.hashCode;a.s=b.equals;return a});k("transit.mapToObject",function(a){var b={};a.forEach(function(a,d){if("string"!==typeof d)throw Error("Cannot convert map with non-string keys");b[d]=a});return b});k("transit.decoder",function(a){return new U(a)});k("transit.UUIDfromString",wa);k("transit.randomUUID",na.ja);k("transit.stringableKeys",kb);})();
